// Nombres de países (y de sus selecciones) en castellano: ESPN los publica en inglés.
export const COUNTRY: Record<string, string> = {
  Argentina: "Argentina", Brazil: "Brasil", Uruguay: "Uruguay", Paraguay: "Paraguay", Chile: "Chile", Colombia: "Colombia", Peru: "Perú",
  Ecuador: "Ecuador", Bolivia: "Bolivia", Venezuela: "Venezuela", Mexico: "México", "United States": "Estados Unidos", Spain: "España",
  Italy: "Italia", Germany: "Alemania", France: "Francia", England: "Inglaterra", Portugal: "Portugal", Netherlands: "Países Bajos",
  Belgium: "Bélgica", Croatia: "Croacia", Morocco: "Marruecos", Japan: "Japón", Norway: "Noruega", Poland: "Polonia", Senegal: "Senegal",
  Nigeria: "Nigeria", Ghana: "Ghana", "Ivory Coast": "Costa de Marfil", Cameroon: "Camerún", Egypt: "Egipto", Turkey: "Turquía",
  Switzerland: "Suiza", Austria: "Austria", Denmark: "Dinamarca", Sweden: "Suecia", Scotland: "Escocia", Wales: "Gales", Serbia: "Serbia",
  Ukraine: "Ucrania", "South Korea": "Corea del Sur", Canada: "Canadá", "Saudi Arabia": "Arabia Saudita", Algeria: "Argelia", Greece: "Grecia",
  "Czech Republic": "Chequia", Czechia: "Chequia", Hungary: "Hungría", Romania: "Rumania", Slovenia: "Eslovenia", Slovakia: "Eslovaquia",
  Ireland: "Irlanda", "Republic of Ireland": "Irlanda", Australia: "Australia", "Costa Rica": "Costa Rica", Panama: "Panamá", Honduras: "Honduras",
  Jamaica: "Jamaica", Georgia: "Georgia", Albania: "Albania", Iran: "Irán", Tunisia: "Túnez", Mali: "Malí", "DR Congo": "RD del Congo",
  Uzbekistan: "Uzbekistán",
  Tajikistan: "Tayikistán",
  India: "India",
  Russia: "Rusia",
  Niger: "Níger",
  Jordan: "Jordania",
  China: "China",
  "China PR": "China",
  Benin: "Benín",
  Qatar: "Catar",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  Iraq: "Irak",
  Oman: "Omán",
  Bahrain: "Baréin",
  Kuwait: "Kuwait",
  Syria: "Siria",
  Lebanon: "Líbano",
  Palestine: "Palestina",
  Thailand: "Tailandia",
  Vietnam: "Vietnam",
  Indonesia: "Indonesia",
  Malaysia: "Malasia",
  Philippines: "Filipinas",
  "North Korea": "Corea del Norte",
  "Korea Republic": "Corea del Sur",
  Kazakhstan: "Kazajistán",
  Kyrgyzstan: "Kirguistán",
  Turkmenistan: "Turkmenistán",
  Afghanistan: "Afganistán",
  Pakistan: "Pakistán",
  "New Zealand": "Nueva Zelanda",
  "Türkiye": "Turquía",
  Cyprus: "Chipre",
  Latvia: "Letonia",
  Lithuania: "Lituania",
  Estonia: "Estonia",
  Finland: "Finlandia",
  Iceland: "Islandia",
  "Northern Ireland": "Irlanda del Norte",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  Montenegro: "Montenegro",
  Armenia: "Armenia",
  Azerbaijan: "Azerbaiyán",
  Belarus: "Bielorrusia",
  Moldova: "Moldavia",
  "North Macedonia": "Macedonia del Norte",
  Kosovo: "Kosovo",
  Bulgaria: "Bulgaria",
  Luxembourg: "Luxemburgo",
  Malta: "Malta",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Liechtenstein: "Liechtenstein",
  Gibraltar: "Gibraltar",
  "Faroe Islands": "Islas Feroe",
  Israel: "Israel",
  Cuba: "Cuba",
  Haiti: "Haití",
  "El Salvador": "El Salvador",
  Guatemala: "Guatemala",
  Nicaragua: "Nicaragua",
  "Trinidad and Tobago": "Trinidad y Tobago",
  Curacao: "Curazao",
  "Curaçao": "Curazao",
  Suriname: "Surinam",
  Guyana: "Guyana",
  "South Africa": "Sudáfrica",
  "Cape Verde": "Cabo Verde",
  "Cape Verde Islands": "Cabo Verde",
  "Burkina Faso": "Burkina Faso",
  Guinea: "Guinea",
  "Equatorial Guinea": "Guinea Ecuatorial",
  Gabon: "Gabón",
  Kenya: "Kenia",
  Uganda: "Uganda",
  Tanzania: "Tanzania",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabue",
  Angola: "Angola",
  Mozambique: "Mozambique",
  Madagascar: "Madagascar",
  Sudan: "Sudán",
  Libya: "Libia",
  Mauritania: "Mauritania",
  Togo: "Togo",
  Ethiopia: "Etiopía",
  "Congo DR": "RD del Congo",
  Congo: "Congo",
  Namibia: "Namibia",
  Botswana: "Botsuana",
  Rwanda: "Ruanda",
  "Sierra Leone": "Sierra Leona",
  Liberia: "Liberia",
  Gambia: "Gambia",
  "Guinea-Bissau": "Guinea-Bisáu",
  Comoros: "Comoras",
  // Selecciones que ya no existen (Copas del Mundo viejas).
  "Germany FR": "Alemania Federal", "West Germany": "Alemania Federal", "Germany DR": "Alemania Democrática", "East Germany": "Alemania Democrática",
  "Soviet Union": "Unión Soviética", USSR: "Unión Soviética", Czechoslovakia: "Checoslovaquia", Yugoslavia: "Yugoslavia", "Serbia and Montenegro": "Serbia y Montenegro", "Serbia & Montenegro": "Serbia y Montenegro",
  Zaire: "Zaire", "Dutch East Indies": "Indias Orientales Neerlandesas", CIS: "CEI",
};
export const countryEs = (c?: string) => (c ? (COUNTRY[c] ?? c) : "");
