// Artículo de Wikipedia de cada club cuando la búsqueda automática no da con el correcto.
// "es:Título" o "en:Título"; null = club sin artículo ni escudo conocido (queda con las iniciales).
const NONE = [
  // Clubes de las primeras décadas sin escudo documentado (o que la búsqueda confunde con otros).
  "saint-andrews", "lobos-athletic", "retiro-athletic", "palermo-athletic", "united-banks", "olivos", "floresta",
  "remedios-escalada", "argentino-banfield", "villa-urquiza", "gimnasia-rosario", "belgrano-rosario", "sparta-rosario",
  "ca-alumni", "everton", "adrogue", "liniers", "wilde", "villa-real", "pineyro", "balcarce", "argentino-avellaneda",
  "martinez", "atlas", "carapachay", "federal", "universitarios", "la-paternal", "retiro-1931", "alvear-caseros",
  "ferrocarriles-estado", "general-belgrano", "argentino-nunez",
  // Clubes del interior y de la Copa Argentina sin artículo propio.
  "empleados-comercio-bolivar", "fortin-vuelta-rojas", "gorriti-jujuy", "correos-salta", "los-andes-sj",
  "san-francisco-la-rioja", "villa-congreso-viedma", "huracan-guatrache", "tnp-corrientes", "talleres-juniors-cr",
  "sol-de-mayo-viedma", "atenas-santo-tome", "independiente-jujuy", "nacional-vsp-mendoza", "regional-resistencia",
  "trafico-pergamino", "boca-tres-arroyos", "cazadores-andes", "deportivo-colon-chivilcoy", "el-socorro-pergamino",
  "graffigna", "independiente-la-rioja", "parana-zarate", "provinciano-tafi", "sportivo-victoria-sl",
  "las-palmeras-san-pedro", "sportivo-union-posadas", "independencia-san-pedro", "independiente-pascanas",
  "san-martin-olavarria", "sportivo-comercio-salta", "sportivo-municipal-rc", "victoria-concordia", "laguna-blanca",
  "san-jorge-santa-fe", "chilecito", "cuervos-fin-del-mundo", "las-heras-concordia", "circulo-italiano",
  "deportivo-curupay", "deportivo-montecaseros", "deportivo-tabacal", "herminio-arrieta", "jorge-ross",
  "petrolero-argentino", "progreso-salta", "san-martin-monte-coman", "independiente-formosa", "comercio-santa-sylvina",
  "independiente-hipolito-yrigoyen", "obrero-zarate", "ocampo-villa-ocampo", "san-carlos-la-escondida",
  "pacifico-neuquen", "colon-juniors-sj", "huracan-comodoro", "defensores-bell-ville", "mercedes",
  "deportivo-25-mayo-lp", "petrolero-austral", "resistencia-central", "sports-salto", "defensores-valeria-del-mar",
  "libertad-concordia", "puerto-san-martin", "deportivo-rincon", "alvear-intendente-alvear", "central-goya",
  "independiente-fernandez", "deportivo-independiente-rio-colorado",
  // Selecciones de liga (Copa Ibarguren) y clubes uruguayos de la era amateur sin escudo conocido.
  "seleccion-tucuman", "liga-cordobesa", "liga-mendocina", "liga-cultural-sde", "deutscher-uy", "bristol-uy",
  "universitario-de-la-paz-bo",
  // Revisión a mano: la búsqueda los confundía con otro club, un mapa o una foto.
  "provincial-rosario", "argentino-rosario", "gimnasia-banfield", "lanus-united", "sportivo-suizo", "union-talleres-lanus",
  "atlanta-argentinos", "gimnasia-lanus", "nacional-adrogue", "union-caseros", "river-plate-villa-maria",
  "ferrocarril-sud-neuquen", "altos-hornos-zapla", "argentinos-del-norte", "central-norte-resistencia", "regina",
  "santa-rosa-lp", "argentino-norte-salta", "central-argentino-sde", "rioja-juniors", "aviador-origone",
  "deportivo-union-catamarca", "huracan-mercedes", "atletico-juventud-sj", "benjamin-matienzo", "gimnasia-mercedes",
  "huracan-san-luis", "racing-colon", "san-pablo-tucuman", "sol-de-mayo-formosa", "sportivo-villa-mercedes", "camioneros",
  "mitre-salta", "san-jorge-tucuman", "sportivo-barracas-colon", "argentinos-25-mayo", "jorge-newbery-cr", "pellegrini-salta",
  "comunicaciones-mercedes", "deportivo-patagones", "monterrico-san-vicente", "argentino-penarol", "sportivo-acassuso",
  "talleres-anatuya", "germinal", "argentino-quilmes-rafaela", "camioneros-norte", "chicoana", "defensores-la-boca",
  "empleados-comercio-mendoza", "estudiantes-unidos", "general-rojo", "instituto-santiago", "las-palmas-cordoba",
  "libertad-campo-santo", "viale", "belgrano-zarate", "union-guemes", "balloffet", "lujan-sport-club", "river-plate-fc-uy",
  "valdez-ec", "argentino-firmat",
];

export const TITLES: Record<string, string | null> = {
  ...Object.fromEntries(NONE.map((id) => [id, null])),
  "concepcion-fc": "Concepción Fútbol Club",
  "atletico-concepcion": "Club Atlético Concepción",
  comunicaciones: "Club Comunicaciones (Buenos Aires)",
  flandria: "Club Social y Deportivo Flandria",
  "del-bono": "Club Sportivo Del Bono",
  sanjustino: "Club Sanjustino",
  "aprendices-casildenses": "Club Atlético Aprendices Casildenses",
  // Clubes del exterior
  "hamburgo-de": "Hamburger SV",
  "al-hilal-sa": "Al-Hilal Saudi Football Club",
  "alajuelense-cr": "Liga Deportiva Alajuelense",
  "bahia-br": "Esporte Clube Bahia",
  "internacional-br": "Sport Club Internacional",
  "internazionale-it": "Football Club Internazionale Milano",
  "libertad-py": "Club Libertad",
  "milan-it": "Associazione Calcio Milan",
  "nacional-py": "Club Nacional (Paraguay)",
  "santos-br": "Santos Futebol Clube",
  "deportivo-quito-ec": "Sociedad Deportivo Quito",
  "sportivo-alagoano-br": "Centro Sportivo Alagoano",
  "fortaleza-br": "Fortaleza Esporte Clube",
  "sanfrecce-jp": "en:Sanfrecce Hiroshima",
  "kashima-jp": "en:Kashima Antlers",
  "kashiwa-reysol-jp": "en:Kashiwa Reysol",
  "psv-nl": "en:PSV Eindhoven",
  "mazembe-cd": "en:TP Mazembe",
  "manchester-city-en": "Manchester City Football Club",
  "manchester-united-en": "en:Manchester United F.C.",
  "liverpool-en": "Liverpool Football Club",
  "america-mineiro-br": "en:América Futebol Clube (MG)",
  "america-co": "América de Cali",
  "atletico-madrid-es": "en:Atlético Madrid",
  "cerro-uy": "Club Atlético Cerro",
  "gremio-br": "Grêmio Foot-Ball Porto Alegrense",
  "guarani-br": "Guarani Futebol Clube",
  "montevideo-city-torque-uy": "en:Montevideo City Torque",
  "municipal-gt": "en:C.S.D. Municipal",
  "paulista-fc-br": "Paulista Futebol Clube",
  "racing-uy": "Racing Club de Montevideo",
  "real-potosi-bo": "en:Club Real Potosí",
  "urawa-jp": "Urawa Red Diamonds",
  "vitoria-br": "Esporte Clube Vitória",
  cai: null,
  "real-madrid-es": "Real Madrid Club de Fútbol",
  "chelsea-en": "Chelsea Football Club",
  "corinthians-br": "Sport Club Corinthians Paulista",
  "fenix-uy": "Centro Atlético Fénix",
  "melgar-pe": "Foot Ball Club Melgar",
  "sport-boys-warnes-bo": "Club Sport Boys Warnes",
  "aragua-ve": "en:Aragua F.C.",
  "deportivo-capiata-py": "en:Deportivo Capiatá",
  "minerven-ve": "en:Minerven S.C.",
  "zulia-ve": "en:Zulia F.C.",
  "rocha-fc-uy": "en:Rocha F.C.",
  "renato-cesarini": "en:Club Renato Cesarini",
  "etoile-du-sahel-tn": "en:Étoile Sportive du Sahel",
  "parana-clube-br": "en:Paraná Clube",
  "deportivo-italiano": null,
};
