// Copa Argentina (2011/12–): la copa nacional con clubes de todas las categorías. RSSSF la publica dentro de la
// página de cada temporada (arg20XX.html). La fase de cada partido sale de los títulos de la página (contextStages).
import type { TournamentConfig } from "./config";
import { A_COPA_2020 } from "./config";

const AFA = "Asociación del Fútbol Argentino";

// Nombres de RSSSF en la Copa Argentina. Van como alias del torneo: "CA Estudiantes" acá es Estudiantes de Buenos
// Aires (el de La Plata figura "Club Estudiantes de La Plata") y "CA Racing" es Racing de Córdoba.
const { Estudiantes: _lp, ...BASE } = A_COPA_2020;
export const A_CA: Record<string, string> = {
  ...BASE,
  "CA Estudiantes": "estudiantes-ba",
  "Club Atlético Estudiantes": "estudiantes-ba",
  "CA Racing": "racing-cordoba",
  "Club Atlético Racing Soc. Civil": "racing-cordoba",
  "CA Huracán (Parque Patricios)": "huracan",
  "CA Talleres (R. de Escalada)": "talleres-re",
  "CA Talleres (Remedios Escalada)": "talleres-re",
  "CA Central Córdoba (ROS)": "central-cordoba-rosario",
  "CA Central Córdoba (Santiago dE)": "central-cordoba-sde",
  "CA San Martín (SM de Tucumán)": "san-martin-tucuman",
  "CA San Martín (San Juan)": "san-martin-sj",
  "Club Atlético San Martín Sociedad Civil": "san-martin-tucuman",
  "CA Patronato dlJC": "patronato-parana",
  "CA Gimnasia y Esgrima (SS Jujuy)": "gimnasia-jujuy",
  "CA Gimnasia y Esgrima (SSJ)": "gimnasia-jujuy",
  "CSD Gimnasia y Esgrima Chivilcoy": "gimnasia-chivilcoy",
  "Gimnasia y Esgrima FBC": "gimnasia-cdu",
  "Club de Gimnasia y Tiro AC": "gimnasia-tiro-salta",
  "Cd Gimnasia y Tiro": "gimnasia-tiro-salta",
  "Atlético Club San Martín": "san-martin-mendoza",
  "C. y Biblioteca Ramón Santamarina": "ramon-santamarina",
  "CB Ramón Santamarina": "ramon-santamarina",
  "Instituto Atl. Central Córdoba": "instituto",
  "Instituto A. Central Córdoba": "instituto",
  "Centro Juventud Antoniana": "juventud-antoniana",
  "Club Juventud Unida Universitario": "juventud-unida-sl",
  "Club Sportivo Estudiantes": "sportivo-estudiantes-sl",
  "CS Estudiantes": "sportivo-estudiantes-sl",
  "Club Sportivo General San Martín": "general-san-martin-formosa",
  "CS General San Martín": "general-san-martin-formosa",
  "Club Sportivo Alfredo Guzmán": "sportivo-guzman",
  "Club Villa Mitre": "villa-mitre",
  "CA Güemes": "guemes-sde",
  "Club Atlético Güemes": "guemes-sde",
  "CA Belgrano (Paraná)": "belgrano-parana",
  "CA Mitre": "mitre-sde",
  "CA Mitre (Santiago del Estero)": "mitre-sde",
  "CA Mitre (Salta)": "mitre-salta",
  "CA Sarmiento (Resistencia)": "sarmiento-resistencia",
  "CA Sarmiento (La Banda)": "sarmiento-la-banda",
  "CS Belgrano (San Francisco)": "sportivo-belgrano-sf",
  "CS Belgrano": "sportivo-belgrano-sf",
  "CS Desamparados": "desamparados",
  "CS Patria": "sportivo-patria",
  "CSB Atenas": "sportivo-atenas",
  "S. Ferroviario": "ferroviarios-corrientes",
  "CA Defensores Unidos": "defensores-unidos-zarate",
  "CD Armenio": "deportivo-armenio",
  "CD Morón": "deportivo-moron",
  "C. Sportivo Barracas (Barracas)": "sportivo-barracas",
  "Club Defensores de Cambaceres": "defensores-cambaceres",
  "ACSyD Sol de Mayo": "sol-de-mayo-viedma",
  "ACSD Sol de Mayo": "sol-de-mayo-viedma",
  "ACyD Altos Hornos Zapla": "altos-hornos-zapla",
  "ACD Altos Hornos Zapla": "altos-hornos-zapla",
  "AMSD Atlético de Rafaela": "atletico-rafaela",
  // Clubes nuevos (lib/data/clubs.ts, sección Copa Argentina).
  "CA Acassuso": "acassuso",
  "CSD Achirense": "achirense",
  "CSyD Achirense": "achirense",
  "Club Agropecuario Argentino": "agropecuario",
  "CA Argentino de Merlo": "argentino-merlo",
  "CA Paraná": "atletico-parana",
  "Club Atlético Paraná": "atletico-parana",
  "C. Belgrano de San Nicolás": "belgrano-san-nicolas",
  "CS Ben Hur": "ben-hur",
  "AD Berazategui": "berazategui",
  "C. Sportivo Bernardino Rivadavia": "bernardino-rivadavia",
  "CA Boca Unidos": "boca-unidos",
  "CA Brown": "brown-adrogue",
  "Club Atlético Brown": "brown-adrogue",
  "CASyD Camioneros": "camioneros",
  "CASD Camioneros": "camioneros",
  "Cañuelas FC": "canuelas",
  "CSyD Central Ballester": "central-ballester",
  "Club Ciudad de Bolívar": "ciudad-bolivar",
  "CA Claypole": "claypole",
  "C. Comercio Central Unidos": "comercio-central-unidos",
  "Club Comunicaciones": "comunicaciones",
  "CSyDD de Pronunciamiento": "defensores-pronunciamiento",
  "CSy Dep. Def. de Pronunciamiento": "defensores-pronunciamiento",
  "Defensores de Pronunciamiento": "defensores-pronunciamiento",
  "CAyS Defensores de Belgrano": "defensores-villa-ramallo",
  "CAy Social Defensores de Belgrano": "defensores-villa-ramallo",
  "CAS Defensores de Belgrano": "defensores-villa-ramallo",
  "CSyD Madryn": "deportivo-madryn",
  "CSD Madryn": "deportivo-madryn",
  "CS Deportivo Madryn": "deportivo-madryn",
  "Club Social y Deportivo Madryn": "deportivo-madryn",
  "CD Maipú": "deportivo-maipu",
  "CD Rincón": "deportivo-rincon",
  "CD Rincón (Rincón de los Sauces)": "deportivo-rincon",
  "CA Douglas Haig": "douglas-haig",
  "Club Atlético Douglas Haig": "douglas-haig",
  "CSyD Flandria": "flandria",
  "CA General Lamadrid": "general-lamadrid",
  "CSyD General Roca": "deportivo-roca",
  "CSA Guillermo Brown": "guillermo-brown",
  "CSyA Guillermo Brown": "guillermo-brown",
  "CA Independiente (Chivilcoy)": "independiente-chivilcoy",
  "CA Independiente (CVY)": "independiente-chivilcoy",
  "CA Independiente del Neuquén": "independiente-neuquen",
  "CA Ituzaingó": "ituzaingo",
  "ASyD Justo J. de Urquiza": "justo-jose-urquiza",
  "CD Juventud Unida": "juventud-unida-gualeguaychu",
  "Club Deportivo Juventud Unida": "juventud-unida-gualeguaychu",
  "Club Social y Deportivo La Emilia": "la-emilia",
  "CSCyD Laferrere": "laferrere",
  "CS y Cultural Deportivo Laferrere": "laferrere",
  "CA Laguna Blanca": "laguna-blanca",
  "CDM Leandro N. Alem": "leandro-n-alem",
  "Club Luján": "lujan",
  "CA Ferrocarril Midland": "midland",
  "SC Pacífico de General Alvear": "pacifico-general-alvear",
  "CA Puerto Nuevo": "puerto-nuevo",
  "Real Pilar FC": "real-pilar",
  "Club Rivadavia": "rivadavia-lincoln",
  "Sacachispas FC": "sacachispas",
  "CSyD San Jorge Juniors": "san-jorge-tucuman",
  "CA San Lorenzo de Alem": "san-lorenzo-alem",
  "Club Atlético San Lorenzo de Alem": "san-lorenzo-alem",
  "CA San Miguel": "san-miguel",
  "CA Sansinena SyD": "sansinena",
  "CA Sansinena SD": "sansinena",
  "CA Sansinena Social y Deportivo": "sansinena",
  "CSyS Sol de América": "sol-de-america-formosa",
  "C. Sportivo Barracas (Colón)": "sportivo-barracas-colon",
  "Sportivo AC": "sportivo-las-parejas",
  "Sportivo Atlético Club": "sportivo-las-parejas",
  "C. Sportivo Peñarol": "sportivo-penarol",
  "CA Talleres (Perico)": "talleres-perico",
  "CSD Textil Mandiyú": "textil-mandiyu",
  "Tiro Federal y Deportivo Morteros": "tiro-federal-morteros",
  "Club Tristán Suárez": "tristan-suarez",
  "Club Deportivo UAI Urquiza": "uai-urquiza",
  "Club Unión Aconquija": "union-aconquija",
  "C. Unión Aconquija": "union-aconquija",
  "Club Atlético Unión Santiago": "union-santiago",
  "CA Unión (Sunchales)": "union-sunchales",
  "Club Atlético Unión (Sunchales)": "union-sunchales",
  "CA Victoriano Arenas": "victoriano-arenas",
  "Club Villa Dálmine": "villa-dalmine",
  "CA Villa San Carlos": "villa-san-carlos",
  "CSyD Yupanqui": "yupanqui",
  "AA Estudiantes": "estudiantes-rio-cuarto",
  "CA Gimnasia y Esgrima": "gimnasia-mendoza",
  // Nombres completos de las tablas de RSSSF (2018/19–).
  "Asociación Atlética Estudiantes": "estudiantes-rio-cuarto",
  "Club Atlético Gimnasia y Esgrima": "gimnasia-mendoza",
  "Club Atlético Mitre": "mitre-sde",
  "Club Sportivo Belgrano": "sportivo-belgrano-sf",
  "Club Social y Deportivo General Roca": "deportivo-roca",
  "Deportivo Roca": "deportivo-roca",
  "Club Atlético Boca Unidos": "boca-unidos",
  "Real Pilar Fútbol Club Asociación Civil": "real-pilar",
  "Club de Gimnasia y Tiro Asociación Civil": "gimnasia-tiro-salta",
  "Asociación Cultural y Deportiva Altos Hornos Zapla": "altos-hornos-zapla",
  "Asociación Club Social y Deportivo Sol de Mayo": "sol-de-mayo-viedma",
  "Club Deportivo Maipú": "deportivo-maipu",
  "Club Atlético y Social Defensores de Belgrano": "defensores-villa-ramallo",
  "Club Social y Deportivo San Jorge Juniors Asociación Civil": "san-jorge-tucuman",
  "Gimnasia y Esgrima Foot Ball Club": "gimnasia-cdu",
  "Asociación Civil Club Atlético Social y Deportivo Camioneros": "camioneros",
  "Club A. Sansinena Social y Deportivo": "sansinena",
  "Club Atlético Independiente del Neuquén": "independiente-neuquen",
  "Asociación Civil Deportivo Armenio": "deportivo-armenio",
  "Club Atlético Ferrocarril Midland": "midland",
  "Club Atlético Acassuso": "acassuso",
  "Club Atlético Argentino de Merlo Asociación Civil": "argentino-merlo",
  "Club Cipolletti Asociación Civil sin Fines de Lucro": "cipolletti",
  "Club Social y Cultural Deportivo Laferrere": "laferrere",
  "Club Social y Deportivo Defensores de Pronunciamiento": "defensores-pronunciamiento",
  "Club Agropecuario Argentino Asociación Civil": "agropecuario",
  "Club Atlético Huracán Las Heras": "huracan-las-heras",
  // Nombres de Wikipedia.
  "Juventud Unida (G)": "juventud-unida-gualeguaychu",
  "Douglas Haig": "douglas-haig",
  "Real Pilar": "real-pilar",
  "Villa Dálmine": "villa-dalmine",
  "Deportivo Laferrere": "laferrere",
  "Mitre (SdE)": "mitre-sde",
  "Argentino de Merlo": "argentino-merlo",
  "Ferrocarril Midland": "midland",
  "Acassuso": "acassuso",
  "Unión (S)": "union-sunchales",
  "Sarmiento (R)": "sarmiento-resistencia",
  "Sportivo Estudiantes (SL)": "sportivo-estudiantes-sl",
  "Villa Mitre": "villa-mitre",
  "Sol de Mayo": "sol-de-mayo-viedma",
  "Estudiantes (RC)": "estudiantes-rio-cuarto",
  "Estudiantes (BA)": "estudiantes-ba",
  "Gimnasia y Esgrima (M)": "gimnasia-mendoza",
  "Gimnasia y Tiro (S)": "gimnasia-tiro-salta",
  "Independiente (N)": "independiente-neuquen",
  "Deportivo Madryn": "deportivo-madryn",
  "Atlético Paraná": "atletico-parana",
  "Sportivo Las Parejas": "sportivo-las-parejas",
  "Sportivo Belgrano": "sportivo-belgrano-sf",
  "San Martín (F)": "general-san-martin-formosa",
  "Sansinena": "sansinena",
  "Deportivo Maipú": "deportivo-maipu",
  "San Jorge (T)": "san-jorge-tucuman",
  "Deportivo Camioneros": "camioneros",
  "Gimnasia y Esgrima (CdU)": "gimnasia-cdu",
  "Defensores de Belgrano (VR)": "defensores-villa-ramallo",
  "Desamparados": "desamparados",
  "Boca Unidos": "boca-unidos",
  "Agropecuario": "agropecuario",
  "San Lorenzo de Alem": "san-lorenzo-alem",
  "Juventud Unida Universitario": "juventud-unida-sl",
  // "CA Ferro Carril Oeste" en la Copa Argentina es el de General Pico (el de Caballito es "Club Ferro Carril Oeste").
  "CA Ferro Carril Oeste": "ferro-general-pico",
  "Club Atlético Ferro Carril Oeste": "ferro-general-pico",
  "Ferro Carril Oeste (GP)": "ferro-general-pico",
  // 2019/20–2026.
  "CS Peñarol": "sportivo-penarol",
  "Club Sportivo Peñarol": "sportivo-penarol",
  "Sportivo Peñarol (C)": "sportivo-penarol",
  "CA Central Norte": "central-norte-salta",
  "Central Norte (S)": "central-norte-salta",
  "Club Atlético Villa San Carlos y Biblioteca Popular Mariano Moreno": "villa-san-carlos",
  "Club Atlético Claypole": "claypole",
  "Club Atlético San Martín S. Civil": "san-martin-tucuman",
  "CA San Martín (SMC)": "san-martin-tucuman",
  "CA San Martín (UAQ)": "san-martin-sj",
  "CA Talleres (COR)": "talleres",
  "Cañuelas Fútbol Club": "canuelas",
  "Asoc. Social y Deportiva Justo J. de Urquiza": "justo-jose-urquiza",
  "J.J. de Urquiza": "justo-jose-urquiza",
  "J. J. de Urquiza": "justo-jose-urquiza",
  "Güemes (SdE)": "guemes-sde",
  "Sportivo Belgrano (SF)": "sportivo-belgrano-sf",
  "Cañuelas": "canuelas",
  "Claypole": "claypole",
  "Comunicaciones": "comunicaciones",
  "Villa San Carlos": "villa-san-carlos",
  "Cipoletti": "cipolletti",
  "Defensores de Cambaceres": "defensores-cambaceres",
  "Club Social Cultural Deportivo Centro de Fomento y Biblioteca Popular Gral J. de San Martín Defensores de Cambaceres": "defensores-cambaceres",
  "Puerto Nuevo": "puerto-nuevo",
  "Club Atlético Puerto Nuevo": "puerto-nuevo",
  "Sacachispas": "sacachispas",
  "Sacachispas Fútbol Club": "sacachispas",
  "Brown de Adrogué": "brown-adrogue",
  "Flandria": "flandria",
  "Club Social y Dep. Flandria": "flandria",
  "Ituzaingó": "ituzaingo",
  "Club Atlético Ituzaingó Asociación Civil": "ituzaingo",
  "Tristán Suárez": "tristan-suarez",
  "CSyD Liniers": "liniers-san-justo",
  "Club Social y Deportivo Liniers": "liniers-san-justo",
  "Liniers (SJ)": "liniers-san-justo",
  "Independiente (C)": "independiente-chivilcoy",
  "Centro Español": "centro-espanol",
  "CSyR Español": "centro-espanol",
  "Centro Social y Recreativo Español": "centro-espanol",
  "Club Social, Deportivo y Cultural Español de la República Argentina Asociación Civil": "deportivo-espanol",
  "Ciudad de Bolívar": "ciudad-bolivar",
  "Defensores Unidos": "defensores-unidos-zarate",
  "Club Atlético Defensores Unidos": "defensores-unidos-zarate",
  "Yupanqui": "yupanqui",
  "Club Social y Deportivo Yupanqui": "yupanqui",
  "Argentino (MM)": "argentino-monte-maiz",
  "CD Argentino": "argentino-monte-maiz",
  "Club Deportivo Argentino": "argentino-monte-maiz",
  "San Martín (B)": "san-martin-burzaco",
  "CSyD San Martín": "san-martin-burzaco",
  "Club Social y Deportivo San Martín": "san-martin-burzaco",
  "San Miguel": "san-miguel",
  "Club Atlético San Miguel": "san-miguel",
  "General Lamadrid": "general-lamadrid",
  "Club Atlétiico General Lamadrid": "general-lamadrid",
  "Sarmiento (LB)": "sarmiento-la-banda",
  "Berazategui": "berazategui",
  "Asociación Deportiva Berazategui": "berazategui",
  "Club y Biblioteca Ramón Santamarina": "ramon-santamarina",
  "Gimnasia y Esgrima (C)": "gimnasia-chivilcoy",
  "Club Social y Deportivo Gimnasia y Esgrima de Chivilcoy": "gimnasia-chivilcoy",
  "Deportivo Rincón": "deportivo-rincon",
  "Asociación Civil Club Deportivo Rincón": "deportivo-rincon",
  "Atenas (RC)": "sportivo-atenas",
  "Liniers": "liniers-san-justo",
  // 2015/16–2017/18.
  "CA Colón Junior": "colon-juniors-sj",
  "Colón Juniors": "colon-juniors-sj",
  "CA Argentinos": "argentinos-25-mayo",
  "Argentinos (VdM)": "argentinos-25-mayo",
  "CA Huracán (Comodoro Rivadavia)": "huracan-comodoro",
  "Jorge Newbery (CR)": "jorge-newbery-cr",
  "Huracán (SR)": "huracan-san-rafael",
  "Racing AC": "racing-olavarria",
  "Racing Atletic Club": "racing-olavarria",
  "Racing (O)": "racing-olavarria",
  "FC Ferro Carril Sud": "ferro-sud-olavarria",
  "Ferro Carril Sud (O)": "ferro-sud-olavarria",
  "CAAByM Sarmiento": "sarmiento-leones",
  "Sarmiento (L)": "sarmiento-leones",
  "CA Pellegrini": "pellegrini-salta",
  "Club Atlético Pellegrini": "pellegrini-salta",
  "Atlético Pellegrini": "pellegrini-salta",
  "CA Unión Rawson": "union-villa-krause",
  "Unión (VK)": "union-villa-krause",
  "C. Bella Vista": "bella-vista-bahia-blanca",
  "Bella Vista (BB)": "bella-vista-bahia-blanca",
  "CA San Jorge MyS": "san-jorge-santa-fe",
  "San Jorge (SF)": "san-jorge-santa-fe",
  "Unión Aconquija": "union-aconquija",
  "La Emilia": "la-emilia",
  "Unión Santiago": "union-santiago",
  "Sportivo Rivadavia (VT)": "bernardino-rivadavia",
  "Güemes": "guemes-sde",
  "Comercio Central Unidos": "comercio-central-unidos",
  "Tiro Federal (M)": "tiro-federal-morteros",
  "Pacífico": "pacifico-general-alvear",
  "Atlético Camioneros": "camioneros",
  "Sportivo Barracas (C)": "sportivo-barracas-colon",
  "Belgrano (SN)": "belgrano-san-nicolas",
  "Rivadavia (L)": "rivadavia-lincoln",
  "Deportivo Achirense": "achirense",
  "Sol de América (F)": "sol-de-america-formosa",
  "Sol de Mayo (V)": "sol-de-mayo-viedma",
  "Luján": "lujan",
  "UAI Urquiza": "uai-urquiza",
  "Guillermo Brown": "guillermo-brown",
  "Central Ballester": "central-ballester",
  "Victoriano Arenas": "victoriano-arenas",
  "Midland": "midland",
  "Leandro N. Alem": "leandro-n-alem",
  "CA Tiro Federal Argentino": "tiro-federal-rosario",
  "Tiro Federal (R)": "tiro-federal-rosario",
  "Belgrano (P)": "belgrano-parana",
  "Ben Hur": "ben-hur",
  "Mitre (S)": "mitre-salta",
  "Almirante Brown (L)": "almirante-brown-lules",
  "Talleres (P)": "talleres-perico",
  "Atlético Laguna Blanca": "laguna-blanca",
  "Ferroviario (C)": "ferroviarios-corrientes",
  "Textil Mandiyú": "textil-mandiyu",
  "Sportivo Rivadavia": "bernardino-rivadavia",
  "Club Atlético Germinal": "germinal-rawson",
  "Germinal": "germinal-rawson",
  "CA Germinal": "germinal-rawson",
  "Independiente Rivadavia (Mza)": "independiente-rivadavia",
  "Godoy Cruz AT (Mendoza)": "godoy-cruz",
  "Alvear FC (Intendente Alvear)": "alvear-intendente-alvear",
  "Alvear FBC": "alvear-intendente-alvear",
  "Atlético Concepción (Banda del Río Salí)": "atletico-concepcion",
  "Ben Hur (Rafaela)": "ben-hur",
  "Chaco For Ever (Resistencia)": "chaco-for-ever",
  "Guillermo Brown (PM)": "guillermo-brown",
  "Independiente (Tandil)": "independiente-tandil",
  "Independiente (T)": "independiente-tandil",
  "Jorge Newbery (Venado Tuerto)": "jorge-newbery-vt",
  "Jorge Newbery (VT)": "jorge-newbery-vt",
  "Liniers (Bahía Blanca)": "liniers-bahia-blanca",
  "Liniers (BB)": "liniers-bahia-blanca",
  "Sarmiento (Junín]": "sarmiento-junin",
  "Sarmiento (Junín)": "sarmiento-junin",
  "Sarmiento (Leones)": "sarmiento-leones",
  "Sarmiento (Resistencia)": "sarmiento-resistencia",
  "Talleres (Perico)": "talleres-perico",
  "Tiro Federal (Morteros)": "tiro-federal-morteros",
  "9 de Julio (Morteros)": "nueve-de-julio-morteros",
  "9 de Julio (M)": "nueve-de-julio-morteros",
  "9 de Julio (R)": "nueve-de-julio-rafaela",
  "Argentino (R)": "argentino-rosario",
  "Riestra": "deportivo-riestra",
  "Brown (A)": "brown-adrogue",
  "Cambaceres": "defensores-cambaceres",
  "J.J. Urquiza": "justo-jose-urquiza",
  "Laferrere": "laferrere",
  "Boca Río Gallegos": "boca-rio-gallegos",
  "Huracán de Comodoro": "huracan-comodoro",
  "Santamarina": "ramon-santamarina",
  "Def. de Belgrano (VR)": "defensores-villa-ramallo",
  "Atlético San Jorge": "san-jorge-santa-fe",
  "Defensores (P)": "defensores-pronunciamiento",
  "General Paz Juniors": "general-paz-juniors",
  "Juventud Alianza (SJ)": "atletico-juventud-sj",
  "Concepción FC": "concepcion-fc",
  "Sarmiento (SdE)": "sarmiento-la-banda",
  // 2011/12 (nombres cortos de RSSSF y de Wikipedia).
  "Cuervos del fin del mundo (TF)": "cuervos-fin-del-mundo",
  "Cuervos del fin del mundo (Tierra del Fuego)": "cuervos-fin-del-mundo",
  "Los Cuervos del Fin del Mundo": "cuervos-fin-del-mundo",
  "Real Madrid (Río Grande)": "real-madrid-rio-grande",
  "Real Madrid (Río Gallegos)": "real-madrid-rio-grande",
  "Real Madrid (RG)": "real-madrid-rio-grande",
  "CA Riojano (La Rioja)": "riojano",
  "Atlético Riojano": "riojano",
  "Atlético Chilecito": "chilecito",
  "Argentino (Rosario)": "argentino-rosario",
  "Lugano": "lugano",
  "San Martín (Burzaco)": "san-martin-burzaco",
  "Deportivo Muñiz": "deportivo-muniz",
  "Muñiz": "deportivo-muniz",
  "Juventud Unida": "juventud-unida-san-miguel",
  "Juventud Unida (SM)": "juventud-unida-san-miguel",
  "Fenix": "fenix",
  "Fénix": "fenix",
  "Deportivo Paraguayo": "deportivo-paraguayo",
  "J.J.Urquiza": "justo-jose-urquiza",
  "Brown (Adrogué)": "brown-adrogue",
  "Sportivo Italiano": "deportivo-italiano",
  "Leandro N.Alem": "leandro-n-alem",
  "Sp.Gral San Martín (Formosa)": "general-san-martin-formosa",
  "Atlético Trinidad (San Juan)": "trinidad-sj",
  "Trinidad (SJ)": "trinidad-sj",
  "Trinidad": "trinidad-sj",
  "Del Bono (San Juan)": "del-bono",
  "Sportivo Del Bono": "del-bono",
  "Huracán Las Heras (Mendoza)": "huracan-las-heras",
  "Deportivo Guaymallén (Mendoza)": "deportivo-guaymallen",
  "Deportivo Guaymallén (Mza)": "deportivo-guaymallen",
  "Guaymallén": "deportivo-guaymallen",
  "Boca Juniors (Río Gallegos)": "boca-rio-gallegos",
  "Deportivo Madryn (Pto Madryn)": "deportivo-madryn",
  "Cruz del Sur (Ing.Jacobacci)": "cruz-del-sur-jacobacci",
  "Cruz del Sur": "cruz-del-sur-jacobacci",
  "Maronese (Neuquén)": "maronese",
  "Maronese": "maronese",
  "Villa Mitre (Bahía Blanca)": "villa-mitre",
  "Ramón Santamarina (Tandil)": "ramon-santamarina",
  "Bella Vista (Bahía Blanca)": "bella-vista-bahia-blanca",
  "El Linqueño (Lincoln)": "el-linqueno",
  "El Linqueño": "el-linqueno",
  "Rivadavia (Lincoln)": "rivadavia-lincoln",
  "Douglas Haig (Pergamino)": "douglas-haig",
  "Ferro Carril Sud (Tandil)": "ferro-sud-olavarria",
  "Ferro (O)": "ferro-sud-olavarria",
  "Racing (Olavarría)": "racing-olavarria",
  "Grupo Universitario (Tandil)": "grupo-universitario-tandil",
  "Grupo Universitario": "grupo-universitario-tandil",
  "Once Tigres (9 de Julio)": "once-tigres",
  "Once Tigres": "once-tigres",
  "Juventud Unida (Gualeguaychú)": "juventud-unida-gualeguaychu",
  "Atlético San Jorge (Santa Fe)": "san-jorge-santa-fe",
  "Colegiales (Concordia)": "colegiales-concordia",
  "Colegiales (C)": "colegiales-concordia",
  "Colegiales(C)": "colegiales-concordia",
  "Club Sportivo Las Heras (Concordia)": "las-heras-concordia",
  "Sportivo Las Heras": "las-heras-concordia",
  "Sportivo Patria (Formosa)": "sportivo-patria",
  "Textil Mandiyú (Corrientes)": "textil-mandiyu",
  "Guaraní A.Franco (Posadas)": "guarani-antonio-franco",
  "Jorge Gibson Brown (Posadas)": "gibson-brown",
  "Gibson Brown": "gibson-brown",
  "Jorge Gibson Brown": "gibson-brown",
  "General Paz Juniors (Córdoba)": "general-paz-juniors",
  "Complejo Deportivo Teniente Origone (Justiniano Posse)": "teniente-origone",
  "Complejo Deportivo": "teniente-origone",
  "Atenas (Río IV)": "sportivo-atenas",
  "Juventud Unida (San Luis)": "juventud-unida-sl",
  "Juventud Unida (SL)": "juventud-unida-sl",
  "Alumni (Villa María)": "alumni-villa-maria",
  "Alumni (VM)": "alumni-villa-maria",
  "Atlético Policial (Catamarca)": "policial-catamarca",
  "Atlético Policial": "policial-catamarca",
  "Villa Cubas (Catamarca)": "villa-cubas",
  "Villa Cubas": "villa-cubas",
  "Concepción FC (Tucumán)": "concepcion-fc",
  "Deportivo San Jorge (Tucumán)": "san-jorge-tucuman",
  "Altos Hornos Zapla (Palpalá)": "altos-hornos-zapla",
  "Sarmiento (Sgo del Estero)": "sarmiento-la-banda",
  "Unión (Mar del Plata)": "union-mar-del-plata",
  "Unión (MdP)": "union-mar-del-plata",
  "Libertad (Sunchales)": "libertad-sunchales",
  "Libertad (S)": "libertad-sunchales",
  "Defensores (Pronunciamiento)": "defensores-pronunciamiento",
  "Atl.Juventud Alianza (SJ)": "atletico-juventud-sj",
  "Deportivo Maipú (Mendoza)": "deportivo-maipu",
  "Atlético San Martín (Mendoza)": "san-martin-mendoza",
  "Central Córdoba (Sgo Estero)": "central-cordoba-sde",
  "Mitre (Santiago del Estero)": "mitre-sde",
  "Sportivo Belgrano (SFco)": "sportivo-belgrano-sf",
  "Racing (Trelew)": "racing-trelew",
  "Racing (T)": "racing-trelew",
  "CAI (Comodoro Rivadavia)": "cai",
  "CAI": "cai",
  "Argentino (Merlo)": "argentino-merlo",
  "Argentino (M)": "argentino-merlo",
  "Unión (Villa Krause)": "union-villa-krause",
  "Sportivo Desamparados (SJ)": "desamparados",
  "Boca Unidos (Corrientes)": "boca-unidos",
  "Deportivo Merlo": "deportivo-merlo",
  "Aldosivi (Mar del Palta)": "aldosivi",
  "Jorge Newbery (Comodoro Rivadavia)": "jorge-newbery-cr",
  "Huracán (Comodoro Rivadavia)": "huracan-comodoro",
  "Defensores de Belgrano (Villa Ramallo)": "defensores-villa-ramallo",
  "Unión (Sunchales)": "union-sunchales",
  "La Emilia (San Nicolás)": "la-emilia",
  "Talleres (Córdoba)": "talleres",
  "Racing (Córdoba)": "racing-cordoba",
  "Racing (C)": "racing-cordoba",
  "Tiro Federal (Rosario)": "tiro-federal-rosario",
  "9 de Julio (Rafaela)": "nueve-de-julio-rafaela",
  "Huracán (Tres Arroyos)": "huracan-tres-arroyos",
  "Club Sportivo y Biblioteca Atenas": "sportivo-atenas",
};

const FORMATO_2019 =
  "Copa de todas las categorías del fútbol argentino. Fases preliminares regionales entre clubes del Torneo Federal A (ida y vuelta) y, desde los treintaidosavos, eliminación directa a un partido en cancha neutral, con penales si hay empate.";

const FORMATO_2022 =
  "Copa de todas las categorías del fútbol argentino: los equipos de Primera y los clasificados del Ascenso y del Torneo Federal A juegan desde los treintaidosavos, eliminación directa a un partido en cancha neutral, con penales si hay empate.";

type Rest = Pick<TournamentConfig, "championIds" | "runnerUpIds" | "summary" | "notes" | "headings"> & Partial<TournamentConfig>;
const copaArgentina = (edition: string, year: number, file: string, rest: Rest): TournamentConfig => ({
  slug: `copa-argentina-${edition}`,
  kind: "cup",
  year,
  yearLabel: edition.replace("-", "/"),
  file,
  wiki: `Copa Argentina ${edition.replace("-", "-")}`,
  competition: "Copa Argentina",
  title: `Copa Argentina ${edition.replace("-", "/")}`,
  tournament: `Copa Argentina ${edition.replace("-", "/")}`,
  organizer: AFA,
  section: rest.headings![0],
  contextStages: true,
  pointsPerWin: 3,
  aliases: A_CA,
  ...rest,
});

export const CUP_TOURNAMENTS_ARGENTINA: TournamentConfig[] = [
  copaArgentina("2011-12", 2011, "arg2012.html", {
    championIds: ["boca"],
    runnerUpIds: ["racing"],
    headings: [/^Copa Argentina 2011\/12$/],
    // Wikipedia lo nombra "Alumni" a secas: es el de Villa María, no el Alumni de 1900.
    aliases: { ...A_CA, Alumni: "alumni-villa-maria" },
    summary: "Boca ganó la primera Copa Argentina desde 1970: le ganó 2-1 la final a Racing en San Juan. Fue la edición de la vuelta de la copa, con 186 partidos y clubes de todas las categorías.",
    notes: [
      {
        kind: "formato",
        text: "Primera edición de la Copa Argentina moderna. Una ronda preliminar en La Rioja y Tierra del Fuego, tres fases regionales (zona metropolitana, con clubes de la B, la C y la D, y zona interior, con clubes del Argentino A y B) y, desde los treintaidosavos, eliminación directa a un partido en cancha neutral con los equipos de Primera y la B Nacional.",
      },
      { kind: "fuentes", text: "RSSSF da el Ferro Carril Sud de la primera fase como de Tandil; Wikipedia lo identifica como el de Olavarría, que es el que se usa acá." },
    ],
  }),
  copaArgentina("2015-16", 2016, "arg2016.html", {
    championIds: ["river"],
    runnerUpIds: ["central"],
    headings: [/^Copa Argentina 2016$/],
    aliases: {
      ...A_CA,
      "CA Gimnasia y Esgrima": "gimnasia-jujuy",
      "Club Atlético Gimnasia y Esgrima": "gimnasia-jujuy",
      // "Club Atlético Unión" a secas es el de Sunchales; el de Santa Fe va con "(Santa Fe)".
      "Club Atlético Unión": "union-sunchales",
      "Club Atlético Unión (Santa Fe)": "union-santa-fe",
    },
    tableAliases: { "7": "union-santa-fe", "54": "union-sunchales" },
    weekdayYears: true,
    // Las rondas 1 y 2 de RSSSF son la ida y la vuelta de la fase preliminar (clubes del Federal A); la 3, los treintaidosavos.
    stageRename: {
      "Ronda 1 · Grupo A": "Fase preliminar · Grupo A (ida)",
      "Ronda 1 · Grupo B": "Fase preliminar · Grupo B (ida)",
      "Ronda 2 · Grupo A": "Fase preliminar · Grupo A (vuelta)",
      "Ronda 2 · Grupo B": "Fase preliminar · Grupo B (vuelta)",
      "Ronda 3": "Treintaidosavos de final",
      "Ronda 4": "Dieciseisavos de final",
      "Ronda 5": "Octavos de final",
      "Ronda 6": "Cuartos de final",
    },
    overrides: {
      "2016-12-15 river central": { note: "Goles: Alario 11' (de penal), 40' (de penal) y 72', Alonso 75' / Musto 26', Rubén 30' y 63'." },
    },
    summary: "River ganó la Copa Argentina 2015/16: le ganó 4-3 a Rosario Central una final muy discutida en Córdoba, con tres goles de Alario.",
    notes: [{ kind: "formato", text: FORMATO_2022 }],
  }),
  copaArgentina("2016-17", 2017, "arg2017.html", {
    championIds: ["river"],
    runnerUpIds: ["atletico-tucuman"],
    headings: [/^Copa Argentina 2016\/2017$/],
    aliases: { ...A_CA, "CA San Martín": "san-martin-sj", "CA Jorge Newbery": "jorge-newbery-cr", "CA Almirante Brown": "almirante-brown-lules" },
    weekdayYears: true,
    overrides: {
      "2017-12-09 river atletico-tucuman": { note: "Goles: Scocco 9', Fernández 48' / Rodríguez 11'." },
    },
    summary: "River ganó la Copa Argentina 2016/17, la segunda seguida: le ganó 2-1 la final a Atlético Tucumán en Mendoza.",
    notes: [{ kind: "formato", text: FORMATO_2022 }],
  }),
  copaArgentina("2017-18", 2018, "arg2018.html", {
    championIds: ["central"],
    runnerUpIds: ["gimnasia"],
    headings: [/^Copa Argentina 2017\/2018$/],
    aliases: { ...A_CA, "Club Huracán": "huracan-san-rafael" },
    weekdayYears: true,
    wikiErrata: {
      "RSSSF velez 1-1 central-cordoba-sde": "Wikipedia da 0-0; el sitio oficial de Vélez da 1-1 (goles de Renzo Pérez y Matías Vargas) y Central Córdoba ganó 4-3 por penales, como en RSSSF.",
      "RSSSF atletico-tucuman 1-0 tristan-suarez": "Wikipedia da 2-1; Infobae y ESPN dan 1-0 (gol de Leandro Díaz), como RSSSF.",
    },
    summary: "Rosario Central ganó la Copa Argentina 2017/18: empató 1-1 la final con Gimnasia y Esgrima La Plata en Mendoza y la ganó 4-1 por penales.",
    notes: [{ kind: "formato", text: FORMATO_2019 }],
  }),
  copaArgentina("2018-19", 2019, "arg2019.html", {
    championIds: ["river"],
    runnerUpIds: ["central-cordoba-sde"],
    headings: [/^Copa Argentina 2018\/2019$/, /^Copa de la Superliga 2019$/],
    tableIndex: [0],
    // Dos "Club Atlético Unión" y dos "Club Atlético Sarmiento" en la tabla: se identifican por el puesto.
    tableAliases: { "32": "sarmiento-resistencia", "54": "union-sunchales", "70": "union-santa-fe", "78": "sarmiento-junin" },
    knownTableDiffs: {
      keys: [
        "sportivo-dock-sud:won", "sportivo-dock-sud:drawn", "sportivo-dock-sud:goalsFor", "sportivo-dock-sud:points",
        "patronato-parana:drawn", "patronato-parana:lost", "patronato-parana:goalsAgainst", "patronato-parana:points",
      ],
      explanation: "La tabla de RSSSF cuenta el Patronato–Dock Sud como 1-2; fue 1-1 y Patronato pasó por penales (ver el partido).",
    },
    overrides: {
      "2019-03-13 patronato-parana sportivo-dock-sud": {
        homeGoals: 1,
        awayGoals: 1,
        advancedId: "patronato-parana",
        note: "Patronato ganó 2-1 por penales. RSSSF da 1-2 (y así lo cuenta en su tabla), pero La Nación, El Día y Ámbito dan 1-1 (goles de Rescaldani y Cariaga), como Wikipedia.",
      },
    },
    wikiErrata: {
      "RSSSF newells 1-2 villa-mitre": "Wikipedia da 0-0 y penales; Infobae y 442: el partido se suspendió a los 90 minutos por incidentes de la hinchada de Newell's, con 2-1 para Villa Mitre, y quedó ese resultado, como en RSSSF.",
      "RSSSF nueva-chicago 0-1 central-cordoba-sde": "Wikipedia da 1-2; la web oficial de la Copa Argentina da 0-1 (gol de Melivilo), como RSSSF.",
      "RSSSF defensa-y-justicia 1-0 gimnasia-tiro-salta": "Wikipedia da 2-1; Infobae y ESPN dan 1-0 (gol de Nicolás Fernández), como RSSSF.",
      "RSSSF mitre-sde 1-0 deportivo-roca": "La tabla de resultados de Wikipedia da 2-1, pero su propio cuadro da 1-0; Diario Río Negro también da 1-0 (gol de Cadenazzi a los 89), como RSSSF.",
    },
    summary: "River ganó su tercera Copa Argentina: le ganó 3-0 la final a Central Córdoba de Santiago del Estero, en Mendoza.",
    notes: [{ kind: "formato", text: FORMATO_2019 }],
  }),
  copaArgentina("2019-20", 2020, "arg2020.html", {
    championIds: ["boca"],
    runnerUpIds: ["talleres"],
    headings: [/^Copa Total Argentina$/],
    weekdayYears: true,
    knownTableDiffs: {
      keys: ["defensores-pronunciamiento:played", "defensores-pronunciamiento:lost", "defensores-pronunciamiento:goalsAgainst"],
      explanation: "La tabla de RSSSF no cuenta el River 4-0 Defensores de Pronunciamiento de treintaidosavos (jugado recién el 10 de febrero de 2021, confirmado por Wikipedia).",
    },
    tableAliases: { "39": "talleres-re", "54": "sarmiento-resistencia", "70": "union-sunchales" },
    tableIndex: [0],
    summary: "Boca ganó la Copa Argentina 2019/20: empató 0-0 la final con Talleres en Santiago del Estero y la ganó 5-4 por penales.",
    notes: [
      { kind: "formato", text: FORMATO_2019 },
      { kind: "dato", text: "La pandemia de covid-19 frenó la copa en marzo de 2020, en los treintaidosavos. Se retomó en diciembre de 2020 y la final se jugó el 8 de diciembre de 2021." },
    ],
  }),
  ...[2022, 2023, 2024, 2025, 2026].map((y) =>
    copaArgentina(String(y), y, `arg${y}.html`, {
      runnerUpIds: ({ 2022: ["talleres"], 2023: ["defensa-y-justicia"], 2024: ["velez"], 2025: ["argentinos"] } as Record<number, string[]>)[y],
      championIds: ({ 2022: ["patronato-parana"], 2023: ["estudiantes"], 2024: ["central-cordoba-sde"], 2025: ["independiente-rivadavia"] } as Record<number, string[]>)[y] ?? [],
      ...(y === 2022 && {
        aliases: { ...A_CA, "CA San Martín": "san-martin-tucuman" },
        overrides: {
          "2022-07-06 argentinos defensa-y-justicia": {
            awayGoals: 1,
            note: "RSSSF da 0-2, pero La Nación, Página/12 y Ámbito dan 0-1 (gol de Kevin Gutiérrez), como Wikipedia.",
          },
        },
        knownTableDiffs: {
          keys: ["defensa-y-justicia:goalsFor", "argentinos:goalsAgainst"],
          explanation: "La tabla de RSSSF cuenta el Argentinos–Defensa y Justicia de octavos como 0-2; fue 0-1 (ver el partido).",
        },
      }),
      // Homónimos en la tabla de RSSSF ("Club Atlético Sarmiento", "Independiente", "Talleres", "Gimnasia y Esgrima"),
      // por su puesto: el primero de cada nombre lo resuelve el alias; los demás van acá.
      tableAliases: ({
        2022: { "17": "gimnasia-jujuy", "55": "gimnasia-mendoza" },
        2023: { "58": "sarmiento-resistencia", "62": "independiente-chivilcoy" },
        2024: { "7": "talleres-re", "10": "talleres", "53": "independiente-chivilcoy" },
        2025: { "41": "gimnasia-jujuy", "45": "sarmiento-la-banda" },
        2026: { "30": "gimnasia-jujuy", "38": "gimnasia-mendoza", "57": "sarmiento-la-banda" },
      } as Record<number, Record<string, string>>)[y],
      // Partidos todavía sin rival definido ("TBD").
      skip: (m) => /\bTBD\b/.test(`${m.home} ${m.away}`),
      headings: [y === 2022 ? /^Copa Argentina Axion energy 2022$/ : new RegExp(`^AFA national cup: Copa Argentina ${y}$`)],
      tableIndex: [0],
      ...(y === 2026 && { inProgress: true }),
      summary: ({
        2022: "Patronato, que ese año descendió, ganó su primera Copa Argentina: eliminó a River y a Boca por penales y le ganó 1-0 la final a Talleres en Mendoza.",
        2023: "Estudiantes de La Plata ganó la Copa Argentina: le ganó 3-2 la semifinal a Boca y 1-0 la final a Defensa y Justicia, en Lanús.",
        2024: "Central Córdoba de Santiago del Estero ganó su primer título nacional: le ganó 1-0 la final a Vélez en Santa Fe.",
        2025: "Independiente Rivadavia de Mendoza ganó su primer título nacional: eliminó a River por penales en semifinales y empató 2-2 la final con Argentinos Juniors en Córdoba, que ganó 5-3 por penales.",
        2026: "En juego: cargada hasta los cuartos de final (actualización de RSSSF de septiembre de 2026).",
      } as Record<number, string>)[y],
      notes: [
        { kind: "formato", text: FORMATO_2022 },
        ...(y === 2026 ? [{ kind: "dato" as const, text: "Torneo en curso: se actualiza a medida que RSSSF carga los partidos." }] : []),
      ],
    }),
  ),
];
