// Copas nacionales 1951–1970. Las páginas de formato estándar se importan solas; las demás se cargan a mano,
// partido por partido, desde la página de RSSSF de cada edición (con el mismo control de la copa que el resto).
import type { Match } from "../../lib/types";
import type { TournamentConfig } from "./config";

const AFA = "Asociación del Fútbol Argentino";

type Row = [date: string, stage: string, home: string, hg: number, ag: number, away: string, extra?: Partial<Match>];
const rows = (slug: string, list: Row[]) =>
  list.map(([date, stage, homeId, homeGoals, awayGoals, awayId, extra], i) => ({
    id: `${slug}-${String(i + 1).padStart(3, "0")}`,
    date,
    stage,
    phase: "cup" as const,
    homeId,
    awayId,
    homeGoals,
    awayGoals,
    ...extra,
  }));
const at = (club: string) => ({ venue: `Cancha de ${club}` });
const aet = { note: "Con alargue." };

const EP_EST = { as: "Estudiantes de Eva Perón" };
const home = (as: string) => ({ homeAs: as });
const away = (as: string) => ({ awayAs: as });

export const CUP_TOURNAMENTS_50S: TournamentConfig[] = [
  // ───────── Copa de Competencia 1952 ─────────
  {
    slug: "copa-competencia-1952",
    kind: "cup",
    year: 1952,
    file: "arg-comafa52.html",
    competition: "Copa de Competencia",
    title: "Copa de Competencia 1952",
    tournament: "Copa de Competencia «Trofeo AFA»",
    organizer: AFA,
    championIds: [],
    abandoned: true,
    skip: () => true,
    extraMatches: rows("copa-competencia-1952", [
      ["1952-03-30", "Ronda preliminar", "atletico-tucuman", 1, 3, "estudiantes"],
      ["1952-03-30", "Ronda preliminar", "godoy-cruz", 3, 4, "ferro", at("Independiente Rivadavia")],
      ["1952-03-30", "Ronda preliminar", "newells", 1, 2, "all-boys", { ...at("Rosario Central"), ...aet }],
      ["1952-03-30", "Ronda preliminar", "talleres", 3, 1, "central"],
      ["1952-04-02", "Ronda preliminar", "atlanta", 1, 2, "colon-santa-fe", at("San Lorenzo")],
      ["1952-07-23", "Ronda preliminar", "chacarita", 3, 4, "gimnasia", at("Atlanta")],
      ["1952-07-23", "Ronda preliminar", "huracan", 2, 2, "almagro", { ...at("San Lorenzo"), advancedId: "almagro", note: "Con alargue. Pasó Almagro por córners (10-9)." }],
      ["1952-07-23", "Ronda preliminar", "platense", 5, 1, "quilmes", at("Boca Juniors")],
    ]),
    summary: "La Copa de Competencia de 1952 quedó en la ronda preliminar: la primera ronda se postergó por la muerte de Eva Perón y la copa se abandonó.",
    notes: [
      { kind: "formato", text: "Eliminación directa entre los equipos de Primera, algunos de la Primera B y los campeones de las ligas de Tucumán, Mendoza y Córdoba (Atlético Tucumán, Godoy Cruz y Talleres)." },
      { kind: "dato", text: "Solo se jugó la ronda preliminar. La primera ronda, prevista para el 8 de agosto, se postergó por la muerte de Eva Perón (26 de julio) y la copa no se terminó." },
    ],
  },

  // ───────── Campeonato de Campeones de la República 1959 ─────────
  {
    slug: "campeonato-campeones-1959",
    kind: "cup",
    year: 1959,
    file: "arg-ccra59.html",
    competition: "Campeonato de Campeones de la República",
    title: "Campeonato de Campeones 1959",
    tournament: "Campeonato de Campeones de la República Argentina",
    organizer: `${AFA} (Consejo Federal; reconocido como copa de Primera en 2024)`,
    championIds: ["atletico-tucuman"],
    runnerUpIds: ["el-quequen"],
    skip: () => true,
    extraMatches: rows("campeonato-campeones-1959", [
      ["1959-11-22", "Provincia de Buenos Aires · 1.ª ronda", "defensores-unidos-zarate", 2, 1, "river-plate-junin"],
      ["1959-11-22", "Provincia de Buenos Aires · 1.ª ronda", "el-quequen", 4, 2, "rivadavia-necochea"],
      ["1959-11-22", "Provincia de Buenos Aires · 1.ª ronda", "gimnasia-chivilcoy", 2, 1, "fortin-vuelta-rojas"],
      ["1959-11-22", "Provincia de Buenos Aires · 1.ª ronda", "quilmes-mdp", 0, 1, "ramon-santamarina"],
      ["1959-11-22", "Provincia de Buenos Aires · 1.ª ronda", "rosario-puerto-belgrano", 6, 3, "estudiantes-olavarria"],
      ["1959-11-29", "Provincia de Buenos Aires · 2.ª ronda", "el-quequen", 2, 1, "rosario-puerto-belgrano"],
      ["1959-11-29", "Provincia de Buenos Aires · 2.ª ronda", "gimnasia-chivilcoy", 1, 3, "defensores-unidos-zarate"],
      ["1959-11-29", "Provincia de Buenos Aires · 2.ª ronda", "ramon-santamarina", 7, 0, "empleados-comercio-bolivar"],
      ["1959-12-06", "Provincia de Buenos Aires · 3.ª ronda", "defensores-unidos-zarate", 0, 1, "el-quequen"],
      ["1959-12-13", "Provincia de Buenos Aires · 4.ª ronda", "el-quequen", 5, 3, "ramon-santamarina", aet],
      ["1959-12-20", "Provincia de Buenos Aires · 5.ª ronda", "el-quequen", 2, 0, "deportivo-la-plata", { venue: "Cancha de Huracán (Tres Arroyos)" }],
      ["1959-11-22", "Provincia de Córdoba · 1.ª ronda", "sportivo-atenas", 0, 1, "river-plate-villa-maria"],
      ["1959-11-29", "Provincia de Córdoba · 2.ª ronda", "river-plate-villa-maria", 3, 4, "sportivo-belgrano-sf"],
      ["1959-12-13", "Fase final · 1.ª ronda", "argentino-mendoza", 5, 2, "sportivo-estudiantes-sl", { venue: "Cancha de Gimnasia y Esgrima (Mendoza)" }],
      ["1959-12-13", "Fase final · 1.ª ronda", "atletico-tucuman", 0, 0, "gorriti-jujuy", { walkover: true, awardedTo: "atletico-tucuman", note: "No se jugó: pasó Atlético Tucumán." }],
      ["1959-12-13", "Fase final · 1.ª ronda", "central-cordoba-sde", 3, 0, "correos-salta"],
      ["1959-12-13", "Fase final · 1.ª ronda", "guarani-antonio-franco", 6, 3, "don-orione-resistencia"],
      ["1959-12-13", "Fase final · 1.ª ronda", "los-andes-sj", 2, 0, "san-francisco-la-rioja"],
      ["1959-12-13", "Fase final · 1.ª ronda", "sportivo-belgrano-sf", 4, 0, "sportivo-velez-catamarca"],
      ["1959-12-15", "Fase final · 1.ª ronda", "belgrano-parana", 2, 4, "union-santa-fe"],
      ["1959-12-27", "Fase final · 1.ª ronda", "el-quequen", 11, 1, "villa-congreso-viedma"],
      ["1959-12-27", "Fase final · 1.ª ronda", "huracan-guatrache", 3, 2, "ferrocarril-sud-neuquen"],
      ["1959-12-27", "Fase final · 1.ª ronda", "tnp-corrientes", 3, 0, "fontana-formosa"],
      ["1960-01-10", "Fase final · 2.ª ronda", "argentino-mendoza", 5, 0, "huracan-guatrache", { venue: "Cancha de Gimnasia y Esgrima (Mendoza)" }],
      ["1960-01-10", "Fase final · 2.ª ronda", "atletico-tucuman", 4, 3, "los-andes-sj"],
      ["1960-01-10", "Fase final · 2.ª ronda", "central-cordoba-sde", 1, 5, "sportivo-belgrano-sf"],
      ["1960-01-10", "Fase final · 2.ª ronda", "el-quequen", 6, 2, "guarani-antonio-franco"],
      ["1960-01-10", "Fase final · 2.ª ronda", "union-santa-fe", 3, 2, "tnp-corrientes"],
      ["1960-01-16", "Cuartos de final", "el-quequen", 3, 1, "union-santa-fe", { venue: "Cancha de Olimpo (Bahía Blanca)" }],
      ["1960-01-24", "Cuartos de final", "argentino-mendoza", 1, 2, "atletico-tucuman", { venue: "Cancha de Gimnasia y Esgrima (Mendoza)", ...aet }],
      ["1960-01-28", "Semifinal", "atletico-tucuman", 2, 1, "sportivo-belgrano-sf", { venue: "Cancha de Olimpo (Bahía Blanca)" }],
      ["1960-01-30", "Final", "el-quequen", 1, 1, "atletico-tucuman", {
        venue: "Cancha de El Nacional (Tres Arroyos)",
        advancedId: "atletico-tucuman",
        note: "Con alargue. Atlético Tucumán ganó 5-3 por penales. Goles: E. Villar 74' / Albrecht 6'. Árbitro: Berdasco.",
      }],
    ]),
    summary: "Atlético Tucumán ganó el Campeonato de Campeones: 1-1 con El Quequén de Oriente en la final y 5-3 por penales. En 2024 la AFA lo reconoció como título de Primera.",
    notes: [
      { kind: "formato", text: "Abierto a los campeones de todas las ligas regionales del país. Las provincias de Buenos Aires y Córdoba jugaron primero su propio cuadro; después, eliminación directa a un partido." },
      { kind: "identidad", text: "Lo organizó el Consejo Federal de la AFA. El 31 de octubre de 2024 la AFA lo reconoció como copa oficial de Primera." },
      { kind: "dato", text: "Empleados de Comercio (Bolívar) pasó la primera ronda sin jugar: la liga de Carlos Casares no había definido su campeón." },
      { kind: "identidad", text: "Estudiantes de San Luis figura en la base como Sportivo Estudiantes, el mismo club que jugó la Copa de la República 1943 y la Copa Argentina 1969." },
    ],
  },

  // ───────── Copa Argentina 1969 ─────────
  {
    slug: "copa-argentina-1969",
    kind: "cup",
    year: 1969,
    file: "argcup69.html",
    wiki: "Copa Argentina 1969",
    competition: "Copa Argentina",
    title: "Copa Argentina 1969",
    tournament: "Copa de Argentina",
    organizer: AFA,
    championIds: ["boca"],
    runnerUpIds: ["atlanta"],
    skip: () => true,
    // La tabla de todos los equipos que publica RSSSF controla cada partido cargado a mano.
    tableIndex: 0,
    checkEliminations: true,
    aliases: {
      "Club Atlético Boca Juniors": "boca",
      "Club Atlético Atlanta": "atlanta",
      "Club Atlético Rosario Central": "central",
      "Club Atlético Colón": "colon-santa-fe",
      "CA San Lorenzo de Almagro": "sanlorenzo",
      "Club Atlético Chacarita Juniors": "chacarita",
      "Club Atlético Huracán": "huracan",
      "Club Atlético Lanús": "lanus",
      "CD Guaraní Antonio Franco": "guarani-antonio-franco",
      "Club Atlético Platense": "platense",
      "AC y Deportiva Altos Hornos Zapla": "altos-hornos-zapla",
      "CA Independiente (Avellaneda)": "independiente",
      "Racing Club": "racing",
      "Club Atlético Newell's Old Boys": "newells",
      "Asociación A. Argentinos Juniors": "argentinos",
      "Club Atlético Sarmiento": "sarmiento-la-banda",
      "Asociación Club Atlético All Boys": "all-boys-santa-rosa",
      "Club Atlético Central Norte": "central-norte-salta",
      "Club Atlético Banfield": "banfield",
      "Club Atlético Los Andes": "los-andes",
      "Club Atlético Américo Tesorieri": "americo-tesorieri-la-rioja",
      "Club Deportivo Morón": "deportivo-moron",
      "C. de Gimnasia y Esgrima La Plata": "gimnasia",
      "Club Atlético Tucumán": "atletico-tucuman",
      "Club Atlético Sporting": "sporting-punta-alta",
      "Club Almagro": "almagro",
      "Club Sportivo Los Andes": "los-andes-sj",
      "Club Atlético Unión": "union-santa-fe",
      "Club Sportivo Belgrano": "sportivo-belgrano-sf",
      "CD Godoy Cruz Antonio Tomba": "godoy-cruz",
      "Lipton Football Club": "lipton-corrientes",
      "Quilmes Atlético Club": "quilmes",
      "Club Atlético Chaco For Ever": "chaco-for-ever",
      "Club Sportivo Estudiantes": "sportivo-estudiantes-sl",
      "CA Independiente (Trelew)": "independiente-trelew",
      "Club Atlético Pacífico": "pacifico-neuquen",
      "AC Social y Deportivo Sol de Mayo": "sol-de-mayo-viedma",
      "Club Deportivo Américo Tesorieri": "americo-tesorieri-catamarca",
      "Club Sportivo General San Martín": "general-san-martin-formosa",
      "Club Atlético Talleres Juniors": "talleres-juniors-cr",
      "CA Patronato dl Juventud Católica": "patronato-parana",
    },
    extraMatches: rows("copa-argentina-1969", [
      // Zonas regionales (diciembre de 1968 y enero de 1969): series de ida y vuelta entre campeones de ligas del interior.
      ["1968-12-15", "Zona regional A", "americo-tesorieri-catamarca", 1, 1, "central-norte-salta", { venue: "Catamarca" }],
      ["1968-12-22", "Zona regional A", "central-norte-salta", 3, 0, "americo-tesorieri-catamarca", { venue: "Salta" }],
      ["1969-01-12", "Zona regional A", "central-norte-salta", 0, 1, "altos-hornos-zapla", { venue: "Salta" }],
      ["1969-01-19", "Zona regional A", "altos-hornos-zapla", 1, 1, "central-norte-salta", { venue: "Jujuy" }],
      ["1968-12-15", "Zona regional B", "guarani-antonio-franco", 3, 0, "patronato-parana", { venue: "Misiones" }],
      ["1968-12-22", "Zona regional B", "patronato-parana", 1, 3, "guarani-antonio-franco", { venue: "Entre Ríos" }],
      ["1968-12-29", "Zona regional B", "general-san-martin-formosa", 2, 3, "chaco-for-ever", { venue: "Formosa" }],
      ["1969-01-05", "Zona regional B", "chaco-for-ever", 1, 0, "general-san-martin-formosa", { venue: "Chaco" }],
      ["1969-01-12", "Zona regional B", "guarani-antonio-franco", 0, 0, "chaco-for-ever", { venue: "Misiones" }],
      ["1969-01-19", "Zona regional B", "chaco-for-ever", 1, 2, "guarani-antonio-franco", { venue: "Chaco" }],
      ["1968-12-15", "Zona regional C", "pacifico-neuquen", 2, 3, "sportivo-estudiantes-sl", { venue: "Neuquén" }],
      ["1968-12-22", "Zona regional C", "sportivo-estudiantes-sl", 1, 1, "pacifico-neuquen", { venue: "San Luis" }],
      ["1969-01-05", "Zona regional C", "sportivo-estudiantes-sl", 1, 0, "americo-tesorieri-la-rioja", { venue: "San Luis" }],
      ["1969-01-17", "Zona regional C", "americo-tesorieri-la-rioja", 3, 1, "sportivo-estudiantes-sl", { venue: "La Rioja" }],
      ["1968-12-15", "Zona regional D", "independiente-trelew", 2, 1, "talleres-juniors-cr", { venue: "Rawson" }],
      ["1968-12-22", "Zona regional D", "talleres-juniors-cr", 0, 2, "independiente-trelew", { venue: "Comodoro Rivadavia" }],
      ["1968-12-29", "Zona regional D", "sol-de-mayo-viedma", 1, 1, "all-boys-santa-rosa", { venue: "Río Negro" }],
      ["1969-01-05", "Zona regional D", "all-boys-santa-rosa", 1, 0, "sol-de-mayo-viedma", { venue: "La Pampa" }],
      ["1969-01-12", "Zona regional D", "independiente-trelew", 2, 3, "all-boys-santa-rosa", { venue: "Rawson" }],
      ["1969-01-19", "Zona regional D", "all-boys-santa-rosa", 4, 0, "independiente-trelew", { venue: "La Pampa" }],
      // Grupos (febrero de 1969): series de ida y vuelta entre clubes de Primera y del interior.
      ["1969-02-06", "Grupo A", "altos-hornos-zapla", 2, 2, "almagro", { venue: "Jujuy" }],
      ["1969-02-06", "Grupo A", "central-norte-salta", 1, 0, "atlanta", { venue: "Cancha de Gimnasia y Tiro (Salta)" }],
      ["1969-02-09", "Grupo A", "altos-hornos-zapla", 1, 0, "almagro", { venue: "La Tablada (Jujuy)" }],
      ["1969-02-09", "Grupo A", "central-norte-salta", 0, 3, "atlanta", { venue: "Cancha de Gimnasia y Tiro (Salta)" }],
      ["1969-02-13", "Grupo A", "altos-hornos-zapla", 0, 3, "atlanta", { venue: "Jujuy" }],
      ["1969-02-15", "Grupo A", "altos-hornos-zapla", 1, 2, "atlanta", { venue: "Jujuy" }],
      ["1969-02-06", "Grupo B", "americo-tesorieri-la-rioja", 0, 5, "sanlorenzo", { venue: "Estadio de la Liga Riojana (La Rioja)" }],
      ["1969-02-07", "Grupo B", "sportivo-belgrano-sf", 0, 1, "argentinos", { venue: "Córdoba" }],
      ["1969-02-08", "Grupo B", "americo-tesorieri-la-rioja", 0, 3, "sanlorenzo", { venue: "Estadio de Vargas (La Rioja)" }],
      ["1969-02-09", "Grupo B", "sportivo-belgrano-sf", 1, 1, "argentinos", { venue: "San Francisco (Córdoba)" }],
      ["1969-02-12", "Grupo B", "sanlorenzo", 1, 0, "argentinos", { venue: "Estadio de la Liga Riojana (La Rioja)" }],
      ["1969-02-15", "Grupo B", "argentinos", 0, 3, "sanlorenzo", { venue: "Cancha de Talleres (Córdoba)" }],
      ["1969-02-06", "Grupo C", "lipton-corrientes", 1, 4, "lanus", { venue: "Cancha de Lipton (Corrientes)" }],
      ["1969-02-06", "Grupo C", "guarani-antonio-franco", 2, 0, "gimnasia", { venue: "Posadas" }],
      ["1969-02-08", "Grupo C", "lipton-corrientes", 3, 5, "lanus", { venue: "Cancha de Lipton (Corrientes)" }],
      ["1969-02-09", "Grupo C", "guarani-antonio-franco", 4, 4, "gimnasia", { venue: "Posadas" }],
      ["1969-02-12", "Grupo C", "guarani-antonio-franco", 0, 4, "lanus", { venue: "Posadas" }],
      ["1969-02-15", "Grupo C", "guarani-antonio-franco", 4, 3, "lanus", { venue: "Cancha de Chaco For Ever (Resistencia)" }],
      ["1969-02-05", "Grupo D", "central", 3, 2, "quilmes", { venue: "Rosario" }],
      ["1969-02-06", "Grupo D", "newells", 0, 1, "banfield", { venue: "Rosario" }],
      ["1969-02-07", "Grupo D", "central", 4, 0, "quilmes", { venue: "Rosario" }],
      ["1969-02-09", "Grupo D", "newells", 3, 1, "banfield", { venue: "Cancha de Newell's Old Boys" }],
      ["1969-02-12", "Grupo D", "central", 0, 0, "newells", { venue: "Rosario" }],
      ["1969-02-15", "Grupo D", "newells", 2, 3, "central", { venue: "Cancha de Newell's Old Boys" }],
      ["1969-02-06", "Grupo E", "atletico-tucuman", 2, 3, "boca", { venue: "Tucumán" }],
      ["1969-02-06", "Grupo E", "sarmiento-la-banda", 2, 0, "los-andes", { venue: "Santiago del Estero" }],
      ["1969-02-09", "Grupo E", "atletico-tucuman", 0, 0, "boca", { venue: "Cancha de Atlético Tucumán" }],
      ["1969-02-09", "Grupo E", "sarmiento-la-banda", 0, 1, "los-andes", { venue: "Santiago del Estero" }],
      ["1969-02-12", "Grupo E", "sarmiento-la-banda", 1, 3, "boca", { venue: "Cancha de Central Córdoba (Santiago del Estero)" }],
      ["1969-02-14", "Grupo E", "sarmiento-la-banda", 2, 4, "boca", { venue: "Cancha de Central Córdoba (Santiago del Estero)" }],
      ["1969-02-06", "Grupo F", "godoy-cruz", 1, 3, "chacarita", { venue: "Mendoza" }],
      ["1969-02-06", "Grupo F", "los-andes-sj", 1, 2, "racing", { venue: "San Juan" }],
      ["1969-02-09", "Grupo F", "godoy-cruz", 2, 3, "chacarita", { venue: "Cancha de Godoy Cruz (Mendoza)" }],
      ["1969-02-09", "Grupo F", "los-andes-sj", 1, 1, "racing", { venue: "Parque de Mayo (San Juan)" }],
      ["1969-02-12", "Grupo F", "chacarita", 3, 1, "racing", { venue: "Mendoza" }],
      ["1969-02-15", "Grupo F", "racing", 2, 2, "chacarita", { venue: "Parque de Mayo (San Juan)" }],
      ["1969-02-06", "Grupo G", "sporting-punta-alta", 1, 2, "huracan", { venue: "Cancha de Sporting (Punta Alta)" }],
      ["1969-02-06", "Grupo G", "all-boys-santa-rosa", 0, 1, "platense", { venue: "Santa Rosa (La Pampa)" }],
      ["1969-02-08", "Grupo G", "sporting-punta-alta", 1, 1, "huracan", { venue: "Cancha de Olimpo (Bahía Blanca)" }],
      ["1969-02-09", "Grupo G", "all-boys-santa-rosa", 0, 1, "platense", { venue: "Santa Rosa (La Pampa)" }],
      ["1969-02-13", "Grupo G", "huracan", 2, 4, "platense", at("Racing Club")],
      ["1969-02-20", "Grupo G", "platense", 0, 3, "huracan", at("Atlanta")],
      ["1969-02-05", "Grupo H", "colon-santa-fe", 1, 1, "deportivo-moron", at("Colón")],
      ["1969-02-06", "Grupo H", "union-santa-fe", 2, 4, "independiente", { venue: "Santa Fe" }],
      ["1969-02-08", "Grupo H", "colon-santa-fe", 3, 2, "deportivo-moron", at("Colón")],
      ["1969-02-09", "Grupo H", "union-santa-fe", 1, 1, "independiente", at("Unión")],
      ["1969-02-12", "Grupo H", "colon-santa-fe", 1, 3, "independiente", at("Colón")],
      ["1969-02-15", "Grupo H", "colon-santa-fe", 5, 1, "independiente", at("Colón")],
      // Cuartos, semifinales y final: ida y vuelta.
      ["1969-07-09", "Cuartos de final (ida)", "central", 2, 0, "lanus", at("Rosario Central")],
      ["1969-07-09", "Cuartos de final (ida)", "boca", 0, 1, "chacarita", at("Racing Club")],
      ["1969-07-09", "Cuartos de final (ida)", "colon-santa-fe", 1, 0, "huracan", at("Unión")],
      ["1969-07-11", "Cuartos de final (ida)", "sanlorenzo", 1, 0, "atlanta", at("Deportivo Morón")],
      ["1969-07-13", "Cuartos de final (vuelta)", "atlanta", 2, 0, "sanlorenzo", { ...at("Deportivo Morón"), advancedId: "atlanta", note: "Pasó Atlanta (2-1 en el global)." }],
      ["1969-07-13", "Cuartos de final (vuelta)", "lanus", 1, 3, "central", { ...at("Talleres (Remedios de Escalada)"), advancedId: "central", note: "Pasó Rosario Central (5-1 en el global)." }],
      ["1969-07-13", "Cuartos de final (vuelta)", "chacarita", 1, 3, "boca", { ...at("Racing Club"), advancedId: "boca", note: "Pasó Boca Juniors (3-2 en el global)." }],
      ["1969-07-13", "Cuartos de final (vuelta)", "huracan", 3, 2, "colon-santa-fe", { ...at("San Lorenzo"), advancedId: "colon-santa-fe", note: "3-3 en el global: pasó Colón por penales (3-2)." }],
      ["1969-07-16", "Semifinal (ida)", "colon-santa-fe", 0, 5, "boca", at("Unión")],
      ["1969-07-17", "Semifinal (ida)", "atlanta", 2, 1, "central", at("Atlanta")],
      ["1969-07-20", "Semifinal (vuelta)", "central", 1, 2, "atlanta", { venue: "Rosario", advancedId: "atlanta", note: "Pasó Atlanta (4-2 en el global)." }],
      ["1969-07-20", "Semifinal (vuelta)", "boca", 1, 0, "colon-santa-fe", { ...at("Boca Juniors"), advancedId: "boca", note: "Pasó Boca Juniors (6-0 en el global)." }],
      ["1969-07-23", "Final (ida)", "atlanta", 1, 3, "boca", at("San Lorenzo")],
      ["1969-07-27", "Final (vuelta)", "boca", 0, 1, "atlanta", { ...at("San Lorenzo"), advancedId: "boca", note: "Boca Juniors campeón por diferencia de gol (3-2 en el global)." }],
    ]),
    summary: "Boca Juniors ganó la primera Copa Argentina: 3-1 y 0-1 con Atlanta en la final, campeón por diferencia de gol. Atlanta jugó la Recopa Sudamericana 1970.",
    notes: [
      {
        kind: "formato",
        text: "Primero, zonas regionales con los campeones de las ligas del interior; después, grupos de cuatro con equipos de Primera, y desde cuartos de final, series de ida y vuelta.",
      },
      { kind: "dato", text: "No la jugaron Estudiantes, River y Vélez, clasificados a la Copa Libertadores 1969. La zona regional empezó en diciembre de 1968." },
      { kind: "fuentes", text: "La tabla resumen es la que publica RSSSF con todos los partidos de la copa; la calculada con los partidos coincide." },
    ],
  },

  // ───────── Copa Argentina 1970 (sin terminar) ─────────
  {
    slug: "copa-argentina-1970",
    kind: "cup",
    year: 1970,
    file: "argcup70.html",
    competition: "Copa Argentina",
    title: "Copa Argentina 1970",
    tournament: "Copa de Argentina",
    organizer: AFA,
    championIds: [],
    abandoned: true,
    skip: () => true,
    // Nombres de la lista de participantes de la página.
    aliases: {
      "All Boys (RSA)": "all-boys-santa-rosa",
      "Argentinos del Norte": "argentinos-del-norte",
      Atenas: "atenas-santo-tome",
      "Bartolomé Mitre": "bartolome-mitre-posadas",
      "Central Norte": "central-norte-salta",
      "Central Norte Argentino": "central-norte-resistencia",
      "Colón Juniors": "colon-juniors-sj",
      Instituto: "instituto",
      "Juventud Unida": "juventud-unida-sl",
      Mitre: "mitre-sde",
      Palmira: "palmira-mendoza",
      "Quilmes (MDQ)": "quilmes-mdp",
      "Quilmes (Qui)": "quilmes",
      "Platense (VLo)": "platense",
      "Independiente (Ave)": "independiente",
      "Gimnasia y Esgrima LPG": "gimnasia",
    },
    extraMatches: rows("copa-argentina-1970", [
      ["1970-03-04", "Primera ronda (ida)", "all-boys-santa-rosa", 3, 1, "gimnasia"],
      ["1970-03-04", "Primera ronda (ida)", "argentinos-del-norte", 1, 0, "velez", at("San Martín (Tucumán)")],
      ["1970-03-04", "Primera ronda (ida)", "bartolome-mitre-posadas", 1, 2, "ferro"],
      ["1970-03-04", "Primera ronda (ida)", "central-norte-salta", 0, 3, "chacarita", at("Gimnasia y Tiro (Salta)")],
      ["1970-03-04", "Primera ronda (ida)", "central-norte-resistencia", 0, 1, "racing", at("Chaco For Ever")],
      ["1970-03-04", "Primera ronda (ida)", "colon-santa-fe", 3, 2, "atenas-santo-tome"],
      ["1970-03-04", "Primera ronda (ida)", "colon-juniors-sj", 2, 3, "lanus"],
      ["1970-03-04", "Primera ronda (ida)", "juventud-unida-sl", 0, 0, "atlanta", at("Sportivo Estudiantes (San Luis)")],
      ["1970-03-04", "Primera ronda (ida)", "palmira-mendoza", 3, 1, "independiente"],
      ["1970-03-04", "Primera ronda (ida)", "quilmes-mdp", 0, 2, "argentinos", at("General San Martín (Mar del Plata)")],
      ["1970-03-04", "Primera ronda (ida)", "central", 4, 2, "huracan"],
      ["1970-03-04", "Primera ronda (ida)", "rosario-puerto-belgrano", 3, 2, "platense", at("Bella Vista (Bahía Blanca)")],
      ["1970-03-05", "Primera ronda (ida)", "instituto", 0, 0, "quilmes"],
      ["1970-03-05", "Primera ronda (ida)", "mitre-sde", 0, 0, "banfield"],
      ["1970-03-05", "Primera ronda (ida)", "newells", 0, 0, "los-andes"],
      ["1970-03-05", "Primera ronda (ida)", "union-santa-fe", 2, 2, "sanlorenzo"],
      ["1970-03-06", "Primera ronda (vuelta)", "argentinos-del-norte", 1, 2, "velez", { advancedId: "velez", note: "2-2 en el global: pasó Vélez por penales (4-3)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "all-boys-santa-rosa", 1, 2, "gimnasia", { advancedId: "all-boys-santa-rosa", note: "Pasó All Boys (4-3 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "bartolome-mitre-posadas", 1, 1, "ferro", { advancedId: "ferro", note: "Pasó Ferro Carril Oeste (3-2 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "central-norte-resistencia", 3, 3, "racing", { ...at("Chaco For Ever"), advancedId: "racing", note: "Pasó Racing Club (4-3 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "colon-santa-fe", 3, 0, "atenas-santo-tome", { advancedId: "colon-santa-fe", note: "Pasó Colón (6-2 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "colon-juniors-sj", 2, 4, "lanus", { advancedId: "lanus", note: "Pasó Lanús (7-4 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "huracan", 1, 1, "central", { advancedId: "central", note: "Pasó Rosario Central (5-3 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "juventud-unida-sl", 0, 2, "atlanta", { advancedId: "atlanta", note: "Pasó Atlanta (2-0 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "mitre-sde", 2, 1, "banfield", { advancedId: "mitre-sde", note: "Pasó Mitre (2-1 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "palmira-mendoza", 2, 2, "independiente", { ...at("Godoy Cruz"), advancedId: "palmira-mendoza", note: "Pasó Palmira (5-3 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "quilmes-mdp", 1, 2, "argentinos", { ...at("General San Martín (Mar del Plata)"), advancedId: "argentinos", note: "Pasó Argentinos Juniors (4-1 en el global)." }],
      ["1970-03-07", "Primera ronda (vuelta)", "rosario-puerto-belgrano", 0, 2, "platense", { advancedId: "platense", note: "Pasó Platense (4-3 en el global)." }],
      ["1970-03-08", "Primera ronda (vuelta)", "central-norte-salta", 1, 4, "chacarita", { ...at("Gimnasia y Tiro (Salta)"), advancedId: "chacarita", note: "Pasó Chacarita Juniors (7-1 en el global)." }],
      ["1970-03-08", "Primera ronda (vuelta)", "instituto", 4, 1, "quilmes", { advancedId: "instituto", note: "Pasó Instituto (4-1 en el global)." }],
      ["1970-03-08", "Primera ronda (vuelta)", "los-andes", 0, 0, "newells", { ...at("Banfield"), advancedId: "newells", note: "0-0 en el global: pasó Newell's por penales (4-2)." }],
      ["1970-03-08", "Primera ronda (vuelta)", "sanlorenzo", 1, 0, "union-santa-fe", { advancedId: "sanlorenzo", note: "Pasó San Lorenzo (3-2 en el global)." }],
      ["1970-03-11", "Segunda ronda (ida)", "all-boys-santa-rosa", 0, 1, "atlanta", at("General Belgrano (Santa Rosa)")],
      ["1970-03-11", "Segunda ronda (ida)", "argentinos", 1, 1, "platense", at("General San Martín (Mar del Plata)")],
      ["1970-03-11", "Segunda ronda (ida)", "colon-santa-fe", 0, 0, "sanlorenzo"],
      ["1970-03-11", "Segunda ronda (ida)", "instituto", 0, 0, "velez"],
      ["1970-03-11", "Segunda ronda (ida)", "palmira-mendoza", 2, 1, "lanus", at("Godoy Cruz")],
      ["1970-03-11", "Segunda ronda (ida)", "racing", 2, 1, "ferro", at("Chaco For Ever")],
      ["1970-03-11", "Segunda ronda (ida)", "central", 1, 0, "newells"],
      ["1970-03-13", "Segunda ronda (ida)", "mitre-sde", 0, 4, "chacarita"],
      ["1970-03-14", "Segunda ronda (vuelta)", "all-boys-santa-rosa", 1, 0, "atlanta", { advancedId: "all-boys-santa-rosa", note: "1-1 en el global: pasó All Boys por penales (4-2)." }],
      ["1970-03-14", "Segunda ronda (vuelta)", "instituto", 0, 2, "velez", { advancedId: "velez", note: "Pasó Vélez Sarsfield (2-0 en el global)." }],
      ["1970-03-14", "Segunda ronda (vuelta)", "newells", 0, 0, "central", { advancedId: "central", note: "Pasó Rosario Central (1-0 en el global)." }],
      ["1970-03-14", "Segunda ronda (vuelta)", "palmira-mendoza", 1, 2, "lanus", { ...at("Godoy Cruz"), advancedId: "lanus", note: "3-3 en el global: pasó Lanús por penales (4-3)." }],
      ["1970-03-14", "Segunda ronda (vuelta)", "racing", 3, 1, "ferro", { ...at("Guaraní Antonio Franco (Posadas)"), advancedId: "racing", note: "Pasó Racing Club (5-2 en el global)." }],
      ["1970-03-14", "Segunda ronda (vuelta)", "sanlorenzo", 4, 1, "colon-santa-fe", { advancedId: "sanlorenzo", note: "Pasó San Lorenzo (4-1 en el global)." }],
      ["1970-03-15", "Segunda ronda (vuelta)", "chacarita", 0, 1, "mitre-sde", { venue: "Salta", advancedId: "chacarita", note: "Pasó Chacarita Juniors (4-1 en el global)." }],
      ["1970-03-15", "Segunda ronda (vuelta)", "platense", 5, 1, "argentinos", { ...at("Atlanta"), advancedId: "platense", note: "Pasó Platense (6-2 en el global)." }],
      ["1970-09-09", "Cuartos de final (ida)", "central", 2, 1, "sanlorenzo"],
      ["1970-09-10", "Cuartos de final (ida)", "chacarita", 0, 1, "velez"],
      ["1970-09-10", "Cuartos de final (ida)", "lanus", 0, 1, "racing"],
      ["1970-09-16", "Cuartos de final (ida)", "all-boys-santa-rosa", 2, 0, "platense"],
      ["1970-09-23", "Cuartos de final (vuelta)", "racing", 3, 0, "lanus", { advancedId: "racing", note: "Pasó Racing Club (4-0 en el global)." }],
      ["1970-09-23", "Cuartos de final (vuelta)", "sanlorenzo", 3, 0, "central", { advancedId: "sanlorenzo", note: "Pasó San Lorenzo (4-2 en el global)." }],
      ["1970-09-23", "Cuartos de final (vuelta)", "velez", 2, 1, "chacarita", { advancedId: "velez", note: "Pasó Vélez Sarsfield (3-1 en el global)." }],
      ["1970-09-27", "Cuartos de final (vuelta)", "all-boys-santa-rosa", 0, 0, "platense", { ...at("General Belgrano (Santa Rosa)"), advancedId: "all-boys-santa-rosa", note: "Pasó All Boys (2-0 en el global)." }],
      ["1971-02-13", "Semifinal (ida)", "all-boys-santa-rosa", 1, 1, "sanlorenzo", at("Belgrano (Santa Rosa)")],
      ["1971-02-16", "Semifinal (ida)", "velez", 3, 2, "racing", at("Atlanta")],
      ["1971-02-18", "Semifinal (vuelta)", "racing", 2, 3, "velez", { ...at("Atlanta"), advancedId: "velez", note: "Con alargue. Pasó Vélez Sarsfield (6-4 en el global)." }],
      ["1971-02-18", "Semifinal (vuelta)", "sanlorenzo", 3, 1, "all-boys-santa-rosa", { ...at("Atlanta"), advancedId: "sanlorenzo", note: "Con alargue. Pasó San Lorenzo (4-2 en el global)." }],
      ["1971-03-03", "Final (ida)", "sanlorenzo", 2, 2, "velez", { ...at("Atlanta"), note: "La vuelta nunca se jugó y la copa quedó sin campeón." }],
    ]),
    summary: "La segunda Copa Argentina quedó sin campeón: San Lorenzo y Vélez empataron 2-2 la ida de la final, en marzo de 1971, y la vuelta nunca se jugó.",
    notes: [
      { kind: "formato", text: "Equipos de Primera no clasificados a la Copa Libertadores 1970 y los mejores del interior, en series de ida y vuelta; los empates en el global se definieron por penales." },
      { kind: "dato", text: "Las semifinales y la ida de la final se jugaron en 1971. La vuelta de la final no se jugó." },
      { kind: "fuentes", text: "RSSSF no da la cancha de todos los partidos." },
    ],
  },

  // ───────── Copa Perón 1955 (Campeonato de la Provincia de Buenos Aires) ─────────
  {
    slug: "copa-peron-1955",
    kind: "cup",
    year: 1955,
    file: "qperon55.html",
    sourceUrl: "https://www.rsssf.org/tablesq/qperon55.html",
    competition: "Copa Juan Domingo Perón",
    title: "Copa Perón 1955",
    tournament: "Campeonato de la Provincia de Buenos Aires · Copa Juan Domingo Perón",
    organizer: "Gobierno de la Provincia de Buenos Aires (reconocida por la AFA en 2024)",
    championIds: ["lanus"],
    runnerUpIds: ["estudiantes"],
    skip: () => true,
    reentry: { note: "Doble eliminación: un equipo que perdía pasaba al cuadro de perdedores y quedaba afuera recién con la segunda derrota." },
    extraMatches: rows("copa-peron-1955", [
      ["1955-03-12", "Primera ronda", "chacarita", 2, 1, "gimnasia", away("Gimnasia y Esgrima (Eva Perón)")],
      ["1955-03-12", "Primera ronda", "estudiantes", 2, 2, "banfield", { homeAs: EP_EST.as, advancedId: "estudiantes", note: "Con alargue. Pasó Estudiantes por córners (1-0)." }],
      ["1955-03-13", "Primera ronda", "racing", 0, 0, "lanus", { advancedId: "lanus", note: "Con alargue. Pasó Lanús por córners (1-0)." }],
      ["1955-03-20", "Ganadores · Semifinal", "lanus", 2, 1, "estudiantes", away(EP_EST.as)],
      ["1955-03-20", "Ganadores · Semifinal", "tigre", 2, 0, "chacarita", { ...at("Platense"), note: "Goles: R. Bores 32' (penal), E. Aguilar 44'." }],
      ["1955-03-20", "Perdedores · Primera ronda", "banfield", 2, 1, "gimnasia", away("Gimnasia y Esgrima (Eva Perón)")],
      ["1955-04-01", "Ganadores · Final", "lanus", 2, 1, "tigre", at("San Lorenzo")],
      ["1955-04-03", "Perdedores · Segunda ronda", "chacarita", 4, 4, "racing", { advancedId: "racing", note: "Con alargue. Pasó Racing por córners (2-1)." }],
      ["1955-04-03", "Perdedores · Segunda ronda", "banfield", 2, 3, "estudiantes", away(EP_EST.as)],
      ["1955-04-17", "Perdedores · Semifinal", "racing", 1, 2, "tigre"],
      ["1955-04-21", "Perdedores · Final", "tigre", 0, 4, "estudiantes", { ...away(EP_EST.as), ...at("Racing Club") }],
      ["1955-04-24", "Final", "lanus", 2, 1, "estudiantes", { ...away(EP_EST.as), ...at("Racing Club") }],
    ]),
    summary: "Lanús ganó la Copa Perón: 2-1 a Estudiantes de Eva Perón (La Plata) en la final. En 2024 la AFA la reconoció como título oficial de Primera.",
    notes: [
      { kind: "formato", text: "Siete equipos de la provincia de Buenos Aires, con doble eliminación: cuadro de ganadores y cuadro de perdedores. La final fue entre los ganadores de los dos cuadros." },
      { kind: "identidad", text: "La organizó el gobierno de la provincia como torneo amistoso; el 31 de octubre de 2024 la AFA la reconoció como copa oficial de Primera." },
      { kind: "fuentes", text: "La página de RSSSF no da la cancha de todos los partidos." },
    ],
  },

  // ───────── Copa Suecia 1958 ─────────
  {
    slug: "copa-suecia-1958",
    kind: "cup",
    year: 1958,
    file: "arg-suecia58.html",
    wiki: "Copa Suecia",
    competition: "Copa Suecia",
    title: "Copa Suecia 1958",
    tournament: "Copa Suecia",
    organizer: AFA,
    championIds: ["atlanta"],
    runnerUpIds: ["racing"],
    aliases: { "Central Córdoba (R)": "central-cordoba-rosario", "Central Córdoba": "central-cordoba-rosario" },
    groupTables: [
      { table: 3, stage: "^Grupo A · " },
      { table: 4, stage: "^Grupo B · " },
    ],
    summary: "Atlanta ganó la Copa Suecia, jugada durante el Mundial de Suecia: 3-1 a Racing Club en la final.",
    notes: [
      {
        kind: "formato",
        text: "Los 16 equipos de Primera en dos grupos de 8, todos contra todos a dos ruedas, 2 puntos por victoria. Los ganadores de los grupos jugaron la final. En el grupo B, Atlanta y Rosario Central empataron el primer puesto y jugaron un desempate.",
      },
      { kind: "dato", text: "Se jugó mientras la selección estaba en el Mundial de Suecia y se estiró hasta enero de 1959. Tigre–Newell's (grupo A) no se jugó." },
    ],
  },
];
