// Copa Argentina (2011/12–): la copa nacional con clubes de todas las categorías. RSSSF la publica dentro de la
// página de cada temporada (arg20XX.html). La fase de cada partido sale de los títulos de la página (contextStages).
import type { TournamentConfig } from "./config";
import { A_COPA_2020 } from "./config";

const AFA = "Asociación del Fútbol Argentino";

// Nombres de RSSSF en la Copa Argentina. Van como alias del torneo: "CA Estudiantes" acá es Estudiantes de Buenos
// Aires (el de La Plata figura "Club Estudiantes de La Plata") y "CA Racing" es Racing de Córdoba.
const { Estudiantes: _lp, ...BASE } = A_COPA_2020;
export const A_CA: Record<string, string> = {
  ...BASE,
  "CA Estudiantes": "estudiantes-ba",
  "Club Atlético Estudiantes": "estudiantes-ba",
  "CA Racing": "racing-cordoba",
  "Club Atlético Racing Soc. Civil": "racing-cordoba",
  "CA Huracán (Parque Patricios)": "huracan",
  "CA Talleres (R. de Escalada)": "talleres-re",
  "CA Talleres (Remedios Escalada)": "talleres-re",
  "CA Central Córdoba (ROS)": "central-cordoba-rosario",
  "CA Central Córdoba (Santiago dE)": "central-cordoba-sde",
  "CA San Martín (SM de Tucumán)": "san-martin-tucuman",
  "CA San Martín (San Juan)": "san-martin-sj",
  "Club Atlético San Martín Sociedad Civil": "san-martin-tucuman",
  "CA Patronato dlJC": "patronato-parana",
  "CA Gimnasia y Esgrima (SS Jujuy)": "gimnasia-jujuy",
  "CA Gimnasia y Esgrima (SSJ)": "gimnasia-jujuy",
  "CSD Gimnasia y Esgrima Chivilcoy": "gimnasia-chivilcoy",
  "Gimnasia y Esgrima FBC": "gimnasia-cdu",
  "Club de Gimnasia y Tiro AC": "gimnasia-tiro-salta",
  "Cd Gimnasia y Tiro": "gimnasia-tiro-salta",
  "Atlético Club San Martín": "san-martin-mendoza",
  "C. y Biblioteca Ramón Santamarina": "ramon-santamarina",
  "CB Ramón Santamarina": "ramon-santamarina",
  "Instituto Atl. Central Córdoba": "instituto",
  "Instituto A. Central Córdoba": "instituto",
  "Centro Juventud Antoniana": "juventud-antoniana",
  "Club Juventud Unida Universitario": "juventud-unida-sl",
  "Club Sportivo Estudiantes": "sportivo-estudiantes-sl",
  "CS Estudiantes": "sportivo-estudiantes-sl",
  "Club Sportivo General San Martín": "general-san-martin-formosa",
  "CS General San Martín": "general-san-martin-formosa",
  "Club Sportivo Alfredo Guzmán": "sportivo-guzman",
  "Club Villa Mitre": "villa-mitre",
  "CA Güemes": "guemes-sde",
  "Club Atlético Güemes": "guemes-sde",
  "CA Belgrano (Paraná)": "belgrano-parana",
  "CA Mitre": "mitre-sde",
  "CA Mitre (Santiago del Estero)": "mitre-sde",
  "CA Mitre (Salta)": "mitre-salta",
  "CA Sarmiento (Resistencia)": "sarmiento-resistencia",
  "CA Sarmiento (La Banda)": "sarmiento-la-banda",
  "CS Belgrano (San Francisco)": "sportivo-belgrano-sf",
  "CS Belgrano": "sportivo-belgrano-sf",
  "CS Desamparados": "desamparados",
  "CS Patria": "sportivo-patria",
  "CSB Atenas": "sportivo-atenas",
  "S. Ferroviario": "ferroviarios-corrientes",
  "CA Defensores Unidos": "defensores-unidos-zarate",
  "CD Armenio": "deportivo-armenio",
  "CD Morón": "deportivo-moron",
  "C. Sportivo Barracas (Barracas)": "sportivo-barracas",
  "Club Defensores de Cambaceres": "defensores-cambaceres",
  "ACSyD Sol de Mayo": "sol-de-mayo-viedma",
  "ACSD Sol de Mayo": "sol-de-mayo-viedma",
  "ACyD Altos Hornos Zapla": "altos-hornos-zapla",
  "ACD Altos Hornos Zapla": "altos-hornos-zapla",
  "AMSD Atlético de Rafaela": "atletico-rafaela",
  // Clubes nuevos (lib/data/clubs.ts, sección Copa Argentina).
  "CA Acassuso": "acassuso",
  "CSD Achirense": "achirense",
  "CSyD Achirense": "achirense",
  "Club Agropecuario Argentino": "agropecuario",
  "CA Argentino de Merlo": "argentino-merlo",
  "CA Paraná": "atletico-parana",
  "Club Atlético Paraná": "atletico-parana",
  "C. Belgrano de San Nicolás": "belgrano-san-nicolas",
  "CS Ben Hur": "ben-hur",
  "AD Berazategui": "berazategui",
  "C. Sportivo Bernardino Rivadavia": "bernardino-rivadavia",
  "CA Boca Unidos": "boca-unidos",
  "CA Brown": "brown-adrogue",
  "Club Atlético Brown": "brown-adrogue",
  "CASyD Camioneros": "camioneros",
  "CASD Camioneros": "camioneros",
  "Cañuelas FC": "canuelas",
  "CSyD Central Ballester": "central-ballester",
  "Club Ciudad de Bolívar": "ciudad-bolivar",
  "CA Claypole": "claypole",
  "C. Comercio Central Unidos": "comercio-central-unidos",
  "Club Comunicaciones": "comunicaciones",
  "CSyDD de Pronunciamiento": "defensores-pronunciamiento",
  "CSy Dep. Def. de Pronunciamiento": "defensores-pronunciamiento",
  "Defensores de Pronunciamiento": "defensores-pronunciamiento",
  "CAyS Defensores de Belgrano": "defensores-villa-ramallo",
  "CAy Social Defensores de Belgrano": "defensores-villa-ramallo",
  "CAS Defensores de Belgrano": "defensores-villa-ramallo",
  "CSyD Madryn": "deportivo-madryn",
  "CSD Madryn": "deportivo-madryn",
  "CS Deportivo Madryn": "deportivo-madryn",
  "Club Social y Deportivo Madryn": "deportivo-madryn",
  "CD Maipú": "deportivo-maipu",
  "CD Rincón": "deportivo-rincon",
  "CD Rincón (Rincón de los Sauces)": "deportivo-rincon",
  "CA Douglas Haig": "douglas-haig",
  "Club Atlético Douglas Haig": "douglas-haig",
  "CSyD Flandria": "flandria",
  "CA General Lamadrid": "general-lamadrid",
  "CSyD General Roca": "deportivo-roca",
  "CSA Guillermo Brown": "guillermo-brown",
  "CSyA Guillermo Brown": "guillermo-brown",
  "CA Independiente (Chivilcoy)": "independiente-chivilcoy",
  "CA Independiente (CVY)": "independiente-chivilcoy",
  "CA Independiente del Neuquén": "independiente-neuquen",
  "CA Ituzaingó": "ituzaingo",
  "ASyD Justo J. de Urquiza": "justo-jose-urquiza",
  "CD Juventud Unida": "juventud-unida-gualeguaychu",
  "Club Deportivo Juventud Unida": "juventud-unida-gualeguaychu",
  "Club Social y Deportivo La Emilia": "la-emilia",
  "CSCyD Laferrere": "laferrere",
  "CS y Cultural Deportivo Laferrere": "laferrere",
  "CA Laguna Blanca": "laguna-blanca",
  "CDM Leandro N. Alem": "leandro-n-alem",
  "Club Luján": "lujan",
  "CA Ferrocarril Midland": "midland",
  "SC Pacífico de General Alvear": "pacifico-general-alvear",
  "CA Puerto Nuevo": "puerto-nuevo",
  "Real Pilar FC": "real-pilar",
  "Club Rivadavia": "rivadavia-lincoln",
  "Sacachispas FC": "sacachispas",
  "CSyD San Jorge Juniors": "san-jorge-tucuman",
  "CA San Lorenzo de Alem": "san-lorenzo-alem",
  "Club Atlético San Lorenzo de Alem": "san-lorenzo-alem",
  "CA San Miguel": "san-miguel",
  "CA Sansinena SyD": "sansinena",
  "CA Sansinena SD": "sansinena",
  "CA Sansinena Social y Deportivo": "sansinena",
  "CSyS Sol de América": "sol-de-america-formosa",
  "C. Sportivo Barracas (Colón)": "sportivo-barracas-colon",
  "Sportivo AC": "sportivo-las-parejas",
  "Sportivo Atlético Club": "sportivo-las-parejas",
  "C. Sportivo Peñarol": "sportivo-penarol",
  "CA Talleres (Perico)": "talleres-perico",
  "CSD Textil Mandiyú": "textil-mandiyu",
  "Tiro Federal y Deportivo Morteros": "tiro-federal-morteros",
  "Club Tristán Suárez": "tristan-suarez",
  "Club Deportivo UAI Urquiza": "uai-urquiza",
  "Club Unión Aconquija": "union-aconquija",
  "C. Unión Aconquija": "union-aconquija",
  "Club Atlético Unión Santiago": "union-santiago",
  "CA Unión (Sunchales)": "union-sunchales",
  "Club Atlético Unión (Sunchales)": "union-sunchales",
  "CA Victoriano Arenas": "victoriano-arenas",
  "Club Villa Dálmine": "villa-dalmine",
  "CA Villa San Carlos": "villa-san-carlos",
  "CSyD Yupanqui": "yupanqui",
  "AA Estudiantes": "estudiantes-rio-cuarto",
  "CA Gimnasia y Esgrima": "gimnasia-mendoza",
  // Nombres completos de las tablas de RSSSF (2018/19–).
  "Asociación Atlética Estudiantes": "estudiantes-rio-cuarto",
  "Club Atlético Gimnasia y Esgrima": "gimnasia-mendoza",
  "Club Atlético Mitre": "mitre-sde",
  "Club Sportivo Belgrano": "sportivo-belgrano-sf",
  "Club Social y Deportivo General Roca": "deportivo-roca",
  "Deportivo Roca": "deportivo-roca",
  "Club Atlético Boca Unidos": "boca-unidos",
  "Real Pilar Fútbol Club Asociación Civil": "real-pilar",
  "Club de Gimnasia y Tiro Asociación Civil": "gimnasia-tiro-salta",
  "Asociación Cultural y Deportiva Altos Hornos Zapla": "altos-hornos-zapla",
  "Asociación Club Social y Deportivo Sol de Mayo": "sol-de-mayo-viedma",
  "Club Deportivo Maipú": "deportivo-maipu",
  "Club Atlético y Social Defensores de Belgrano": "defensores-villa-ramallo",
  "Club Social y Deportivo San Jorge Juniors Asociación Civil": "san-jorge-tucuman",
  "Gimnasia y Esgrima Foot Ball Club": "gimnasia-cdu",
  "Asociación Civil Club Atlético Social y Deportivo Camioneros": "camioneros",
  "Club A. Sansinena Social y Deportivo": "sansinena",
  "Club Atlético Independiente del Neuquén": "independiente-neuquen",
  "Asociación Civil Deportivo Armenio": "deportivo-armenio",
  "Club Atlético Ferrocarril Midland": "midland",
  "Club Atlético Acassuso": "acassuso",
  "Club Atlético Argentino de Merlo Asociación Civil": "argentino-merlo",
  "Club Cipolletti Asociación Civil sin Fines de Lucro": "cipolletti",
  "Club Social y Cultural Deportivo Laferrere": "laferrere",
  "Club Social y Deportivo Defensores de Pronunciamiento": "defensores-pronunciamiento",
  "Club Agropecuario Argentino Asociación Civil": "agropecuario",
  "Club Atlético Huracán Las Heras": "huracan-las-heras",
  // Nombres de Wikipedia.
  "Juventud Unida (G)": "juventud-unida-gualeguaychu",
  "Douglas Haig": "douglas-haig",
  "Real Pilar": "real-pilar",
  "Villa Dálmine": "villa-dalmine",
  "Deportivo Laferrere": "laferrere",
  "Mitre (SdE)": "mitre-sde",
  "Argentino de Merlo": "argentino-merlo",
  "Ferrocarril Midland": "midland",
  "Acassuso": "acassuso",
  "Unión (S)": "union-sunchales",
  "Sarmiento (R)": "sarmiento-resistencia",
  "Sportivo Estudiantes (SL)": "sportivo-estudiantes-sl",
  "Villa Mitre": "villa-mitre",
  "Sol de Mayo": "sol-de-mayo-viedma",
  "Estudiantes (RC)": "estudiantes-rio-cuarto",
  "Estudiantes (BA)": "estudiantes-ba",
  "Gimnasia y Esgrima (M)": "gimnasia-mendoza",
  "Gimnasia y Tiro (S)": "gimnasia-tiro-salta",
  "Independiente (N)": "independiente-neuquen",
  "Deportivo Madryn": "deportivo-madryn",
  "Atlético Paraná": "atletico-parana",
  "Sportivo Las Parejas": "sportivo-las-parejas",
  "Sportivo Belgrano": "sportivo-belgrano-sf",
  "San Martín (F)": "general-san-martin-formosa",
  "Sansinena": "sansinena",
  "Deportivo Maipú": "deportivo-maipu",
  "San Jorge (T)": "san-jorge-tucuman",
  "Deportivo Camioneros": "camioneros",
  "Gimnasia y Esgrima (CdU)": "gimnasia-cdu",
  "Defensores de Belgrano (VR)": "defensores-villa-ramallo",
  "Desamparados": "desamparados",
  "Boca Unidos": "boca-unidos",
  "Agropecuario": "agropecuario",
  "San Lorenzo de Alem": "san-lorenzo-alem",
  "Juventud Unida Universitario": "juventud-unida-sl",
  // "CA Ferro Carril Oeste" en la Copa Argentina es el de General Pico (el de Caballito es "Club Ferro Carril Oeste").
  "CA Ferro Carril Oeste": "ferro-general-pico",
  "Club Atlético Ferro Carril Oeste": "ferro-general-pico",
  "Ferro Carril Oeste (GP)": "ferro-general-pico",
  // 2019/20–2026.
  "CS Peñarol": "sportivo-penarol",
  "Club Sportivo Peñarol": "sportivo-penarol",
  "Sportivo Peñarol (C)": "sportivo-penarol",
  "CA Central Norte": "central-norte-salta",
  "Central Norte (S)": "central-norte-salta",
  "Club Atlético Villa San Carlos y Biblioteca Popular Mariano Moreno": "villa-san-carlos",
  "Club Atlético Claypole": "claypole",
  "Club Atlético San Martín S. Civil": "san-martin-tucuman",
  "CA San Martín (SMC)": "san-martin-tucuman",
  "CA San Martín (UAQ)": "san-martin-sj",
  "CA Talleres (COR)": "talleres",
  "Cañuelas Fútbol Club": "canuelas",
  "Asoc. Social y Deportiva Justo J. de Urquiza": "justo-jose-urquiza",
  "J.J. de Urquiza": "justo-jose-urquiza",
  "J. J. de Urquiza": "justo-jose-urquiza",
  "Güemes (SdE)": "guemes-sde",
  "Sportivo Belgrano (SF)": "sportivo-belgrano-sf",
  "Cañuelas": "canuelas",
  "Claypole": "claypole",
  "Comunicaciones": "comunicaciones",
  "Villa San Carlos": "villa-san-carlos",
  "Cipoletti": "cipolletti",
  "Defensores de Cambaceres": "defensores-cambaceres",
  "Club Social Cultural Deportivo Centro de Fomento y Biblioteca Popular Gral J. de San Martín Defensores de Cambaceres": "defensores-cambaceres",
  "Puerto Nuevo": "puerto-nuevo",
  "Club Atlético Puerto Nuevo": "puerto-nuevo",
  "Sacachispas": "sacachispas",
  "Sacachispas Fútbol Club": "sacachispas",
  "Brown de Adrogué": "brown-adrogue",
  "Flandria": "flandria",
  "Club Social y Dep. Flandria": "flandria",
  "Ituzaingó": "ituzaingo",
  "Club Atlético Ituzaingó Asociación Civil": "ituzaingo",
  "Tristán Suárez": "tristan-suarez",
  "CSyD Liniers": "liniers-san-justo",
  "Club Social y Deportivo Liniers": "liniers-san-justo",
  "Liniers (SJ)": "liniers-san-justo",
  "Independiente (C)": "independiente-chivilcoy",
  "Centro Español": "centro-espanol",
  "CSyR Español": "centro-espanol",
  "Centro Social y Recreativo Español": "centro-espanol",
  "Club Social, Deportivo y Cultural Español de la República Argentina Asociación Civil": "deportivo-espanol",
  "Ciudad de Bolívar": "ciudad-bolivar",
  "Defensores Unidos": "defensores-unidos-zarate",
  "Club Atlético Defensores Unidos": "defensores-unidos-zarate",
  "Yupanqui": "yupanqui",
  "Club Social y Deportivo Yupanqui": "yupanqui",
  "Argentino (MM)": "argentino-monte-maiz",
  "CD Argentino": "argentino-monte-maiz",
  "Club Deportivo Argentino": "argentino-monte-maiz",
  "San Martín (B)": "san-martin-burzaco",
  "CSyD San Martín": "san-martin-burzaco",
  "Club Social y Deportivo San Martín": "san-martin-burzaco",
  "San Miguel": "san-miguel",
  "Club Atlético San Miguel": "san-miguel",
  "General Lamadrid": "general-lamadrid",
  "Club Atlétiico General Lamadrid": "general-lamadrid",
  "Sarmiento (LB)": "sarmiento-la-banda",
  "Berazategui": "berazategui",
  "Asociación Deportiva Berazategui": "berazategui",
  "Club y Biblioteca Ramón Santamarina": "ramon-santamarina",
  "Gimnasia y Esgrima (C)": "gimnasia-chivilcoy",
  "Club Social y Deportivo Gimnasia y Esgrima de Chivilcoy": "gimnasia-chivilcoy",
  "Deportivo Rincón": "deportivo-rincon",
  "Asociación Civil Club Deportivo Rincón": "deportivo-rincon",
  "Atenas (RC)": "sportivo-atenas",
  "Liniers": "liniers-san-justo",
  // 2015/16–2017/18.
  "CA Colón Junior": "colon-juniors-sj",
  "Colón Juniors": "colon-juniors-sj",
  "CA Argentinos": "argentinos-25-mayo",
  "Argentinos (VdM)": "argentinos-25-mayo",
  "CA Huracán (Comodoro Rivadavia)": "huracan-comodoro",
  "Jorge Newbery (CR)": "jorge-newbery-cr",
  "Huracán (SR)": "huracan-san-rafael",
  "Racing AC": "racing-olavarria",
  "Racing Atletic Club": "racing-olavarria",
  "Racing (O)": "racing-olavarria",
  "FC Ferro Carril Sud": "ferro-sud-olavarria",
  "Ferro Carril Sud (O)": "ferro-sud-olavarria",
  "CAAByM Sarmiento": "sarmiento-leones",
  "Sarmiento (L)": "sarmiento-leones",
  "CA Pellegrini": "pellegrini-salta",
  "Club Atlético Pellegrini": "pellegrini-salta",
  "Atlético Pellegrini": "pellegrini-salta",
  "CA Unión Rawson": "union-villa-krause",
  "Unión (VK)": "union-villa-krause",
  "C. Bella Vista": "bella-vista-bahia-blanca",
  "Bella Vista (BB)": "bella-vista-bahia-blanca",
  "CA San Jorge MyS": "san-jorge-santa-fe",
  "San Jorge (SF)": "san-jorge-santa-fe",
  "Unión Aconquija": "union-aconquija",
  "La Emilia": "la-emilia",
  "Unión Santiago": "union-santiago",
  "Sportivo Rivadavia (VT)": "bernardino-rivadavia",
  "Güemes": "guemes-sde",
  "Comercio Central Unidos": "comercio-central-unidos",
  "Tiro Federal (M)": "tiro-federal-morteros",
  "Pacífico": "pacifico-general-alvear",
  "Atlético Camioneros": "camioneros",
  "Sportivo Barracas (C)": "sportivo-barracas-colon",
  "Belgrano (SN)": "belgrano-san-nicolas",
  "Rivadavia (L)": "rivadavia-lincoln",
  "Deportivo Achirense": "achirense",
  "Sol de América (F)": "sol-de-america-formosa",
  "Sol de Mayo (V)": "sol-de-mayo-viedma",
  "Luján": "lujan",
  "UAI Urquiza": "uai-urquiza",
  "Guillermo Brown": "guillermo-brown",
  "Central Ballester": "central-ballester",
  "Victoriano Arenas": "victoriano-arenas",
  "Midland": "midland",
  "Leandro N. Alem": "leandro-n-alem",
  "CA Tiro Federal Argentino": "tiro-federal-rosario",
  "Tiro Federal (R)": "tiro-federal-rosario",
  "Belgrano (P)": "belgrano-parana",
  "Ben Hur": "ben-hur",
  "Mitre (S)": "mitre-salta",
  "Almirante Brown (L)": "almirante-brown-lules",
  "Talleres (P)": "talleres-perico",
  "Atlético Laguna Blanca": "laguna-blanca",
  "Ferroviario (C)": "ferroviarios-corrientes",
  "Textil Mandiyú": "textil-mandiyu",
  "Sportivo Rivadavia": "bernardino-rivadavia",
  "Club Atlético Germinal": "germinal-rawson",
  "Germinal": "germinal-rawson",
  "CA Germinal": "germinal-rawson",
  // 2014/15 (más nombres de Wikipedia).
  "Ferrocarril Roca (LF)": "ferrocarril-nacional-las-flores",
  "Sportivo Baradero": "baradero",
  "Social Obrero": "obrero-zarate",
  "Huracán (G)": "huracan-goya",
  "Juventud Unida (C)": "juventud-unida-charata",
  "Comercio (SS)": "comercio-santa-sylvina",
  "Independiente (Fo)": "independiente-formosa",
  "Sportivo (PRSP)": "sportivo-saenz-pena",
  "Ocampo Fábrica": "ocampo-villa-ocampo",
  "San Carlos (LE)": "san-carlos-la-escondida",
  "Sportivo Tintina": "tintina",
  "Talleres (F)": "talleres-frias",
  "Pacífico (GA)": "pacifico-general-alvear",
  "Puerto General San Martín": "puerto-san-martin",
  "Atlético Lugano": "lugano",
  // 2014/15 (nombres de Wikipedia).
  "General Belgrano (SR)": "general-belgrano-santa-rosa",
  "Independiente (Ch)": "independiente-chivilcoy",
  "Américo Tesorieri (LR)": "americo-tesorieri-la-rioja",
  "Ferro Sud (O)": "ferro-sud-olavarria",
  "La Salle Jobson": "la-salle-jobson",
  "Atlético Pellegrini (S)": "pellegrini-salta",
  "Río Grande": "tiro-rio-grande",
  "Independiente (HY)": "independiente-hipolito-yrigoyen",
  "Vélez Sarsfield (SR)": "velez-san-ramon",
  "Independiente (Fe)": "independiente-fernandez",
  "Bella Vista (T)": "bella-vista-tucuman",
  "Sportivo Peñarol (Ch)": "sportivo-penarol",
  "CEC": "empleados-comercio-mendoza",
  "Sportivo Balloffet": "balloffet",
  "Libertad (C)": "libertad-concordia",
  "Cruz de Sur (B)": "cruz-del-sur-bariloche",
  "Boxing Club": "boxing-rio-gallegos",
  "Defensores (VdM)": "defensores-valeria-del-mar",
  "Bragado Club": "bragado",
  "Sarmiento (CS)": "sarmiento-coronel-suarez",
  "Luján SC": "lujan-sport-club",
  "Everton": "everton-la-plata",
  // 2014/15 (nombres oficiales abreviados de RSSSF, con la ciudad que da la página).
  "A. Atlética Argentinos Juniors": "argentinos",
  "A. Civil Club Atlético Amalia": "atletico-amalia",
  "A. Civil Club Deportivo Comercio": "comercio-santa-sylvina",
  "A. Civil Club General Belgrano": "general-belgrano-santa-rosa",
  "A. Civil Club Sportivo Italiano": "deportivo-italiano",
  "A. Civil Deportivo Armenio": "deportivo-armenio",
  "A. Ex Alumnos Esc. Nac. N° 185": "ex-alumnos-185",
  "A. de Tiro y Deportes Río Grande": "tiro-rio-grande",
  "AC Club Deportivo Cruz del Sur": "cruz-del-sur-bariloche",
  "AC y Deportiva Altos Hornos Zapla": "altos-hornos-zapla",
  "ACCAS y Deportivo Camioneros": "camioneros",
  "AD Social y Cultural 25 de Mayo": "deportivo-25-mayo-lp",
  "AD, Social y Cultural 25 de Mayo": "deportivo-25-mayo-lp",
  "ASy Deportiva Justo J. de Urquiza": "justo-jose-urquiza",
  "Asociación Atlético Boxing Club": "boxing-rio-gallegos",
  "Bragado Club y Biblioteca Pública": "bragado",
  "C. Atlético Argentino de Merlo AC": "argentino-merlo",
  "C. Atlético Argentino de Quilmes": "argentino-quilmes",
  "C. Deportivo y Social Guaymallén": "deportivo-guaymallen",
  "C. Social y Recreativo Español": "centro-espanol",
  "CA Independiente de H. Yrigoyen": "independiente-hipolito-yrigoyen",
  "CA Independiente del B. Fontana": "independiente-formosa",
  "CA Sarmiento Cultural Social y D.": "sarmiento-ayacucho",
  "CA Villa San Carlos y BPMM": "villa-san-carlos",
  "CAA Biblioteca y Mutual Sarmiento": "sarmiento-leones",
  "CC Social y Deportivo América": "america-general-piran",
  "CCyD Ingeniero Herminio Arrieta": "herminio-arrieta",
  "CD y Mutual Leandro N. Alem": "leandro-n-alem",
  "CD y Social Juventud Unida": "juventud-unida-san-miguel",
  "CS Cultural Atlético Progreso": "progreso-salta",
  "CS Cultural y Deportivo Belgrano": "belgrano-esquel",
  "CS Deportivo y C. Español dlRAAC": "deportivo-espanol",
  "CS y Atlético Guillermo Brown": "guillermo-brown",
  "CS y Deportivo General Roca": "deportivo-roca",
  "CS y Social Sol de América": "sol-de-america-formosa",
  "CSCDCdFyBPGJdSMD de Cambaceres": "defensores-cambaceres",
  "CSD Defensores de Valeria del Mar": "defensores-valeria-del-mar",
  "CSy Deportivo Petrolero Argentino": "petrolero-argentino",
  "CSyD Ferrocarril N. General Roca": "ferrocarril-nacional-las-flores",
  "CSyD Tristán Suárez y BPDFS": "tristan-suarez",
  "Cd Actividades Infantiles AMSyD": "cai",
  "Centro Deportivo Sarmiento": "sarmiento-coronel-suarez",
  "Club Atlético Chicoana": "chicoana",
  "Club Atlético Colón Junior": "colon-juniors-sj",
  "Club Atlético Concepción": "atletico-concepcion",
  "Club Atlético Juventud": "juventud-pergamino",
  "Club Atlético Libertad": "libertad-concordia",
  "Club Atlético Ocampo Fábrica": "ocampo-villa-ocampo",
  "Club Atlético Palmira": "palmira-mendoza",
  "Club Atlético Policial": "policial-catamarca",
  "Club Atlético San Jorge MyS": "san-jorge-santa-fe",
  "Club Atlético Sarmiento CSyD": "sarmiento-ayacucho",
  "Club Atlético Sportivo": "sportivo-saenz-pena",
  "Club Deportivo Social Obrero": "obrero-zarate",
  "Club Everton y Biblioteca PMLS": "everton-la-plata",
  "Club San Carlos": "san-carlos-la-escondida",
  "Club Social y Deportivo Achirense": "achirense",
  "Club Social y Deportivo Merlo AC": "deportivo-merlo",
  "Club Sportivo Balloffet": "balloffet",
  "Club Sportivo Baradero": "baradero",
  "Club Sportivo Bella Vista": "bella-vista-tucuman",
  "Club Sportivo Ben Hur": "ben-hur",
  "Club Sportivo Tintina": "tintina",
  "Club del Colegio La Salle Jobson": "la-salle-jobson",
  "Deportivo Riestra AdFB Colón": "deportivo-riestra",
  "Fútbol Club Ferro Carril Sud": "ferro-sud-olavarria",
  "General Rojo Unión Deportiva": "general-rojo",
  "Instituto Atlético Ctral. Córdoba": "instituto",
  "Luján Sport Club": "lujan-sport-club",
  "Puerto San Martín Fútbol": "puerto-san-martin",
  "Sd Tiro y Gimnasia de San PdJ": "tiro-gimnasia-san-pedro",
  // 2013/14 (segunda tanda).
  "Argentinos (25 de Mayo)": "argentinos-25-mayo",
  "Atlético Racing (Córdoba)": "racing-cordoba",
  "Belgrano (Esquel)": "belgrano-esquel",
  "Belgrano (E)": "belgrano-esquel",
  "Belgrano (Zárate)": "belgrano-zarate",
  "Belgrano (Z)": "belgrano-zarate",
  "Estudiantes (San Luis)": "sportivo-estudiantes-sl",
  "Ferro Carril Oeste (Buenos Aiers)": "ferro",
  "Ferro Carril Oeste (Buenos Aires)": "ferro",
  "Ferro Carril Oeste (General Pico)": "ferro-general-pico",
  "Ferrocarril Sud": "ferro-sud-olavarria",
  "Independiente del Barrio Fontana": "independiente-formosa",
  "Independiente (F)": "independiente-formosa",
  "Juventud Unida (San Miguel)": "juventud-unida-san-miguel",
  "Liniers (San Justo)": "liniers-san-justo",
  "Racing Athletic Club (Olavarría)": "racing-olavarria",
  "Sarmiento (Leones]": "sarmiento-leones",
  "Sarmiento (Santiago del Estero)": "sarmiento-la-banda",
  "Sportivo Barracas (Colón)": "sportivo-barracas-colon",
  "Tiro Federal (Bahía Blanca)": "tiro-federal-bahia-blanca",
  "Unión Güemes": "union-guemes",
  "Güemes (S)": "union-guemes",
  "Jorge Newbery (J)": "jorge-newbery-junin",
  "Deportivo Fontana (R)": "deportivo-fontana",
  "Deportivo Guaymallén": "deportivo-guaymallen",
  "Juventud Unida U.": "juventud-unida-sl",
  "Independiente Riv.": "independiente-rivadavia",
  // 2013/14 (nombres de RSSSF y de Wikipedia).
  "Villa Congreso": "villa-congreso-viedma",
  "Independiente (Río Colorado)": "deportivo-independiente-rio-colorado",
  "Defensores de Buena Parada": "defensores-buena-parada",
  "Sportivo (Las Parejas)": "sportivo-las-parejas",
  "25 de Mayo (Veinticinco de Mayo)": "deportivo-25-mayo-lp",
  "Deportivo 25 de Mayo (LP)": "deportivo-25-mayo-lp",
  "Petrolero Argentino": "petrolero-argentino",
  "Aprendices Casildenses": "aprendices-casildenses",
  "Coronel Aguirre": "coronel-aguirre",
  "Atlético Amalia": "atletico-amalia",
  "Social y Deportivo Lastenia": "lastenia",
  "Deportivo Lastenia": "lastenia",
  "Atlético Chicoana": "chicoana",
  "Atlético Progreso": "progreso-salta",
  "Progreso (RdlF)": "progreso-salta",
  "Atlético Las Palmas": "las-palmas-cordoba",
  "Las Palmas": "las-palmas-cordoba",
  "Argentino Peñarol": "argentino-penarol",
  "Atlético Adelante Reconquista": "atletico-adelante",
  "Atlético Adelante": "atletico-adelante",
  "Petrolero Austral": "petrolero-austral",
  "Camioneros Argentinos del Norte": "camioneros-norte",
  "Libertad (Campo Santo)": "libertad-campo-santo",
  "Libertad (CS)": "libertad-campo-santo",
  "Central Goya": "central-goya",
  "Ex Alumnos Escuela Nacional 185": "ex-alumnos-185",
  "Ex Alumnos Escuela N°185": "ex-alumnos-185",
  "Exalumnos Escuela N°185": "ex-alumnos-185",
  "Centro de Empleados de Comercio": "empleados-comercio-mendoza",
  "Empleados de Comercio (M)": "empleados-comercio-mendoza",
  "Atlético Argentino (San José)": "argentino-mendoza",
  "Atlético Argentino (M)": "argentino-mendoza",
  "Sports Salto": "sports-salto",
  "Sports": "sports-salto",
  "Deportivo Curupay": "deportivo-curupay",
  "Sportivo Ferroviario": "ferroviarios-corrientes",
  "Círculo Italiano de Villa Regina": "circulo-italiano",
  "Círculo Italiano": "circulo-italiano",
  "Deportivo Río Dorado": "rio-dorado",
  "Deportivo Tabacal": "deportivo-tabacal",
  "Deportivo Tres Algarrobos": "tres-algarrobos",
  "FC Tres Algarrobos": "tres-algarrobos",
  "Estudiantes Unidos": "estudiantes-unidos",
  "Náutico Hacoaj": "nautico-hacoaj",
  "Gutiérrez": "gutierrez-sport-club",
  "Leonardo Murialdo": "leonardo-murialdo",
  "General Rojo": "general-rojo",
  "Independiente (La Rioja)": "independiente-la-rioja",
  "Independiente (LR)": "independiente-la-rioja",
  "Defensores de La Boca": "defensores-la-boca",
  "Defensores de La Boca (LR)": "defensores-la-boca",
  "Instituto Deportivo Santiago": "instituto-santiago",
  "Instituto Santiago": "instituto-santiago",
  "Jorge Roberto Ross": "jorge-ross",
  "Jorge Ross": "jorge-ross",
  "Argentino Quilmes (Rafaela)": "argentino-quilmes-rafaela",
  "Argentino Quilmes (R)": "argentino-quilmes-rafaela",
  "Juventud (Pergamino)": "juventud-pergamino",
  "Juventud (P)": "juventud-pergamino",
  "Resistencia Central": "resistencia-central",
  "San Martín de Monte Comán": "san-martin-monte-coman",
  "San Martín (MC)": "san-martin-monte-coman",
  "Andes Foot Ball Club": "andes-general-alvear",
  "Andes FBC": "andes-general-alvear",
  "Sarmiento (Ayacucho)": "sarmiento-ayacucho",
  "Sarmiento (A)": "sarmiento-ayacucho",
  "América": "america-general-piran",
  "América (GP)": "america-general-piran",
  "Social y Deportivo Montecaseros": "deportivo-montecaseros",
  "Deportivo Montecaseros": "deportivo-montecaseros",
  "Atlético Palmira": "palmira-mendoza",
  "Sociedad de Tiro y Gimnasia": "tiro-gimnasia-san-pedro",
  "Tiro y Gimnasia": "tiro-gimnasia-san-pedro",
  "Centro Herminio Arrieta": "herminio-arrieta",
  "Herminio Arrieta": "herminio-arrieta",
  "Viale Foot Ball Club": "viale",
  "Viale FBC": "viale",
  "Jorge Newbery (Villa Mercedes)": "jorge-newbery-villa-mercedes",
  "Jorge Newbery (VM)": "jorge-newbery-villa-mercedes",
  "Independiente Villa Obrera": "independiente-villa-obrera",
  "Independiente (VO)": "independiente-villa-obrera",
  "Sportivo Juan B. Del Bono": "del-bono",
  "Atenas de Pocito": "atenas-pocito",
  "Atenas (P)": "atenas-pocito",
  "Atlético Mitre (Santiago Estero)": "mitre-sde",
  "Atlético Unión Santiago": "union-santiago",
  "Huracán (Goya)": "huracan-goya",
  "San Martín (San Martín)": "san-martin-mendoza",
  "Sanjustino (San Justo)": "sanjustino",
  "'Sanjustino'": "sanjustino",
  "San Martín (Formosa)": "general-san-martin-formosa",
  "Club Social y Deportivo San Jorge": "san-jorge-tucuman",
  "Defensores de Belgrano (Ramallo)": "defensores-villa-ramallo",
  "Rivadavia": "rivadavia-lincoln",
  "Deportivo Santamarina": "ramon-santamarina",
  "Gimnasia (Concepción del Uruguay)": "gimnasia-cdu",
  "Central Córdoba (Santiago Estero)": "central-cordoba-sde",
  "Sportivo Barracas (Buenos Aires)": "sportivo-barracas",
  "Defensores de Belgrano (B. Aires)": "defensores-belgrano",
  "Mercado Central-Sacachispas": "sacachispas",
  "Estudiantes (Buenos Aires)": "estudiantes-ba",
  "Mercado Central-Sacachipas": "sacachispas",
  "Accasuso": "acassuso",
  "Gimnasia y E. (J)": "gimnasia-jujuy",
  // 2012/13 (homónimos de la lista de participantes y nombres de Wikipedia).
  "Alvear Football Club": "alvear-intendente-alvear",
  "Belgrano (Paraná)": "belgrano-parana",
  "Huracán Football Club": "huracan-goya",
  "Huracán de Goya": "huracan-goya",
  "Independiente (Chivilcoy)": "independiente-chivilcoy",
  "Independiente del Neuquén": "independiente-neuquen",
  "Racing Club de Trelew": "racing-trelew",
  "River Plate - Embarcación": "river-embarcacion",
  "River de Embarcación": "river-embarcacion",
  "Tiro Federal (BB)": "tiro-federal-bahia-blanca",
  "Sportivo Fernández": "sportivo-fernandez",
  "Américo Tesorieri": "americo-tesorieri-la-rioja",
  "Estudiantes (SL)": "sportivo-estudiantes-sl",
  "Alianza de Moldes": "alianza-coronel-moldes",
  "Gutiérrez SC": "gutierrez-sport-club",
  "Andes Talleres": "andes-talleres",
  "Def. de Pronunciamiento": "defensores-pronunciamiento",
  "Comunicaciones (M)": "comunicaciones-mercedes",
  "Rosamonte": "deportivo-rosamonte",
  "Fontana": "deportivo-fontana",
  "Ferro (GP)": "ferro-general-pico",
  "Independiente (RC)": "deportivo-independiente-rio-colorado",
  "Argentino de Rosario": "argentino-rosario",
  "Chacarita": "chacarita",
  "Argentino (Q)": "argentino-quilmes",
  "SC Pacífico": "pacifico-general-alvear",
  // 2012/13 (nombres de la lista de participantes de RSSSF).
  "Sportivo Villa Cubas": "villa-cubas",
  "Unión Rawson": "union-villa-krause",
  "Agropecuario Argentino": "agropecuario",
  "Mercedes": "mercedes",
  "Andino Sport Club": "andino-la-rioja",
  "Atlético Américo Tesorieri": "americo-tesorieri-la-rioja",
  "Asociación Deportiva 9 de Julio": "nueve-de-julio-morteros",
  "Atenas": "sportivo-atenas",
  "Atlético Ferro Carril Oeste": "ferro-general-pico",
  "Atlético Liniers": "liniers-bahia-blanca",
  "Atlético Maronese": "maronese",
  "Sportivo Peñarol": "sportivo-penarol",
  "Club Atlético 9 de Julio": "nueve-de-julio-rafaela",
  "Bella Vista": "bella-vista-bahia-blanca",
  "Sportivo Huracán": "sportivo-huracan-gregores",
  "Club Atlético Gimnasia Esgrima": "gimnasia-mendoza",
  "Comisión Actividades Infantiles": "cai",
  "Social y Deportivo Alianza": "alianza-cutral-co",
  "Deportivo Aguilares": "deportivo-aguilares",
  "Atlético Famaillá": "atletico-famailla",
  "Deportivo General Roca": "deportivo-roca",
  "Deportivo Independiente": "deportivo-independiente-rio-colorado",
  "Textil Madiyú": "textil-mandiyu",
  "Deportivo Patagones": "deportivo-patagones",
  "Aeronáutico Sarmiento": "sarmiento-leones",
  "Gutiérrez Sport Club": "gutierrez-sport-club",
  "Andes Talleres Sport Club": "andes-talleres",
  "Newbery (Comodoro Rivadavia)": "jorge-newbery-cr",
  "Deportivo Rosamonte": "deportivo-rosamonte",
  "Atlético Trinidad": "trinidad-sj",
  "Mitre (Salta)": "mitre-salta",
  "Monterrico San Vicente": "monterrico-san-vicente",
  "Pacífico de General Alvear": "pacifico-general-alvear",
  "Sanjustino": "sanjustino",
  "Sarmiento (La Banda)": "sarmiento-la-banda",
  "Sportivo de Fernández": "sportivo-fernandez",
  "Social y Deportivo Comunicaciones": "comunicaciones-mercedes",
  "Sol de América": "sol-de-america-formosa",
  "Deportivo Fontana": "deportivo-fontana",
  "Sportivo Bernardino Rivadavia": "bernardino-rivadavia",
  "Sportivo Estudiantes": "sportivo-estudiantes-sl",
  "Alianza Coronel Moldes": "alianza-coronel-moldes",
  "Villa Belgrano": "villa-belgrano-junin",
  "Ferro Carril Sud": "ferro-sud-olavarria",
  "Defensores de Salto": "defensores-salto",
  "Social y Deportivo Español": "deportivo-espanol",
  "Social Juventud Unida": "juventud-unida-san-miguel",
  "Mercado Central - Sacachispas FC": "sacachispas",
  "Centro Recreativo Español": "centro-espanol",
  "Social y Deportivo San Martín": "san-martin-burzaco",
  "Social y Deportivo Liniers": "liniers-san-justo",
  "Club Atlético Argentino": "argentino-rosario",
  "Atlético Brown": "brown-adrogue",
  "Colegiales (Florida Oeste)": "colegiales",
  "Los Andes (Lomas de Zamora)": "los-andes",
  "Justo J. de Urquiza": "justo-jose-urquiza",
  "Grupo Universitario de Tandil": "grupo-universitario-tandil",
  "Atlético Alumni": "alumni-villa-maria",
  "Deportivo Libertad": "libertad-sunchales",
  "San Jorge Juniors": "san-jorge-tucuman",
  "Social Defensores de Belgrano": "defensores-villa-ramallo",
  "C. Córdoba (Santiago del Estero)": "central-cordoba-sde",
  "Racing Athletic Club": "racing-olavarria",
  "Patronato de la Juventud Católica": "patronato-parana",
  "Independiente Rivadavia (Mza)": "independiente-rivadavia",
  "Godoy Cruz AT (Mendoza)": "godoy-cruz",
  "Alvear FC (Intendente Alvear)": "alvear-intendente-alvear",
  "Alvear FBC": "alvear-intendente-alvear",
  "Atlético Concepción (Banda del Río Salí)": "atletico-concepcion",
  "Ben Hur (Rafaela)": "ben-hur",
  "Chaco For Ever (Resistencia)": "chaco-for-ever",
  "Guillermo Brown (PM)": "guillermo-brown",
  "Independiente (Tandil)": "independiente-tandil",
  "Independiente (T)": "independiente-tandil",
  "Jorge Newbery (Venado Tuerto)": "jorge-newbery-vt",
  "Jorge Newbery (VT)": "jorge-newbery-vt",
  "Liniers (Bahía Blanca)": "liniers-bahia-blanca",
  "Liniers (BB)": "liniers-bahia-blanca",
  "Sarmiento (Junín]": "sarmiento-junin",
  "Sarmiento (Junín)": "sarmiento-junin",
  "Sarmiento (Leones)": "sarmiento-leones",
  "Sarmiento (Resistencia)": "sarmiento-resistencia",
  "Talleres (Perico)": "talleres-perico",
  "Tiro Federal (Morteros)": "tiro-federal-morteros",
  "9 de Julio (Morteros)": "nueve-de-julio-morteros",
  "9 de Julio (M)": "nueve-de-julio-morteros",
  "9 de Julio (R)": "nueve-de-julio-rafaela",
  "Argentino (R)": "argentino-rosario",
  "Riestra": "deportivo-riestra",
  "Brown (A)": "brown-adrogue",
  "Cambaceres": "defensores-cambaceres",
  "J.J. Urquiza": "justo-jose-urquiza",
  "Laferrere": "laferrere",
  "Boca Río Gallegos": "boca-rio-gallegos",
  "Huracán de Comodoro": "huracan-comodoro",
  "Santamarina": "ramon-santamarina",
  "Def. de Belgrano (VR)": "defensores-villa-ramallo",
  "Atlético San Jorge": "san-jorge-santa-fe",
  "Defensores (P)": "defensores-pronunciamiento",
  "General Paz Juniors": "general-paz-juniors",
  "Juventud Alianza (SJ)": "atletico-juventud-sj",
  "Concepción FC": "concepcion-fc",
  "Sarmiento (SdE)": "sarmiento-la-banda",
  // 2011/12 (nombres cortos de RSSSF y de Wikipedia).
  "Cuervos del fin del mundo (TF)": "cuervos-fin-del-mundo",
  "Cuervos del fin del mundo (Tierra del Fuego)": "cuervos-fin-del-mundo",
  "Los Cuervos del Fin del Mundo": "cuervos-fin-del-mundo",
  "Real Madrid (Río Grande)": "real-madrid-rio-grande",
  "Real Madrid (Río Gallegos)": "real-madrid-rio-grande",
  "Real Madrid (RG)": "real-madrid-rio-grande",
  "CA Riojano (La Rioja)": "riojano",
  "Atlético Riojano": "riojano",
  "Atlético Chilecito": "chilecito",
  "Argentino (Rosario)": "argentino-rosario",
  "Lugano": "lugano",
  "San Martín (Burzaco)": "san-martin-burzaco",
  "Deportivo Muñiz": "deportivo-muniz",
  "Muñiz": "deportivo-muniz",
  "Juventud Unida": "juventud-unida-san-miguel",
  "Juventud Unida (SM)": "juventud-unida-san-miguel",
  "Fenix": "fenix",
  "Fénix": "fenix",
  "Deportivo Paraguayo": "deportivo-paraguayo",
  "J.J.Urquiza": "justo-jose-urquiza",
  "Brown (Adrogué)": "brown-adrogue",
  "Sportivo Italiano": "deportivo-italiano",
  "Leandro N.Alem": "leandro-n-alem",
  "Sp.Gral San Martín (Formosa)": "general-san-martin-formosa",
  "Atlético Trinidad (San Juan)": "trinidad-sj",
  "Trinidad (SJ)": "trinidad-sj",
  "Trinidad": "trinidad-sj",
  "Del Bono (San Juan)": "del-bono",
  "Sportivo Del Bono": "del-bono",
  "Huracán Las Heras (Mendoza)": "huracan-las-heras",
  "Deportivo Guaymallén (Mendoza)": "deportivo-guaymallen",
  "Deportivo Guaymallén (Mza)": "deportivo-guaymallen",
  "Guaymallén": "deportivo-guaymallen",
  "Boca Juniors (Río Gallegos)": "boca-rio-gallegos",
  "Deportivo Madryn (Pto Madryn)": "deportivo-madryn",
  "Cruz del Sur (Ing.Jacobacci)": "cruz-del-sur-bariloche",
  "Cruz del Sur": "cruz-del-sur-bariloche",
  "Maronese (Neuquén)": "maronese",
  "Maronese": "maronese",
  "Villa Mitre (Bahía Blanca)": "villa-mitre",
  "Ramón Santamarina (Tandil)": "ramon-santamarina",
  "Bella Vista (Bahía Blanca)": "bella-vista-bahia-blanca",
  "El Linqueño (Lincoln)": "el-linqueno",
  "El Linqueño": "el-linqueno",
  "Rivadavia (Lincoln)": "rivadavia-lincoln",
  "Douglas Haig (Pergamino)": "douglas-haig",
  "Ferro Carril Sud (Tandil)": "ferro-sud-olavarria",
  "Ferro (O)": "ferro-sud-olavarria",
  "Racing (Olavarría)": "racing-olavarria",
  "Grupo Universitario (Tandil)": "grupo-universitario-tandil",
  "Grupo Universitario": "grupo-universitario-tandil",
  "Once Tigres (9 de Julio)": "once-tigres",
  "Once Tigres": "once-tigres",
  "Juventud Unida (Gualeguaychú)": "juventud-unida-gualeguaychu",
  "Atlético San Jorge (Santa Fe)": "san-jorge-santa-fe",
  "Colegiales (Concordia)": "colegiales-concordia",
  "Colegiales (C)": "colegiales-concordia",
  "Colegiales(C)": "colegiales-concordia",
  "Club Sportivo Las Heras (Concordia)": "las-heras-concordia",
  "Sportivo Las Heras": "las-heras-concordia",
  "Sportivo Patria (Formosa)": "sportivo-patria",
  "Textil Mandiyú (Corrientes)": "textil-mandiyu",
  "Guaraní A.Franco (Posadas)": "guarani-antonio-franco",
  "Jorge Gibson Brown (Posadas)": "gibson-brown",
  "Gibson Brown": "gibson-brown",
  "Jorge Gibson Brown": "gibson-brown",
  "General Paz Juniors (Córdoba)": "general-paz-juniors",
  "Complejo Deportivo Teniente Origone (Justiniano Posse)": "teniente-origone",
  "Complejo Deportivo": "teniente-origone",
  "Atenas (Río IV)": "sportivo-atenas",
  "Juventud Unida (San Luis)": "juventud-unida-sl",
  "Juventud Unida (SL)": "juventud-unida-sl",
  "Alumni (Villa María)": "alumni-villa-maria",
  "Alumni (VM)": "alumni-villa-maria",
  "Atlético Policial (Catamarca)": "policial-catamarca",
  "Atlético Policial": "policial-catamarca",
  "Villa Cubas (Catamarca)": "villa-cubas",
  "Villa Cubas": "villa-cubas",
  "Concepción FC (Tucumán)": "concepcion-fc",
  "Deportivo San Jorge (Tucumán)": "san-jorge-tucuman",
  "Altos Hornos Zapla (Palpalá)": "altos-hornos-zapla",
  "Sarmiento (Sgo del Estero)": "sarmiento-la-banda",
  "Unión (Mar del Plata)": "union-mar-del-plata",
  "Unión (MdP)": "union-mar-del-plata",
  "Libertad (Sunchales)": "libertad-sunchales",
  "Libertad (S)": "libertad-sunchales",
  "Defensores (Pronunciamiento)": "defensores-pronunciamiento",
  "Atl.Juventud Alianza (SJ)": "atletico-juventud-sj",
  "Deportivo Maipú (Mendoza)": "deportivo-maipu",
  "Atlético San Martín (Mendoza)": "san-martin-mendoza",
  "Central Córdoba (Sgo Estero)": "central-cordoba-sde",
  "Mitre (Santiago del Estero)": "mitre-sde",
  "Sportivo Belgrano (SFco)": "sportivo-belgrano-sf",
  "Racing (Trelew)": "racing-trelew",
  "Racing (T)": "racing-trelew",
  "CAI (Comodoro Rivadavia)": "cai",
  "CAI": "cai",
  "Argentino (Merlo)": "argentino-merlo",
  "Argentino (M)": "argentino-merlo",
  "Unión (Villa Krause)": "union-villa-krause",
  "Sportivo Desamparados (SJ)": "desamparados",
  "Boca Unidos (Corrientes)": "boca-unidos",
  "Deportivo Merlo": "deportivo-merlo",
  "Aldosivi (Mar del Palta)": "aldosivi",
  "Jorge Newbery (Comodoro Rivadavia)": "jorge-newbery-cr",
  "Huracán (Comodoro Rivadavia)": "huracan-comodoro",
  "Defensores de Belgrano (Villa Ramallo)": "defensores-villa-ramallo",
  "Unión (Sunchales)": "union-sunchales",
  "La Emilia (San Nicolás)": "la-emilia",
  "Talleres (Córdoba)": "talleres",
  "Racing (Córdoba)": "racing-cordoba",
  "Racing (C)": "racing-cordoba",
  "Tiro Federal (Rosario)": "tiro-federal-rosario",
  "9 de Julio (Rafaela)": "nueve-de-julio-rafaela",
  "Huracán (Tres Arroyos)": "huracan-tres-arroyos",
  "Club Sportivo y Biblioteca Atenas": "sportivo-atenas",
};

const FORMATO_2019 =
  "Copa de todas las categorías del fútbol argentino. Fases preliminares regionales entre clubes del Torneo Federal A (ida y vuelta) y, desde los treintaidosavos, eliminación directa a un partido en cancha neutral, con penales si hay empate.";

const FORMATO_2022 =
  "Copa de todas las categorías del fútbol argentino: los equipos de Primera y los clasificados del Ascenso y del Torneo Federal A juegan desde los treintaidosavos, eliminación directa a un partido en cancha neutral, con penales si hay empate.";

type Rest = Pick<TournamentConfig, "championIds" | "runnerUpIds" | "summary" | "notes" | "headings"> & Partial<TournamentConfig>;
const copaArgentina = (edition: string, year: number, file: string, rest: Rest): TournamentConfig => ({
  slug: `copa-argentina-${edition}`,
  kind: "cup",
  year,
  yearLabel: edition.replace("-", "/"),
  file,
  wiki: `Copa Argentina ${edition.replace("-", "-")}`,
  competition: "Copa Argentina",
  title: `Copa Argentina ${edition.replace("-", "/")}`,
  tournament: `Copa Argentina ${edition.replace("-", "/")}`,
  organizer: AFA,
  section: rest.headings![0],
  contextStages: true,
  pointsPerWin: 3,
  aliases: A_CA,
  ...rest,
});

export const CUP_TOURNAMENTS_ARGENTINA: TournamentConfig[] = [
  copaArgentina("2014-15", 2014, "arg2015.html", {
    championIds: ["boca"],
    runnerUpIds: ["central"],
    headings: [/^Preliminar Phase$/],
    rollingYear: true,
    // La página da debajo de cada partido la ciudad de cada equipo: los nombres genéricos se resuelven con ella.
    cityAliases: {
      "Club Atlético Argentino|San José, M": "argentino-mendoza",
      "Club Atlético Argentino|Rosario, S": "argentino-rosario",
      "Club Atlético Argentinos|25 de Mayo, B": "argentinos-25-mayo",
      "Club Atlético Belgrano|Paraná, E": "belgrano-parana",
      "Club Atlético Belgrano|Córdoba, X": "belgrano",
      "Club Atlético Colegiales|Concordia, E": "colegiales-concordia",
      "Club Atlético Colegiales|Florida Oeste, B": "colegiales",
      "Club Atlético Independiente|Fernández, G": "independiente-fernandez",
      "Club Atlético Independiente|Chivilcoy, B": "independiente-chivilcoy",
      "Club Atlético Independiente|Avellaneda, B": "independiente",
      "Club Atlético Mitre|Salta, A": "mitre-salta",
      "Club Atlético Mitre|Santiago del Estero, G": "mitre-sde",
      "Club Atlético Sarmiento|La Banda, G": "sarmiento-la-banda",
      "Club Atlético Sarmiento|Resistencia, H": "sarmiento-resistencia",
      "Club Atlético Sarmiento|Junín, B": "sarmiento-junin",
      "Club Atlético Talleres|Frías, G": "talleres-frias",
      "Club Atlético Talleres|Perico, Y": "talleres-perico",
      "Club Atlético Talleres|Córdoba, X": "talleres",
      "Club Atlético Talleres|Remedios de Escalada, B": "talleres-re",
      "Club Atlético Unión|Sunchales, S": "union-sunchales",
      "Club Atlético Unión|Mar del Plata, B": "union-mar-del-plata",
      "Club Atlético Unión|Santa Fe, S": "union-santa-fe",
      "Club Jorge Newbery|Junín, B": "jorge-newbery-junin",
      "Club Jorge Newbery|Villa Mercedes, D": "jorge-newbery-villa-mercedes",
      "Club Atlético Liniers|Bahía Blanca, B": "liniers-bahia-blanca",
      "Club Tiro Federal|Bahía Blanca, B": "tiro-federal-bahia-blanca",
      "Club Huracán|San Rafael, M": "huracan-san-rafael",
      "Club Atlético Almirante Brown|Lules, T": "almirante-brown-lules",
      "Club Atlético Vélez Sarsfield|San Ramón, G": "velez-san-ramon",
      "CS y Deportivo Juventud Unida|Charata, H": "juventud-unida-charata",
      "Club Atlético Alumni|Villa María, X": "alumni-villa-maria",
      "Club Atlético Gimnasia y Esgrima|San Salvador de Jujuy, Y": "gimnasia-jujuy",
      "Club Atlético Gimnasia y Esgrima|Mendoza, M": "gimnasia-mendoza",
      "Club Atlético Central Córdoba|Rosario, S": "central-cordoba-rosario",
      "Club Atlético Central Córdoba SC|Santiago del Estero, G": "central-cordoba-sde",
    },
    // RSSSF numera las rondas: la 6 son los treintaidosavos, la 7 los dieciseisavos y la 8 los octavos.
    stageRename: {
      "Ronda 6": "Treintaidosavos de final",
      "Ronda 7": "Dieciseisavos de final",
      "Ronda 8": "Octavos de final",
    },
    overrides: {
      "2014-10-22 cipolletti deportivo-roca": {
        homeGoals: 0,
        awayGoals: 0,
        walkover: true,
        awardedTo: "cipolletti",
        note: "No se jugó: Deportivo Roca no se presentó y el 8 de enero le dieron el partido a Cipolletti.",
      },
    },
    summary: "Boca ganó la Copa Argentina 2014/15, con la que cerró el doblete del año: le ganó 2-0 a Rosario Central una final muy polémica por el arbitraje, en Córdoba.",
    notes: [
      {
        kind: "formato",
        text: "Cinco rondas preliminares por grupos regionales: el A (clubes del Federal A), el B (del Federal B), a cargo del Consejo Federal, y el 1 y el 2 (de la C y la D, y de la B Metropolitana). Desde los treintaidosavos, eliminación directa a un partido en cancha neutral con los equipos de Primera y de la B Nacional.",
      },
      { kind: "dato", text: "En la tercera ronda del grupo B, Sol de Mayo e Independiente de Río Colorado se retiraron y Liniers de Bahía Blanca pasó sin jugar." },
    ],
  }),
  copaArgentina("2013-14", 2013, "arg2014.html", {
    championIds: ["huracan"],
    runnerUpIds: ["central"],
    headings: [],
    sectionRange: { from: /^Preliminar phase$/, to: /^Supercopa Argentina 2014$/ },
    allSections: true,
    rollingYear: true,
    // RSSSF marca estos dos "n/p" (no se presentó un equipo): pasa el otro.
    extraMatches: [
      {
        id: "copa-argentina-2013-14-wo1",
        date: "2013-10-30",
        stage: "Fase preliminar · Regional 1",
        phase: "cup",
        homeId: "estudiantes-unidos",
        awayId: "belgrano-esquel",
        homeGoals: 0,
        awayGoals: 0,
        walkover: true,
        awardedTo: "belgrano-esquel",
        note: "No se jugó: Estudiantes Unidos no se presentó y pasó Belgrano (Esquel).",
      },
      {
        id: "copa-argentina-2013-14-wo2",
        date: "2013-11-13",
        stage: "Fase preliminar · Regional 2",
        phase: "cup",
        homeId: "deportivo-madryn",
        awayId: "belgrano-esquel",
        homeGoals: 0,
        awayGoals: 0,
        walkover: true,
        awardedTo: "deportivo-madryn",
        note: "No se jugó: Belgrano (Esquel) no se presentó y pasó Deportivo Madryn.",
      },
    ],
    overrides: {
      "2013-10-29 deportivo-patagones villa-congreso-viedma": {
        note: "Se suspendió a los 47 minutos del segundo tiempo por agresiones al árbitro, con 1-2, y quedó ese resultado. Wikipedia da 0-2.",
      },
      "2013-11-13 ferro-sud-olavarria independiente-chivilcoy": {
        homeGoals: 0,
        awayGoals: 0,
        advancedId: "ferro-sud-olavarria",
        note: "Ferro Carril Sud ganó 3-0 por penales. RSSSF da 3-0 como resultado del partido; fue 0-0 y penales (La Arena, Wikipedia).",
      },
      "2013-11-13 argentino-rosario yupanqui": {
        awayGoals: 2,
        note: "Goles: Pons (2), Cabral, Schiavo / Fuentes (2). RSSSF da 4-0; ESPN y Wikipedia dan 4-2.",
      },
      "2014-04-02 crucero-del-norte gimnasia-cdu": {
        awayGoals: 0,
        note: "Goles: Víctor Aquino (2). RSSSF da 2-1; la crónica del partido y Wikipedia dan 2-0.",
      },
      "2014-09-17 sanlorenzo defensa-y-justicia": {
        homeGoals: 1,
        awayGoals: 2,
        note: "Goles: Cauteruccio / Rius, Prósperi (en contra). RSSSF da 1-0 para San Lorenzo, pero Defensa y Justicia ganó 2-1 y pasó (La Nueva, ESPN, Wikipedia).",
      },
    },
    wikiErrata: {
      "RSSSF deportivo-patagones 1-2 villa-congreso-viedma": "El partido se suspendió en el segundo tiempo con 1-2 (crónica de la época); Wikipedia da 0-2.",
    },
    summary: "Huracán, que jugaba en la B Nacional, ganó la Copa Argentina 2013/14: empató 0-0 la final con Rosario Central en San Juan y la ganó 5-4 por penales.",
    notes: [
      {
        kind: "formato",
        text: "Fase preliminar y fase inicial por rondas regionales (del interior, a cargo del Consejo Federal, y metropolitanas, con clubes de la B, la C y la D) y fase final a un partido en cancha neutral, con los equipos de Primera y de la B Nacional.",
      },
      { kind: "fuentes", text: "Cinco resultados de RSSSF se corrigieron con Wikipedia y las crónicas de la época (ver cada partido)." },
    ],
  }),
  copaArgentina("2012-13", 2012, "arg2013.html", {
    championIds: ["arsenal"],
    runnerUpIds: ["sanlorenzo"],
    // La fase inicial y la final son secciones aparte de la página: se juntan hasta la lista de participantes.
    headings: [],
    sectionRange: { from: /^Initial phase$/, to: /^List of Participants$/ },
    rollingYear: true,
    allSections: true,
    // Nombres ambiguos de esta página, según su lista de participantes (nombre, sede y provincia).
    aliases: {
      ...A_CA,
      "Club Atlético Racing": "racing-cordoba",
      "Club Huracán": "huracan-san-rafael",
      "Club Tiro Federal": "tiro-federal-bahia-blanca",
      "Club Atlético Gimnasia y Esgrima": "gimnasia-jujuy",
      Alumni: "alumni-villa-maria",
    },
    wikiErrata: {
      "RSSSF platense 2-1 argentino-quilmes":
        "Wikipedia da 2-0. No encontramos una tercera fuente de 2012 (las crónicas que aparecen son del cruce de 2025): queda el resultado de RSSSF.",
    },
    summary: "Arsenal ganó la Copa Argentina 2012/13: le ganó 3-0 la final a San Lorenzo en Catamarca, en octubre de 2013.",
    notes: [
      {
        kind: "formato",
        text: "Fase inicial por zonas (interior, a cargo del Consejo Federal, y metropolitana, con clubes de la B, la C y la D) y fase final a un partido en cancha neutral, desde una ronda preliminar y los veinticuatroavos, con los equipos de Primera y de la B Nacional.",
      },
      { kind: "dato", text: "Duró un año: empezó en octubre de 2012 y la final se jugó el 16 de octubre de 2013." },
    ],
  }),
  copaArgentina("2011-12", 2011, "arg2012.html", {
    championIds: ["boca"],
    runnerUpIds: ["racing"],
    headings: [/^Copa Argentina 2011\/12$/],
    // Wikipedia lo nombra "Alumni" a secas: es el de Villa María, no el Alumni de 1900.
    aliases: { ...A_CA, Alumni: "alumni-villa-maria" },
    summary: "Boca ganó la primera Copa Argentina desde 1970: le ganó 2-1 la final a Racing en San Juan. Fue la edición de la vuelta de la copa, con 186 partidos y clubes de todas las categorías.",
    notes: [
      {
        kind: "formato",
        text: "Primera edición de la Copa Argentina moderna. Una ronda preliminar en La Rioja y Tierra del Fuego, tres fases regionales (zona metropolitana, con clubes de la B, la C y la D, y zona interior, con clubes del Argentino A y B) y, desde los treintaidosavos, eliminación directa a un partido en cancha neutral con los equipos de Primera y la B Nacional.",
      },
      { kind: "fuentes", text: "RSSSF da el Ferro Carril Sud de la primera fase como de Tandil; Wikipedia lo identifica como el de Olavarría, que es el que se usa acá." },
    ],
  }),
  copaArgentina("2015-16", 2016, "arg2016.html", {
    championIds: ["river"],
    runnerUpIds: ["central"],
    headings: [/^Copa Argentina 2016$/],
    aliases: {
      ...A_CA,
      "CA Gimnasia y Esgrima": "gimnasia-jujuy",
      "Club Atlético Gimnasia y Esgrima": "gimnasia-jujuy",
      // "Club Atlético Unión" a secas es el de Sunchales; el de Santa Fe va con "(Santa Fe)".
      "Club Atlético Unión": "union-sunchales",
      "Club Atlético Unión (Santa Fe)": "union-santa-fe",
    },
    tableAliases: { "7": "union-santa-fe", "54": "union-sunchales" },
    weekdayYears: true,
    // Las rondas 1 y 2 de RSSSF son la ida y la vuelta de la fase preliminar (clubes del Federal A); la 3, los treintaidosavos.
    stageRename: {
      "Ronda 1 · Grupo A": "Fase preliminar · Grupo A (ida)",
      "Ronda 1 · Grupo B": "Fase preliminar · Grupo B (ida)",
      "Ronda 2 · Grupo A": "Fase preliminar · Grupo A (vuelta)",
      "Ronda 2 · Grupo B": "Fase preliminar · Grupo B (vuelta)",
      "Ronda 3": "Treintaidosavos de final",
      "Ronda 4": "Dieciseisavos de final",
      "Ronda 5": "Octavos de final",
      "Ronda 6": "Cuartos de final",
    },
    overrides: {
      "2016-12-15 river central": { note: "Goles: Alario 11' (de penal), 40' (de penal) y 72', Alonso 75' / Musto 26', Rubén 30' y 63'." },
    },
    summary: "River ganó la Copa Argentina 2015/16: le ganó 4-3 a Rosario Central una final muy discutida en Córdoba, con tres goles de Alario.",
    notes: [{ kind: "formato", text: FORMATO_2022 }],
  }),
  copaArgentina("2016-17", 2017, "arg2017.html", {
    championIds: ["river"],
    runnerUpIds: ["atletico-tucuman"],
    headings: [/^Copa Argentina 2016\/2017$/],
    aliases: { ...A_CA, "CA San Martín": "san-martin-sj", "CA Jorge Newbery": "jorge-newbery-cr", "CA Almirante Brown": "almirante-brown-lules" },
    weekdayYears: true,
    overrides: {
      "2017-12-09 river atletico-tucuman": { note: "Goles: Scocco 9', Fernández 48' / Rodríguez 11'." },
    },
    summary: "River ganó la Copa Argentina 2016/17, la segunda seguida: le ganó 2-1 la final a Atlético Tucumán en Mendoza.",
    notes: [{ kind: "formato", text: FORMATO_2022 }],
  }),
  copaArgentina("2017-18", 2018, "arg2018.html", {
    championIds: ["central"],
    runnerUpIds: ["gimnasia"],
    headings: [/^Copa Argentina 2017\/2018$/],
    aliases: { ...A_CA, "Club Huracán": "huracan-san-rafael" },
    weekdayYears: true,
    wikiErrata: {
      "RSSSF velez 1-1 central-cordoba-sde": "Wikipedia da 0-0; el sitio oficial de Vélez da 1-1 (goles de Renzo Pérez y Matías Vargas) y Central Córdoba ganó 4-3 por penales, como en RSSSF.",
      "RSSSF atletico-tucuman 1-0 tristan-suarez": "Wikipedia da 2-1; Infobae y ESPN dan 1-0 (gol de Leandro Díaz), como RSSSF.",
    },
    summary: "Rosario Central ganó la Copa Argentina 2017/18: empató 1-1 la final con Gimnasia y Esgrima La Plata en Mendoza y la ganó 4-1 por penales.",
    notes: [{ kind: "formato", text: FORMATO_2019 }],
  }),
  copaArgentina("2018-19", 2019, "arg2019.html", {
    championIds: ["river"],
    runnerUpIds: ["central-cordoba-sde"],
    headings: [/^Copa Argentina 2018\/2019$/, /^Copa de la Superliga 2019$/],
    tableIndex: [0],
    // Dos "Club Atlético Unión" y dos "Club Atlético Sarmiento" en la tabla: se identifican por el puesto.
    tableAliases: { "32": "sarmiento-resistencia", "54": "union-sunchales", "70": "union-santa-fe", "78": "sarmiento-junin" },
    knownTableDiffs: {
      keys: [
        "sportivo-dock-sud:won", "sportivo-dock-sud:drawn", "sportivo-dock-sud:goalsFor", "sportivo-dock-sud:points",
        "patronato-parana:drawn", "patronato-parana:lost", "patronato-parana:goalsAgainst", "patronato-parana:points",
      ],
      explanation: "La tabla de RSSSF cuenta el Patronato–Dock Sud como 1-2; fue 1-1 y Patronato pasó por penales (ver el partido).",
    },
    overrides: {
      "2019-03-13 patronato-parana sportivo-dock-sud": {
        homeGoals: 1,
        awayGoals: 1,
        advancedId: "patronato-parana",
        note: "Patronato ganó 2-1 por penales. RSSSF da 1-2 (y así lo cuenta en su tabla), pero La Nación, El Día y Ámbito dan 1-1 (goles de Rescaldani y Cariaga), como Wikipedia.",
      },
    },
    wikiErrata: {
      "RSSSF newells 1-2 villa-mitre": "Wikipedia da 0-0 y penales; Infobae y 442: el partido se suspendió a los 90 minutos por incidentes de la hinchada de Newell's, con 2-1 para Villa Mitre, y quedó ese resultado, como en RSSSF.",
      "RSSSF nueva-chicago 0-1 central-cordoba-sde": "Wikipedia da 1-2; la web oficial de la Copa Argentina da 0-1 (gol de Melivilo), como RSSSF.",
      "RSSSF defensa-y-justicia 1-0 gimnasia-tiro-salta": "Wikipedia da 2-1; Infobae y ESPN dan 1-0 (gol de Nicolás Fernández), como RSSSF.",
      "RSSSF mitre-sde 1-0 deportivo-roca": "La tabla de resultados de Wikipedia da 2-1, pero su propio cuadro da 1-0; Diario Río Negro también da 1-0 (gol de Cadenazzi a los 89), como RSSSF.",
    },
    summary: "River ganó su tercera Copa Argentina: le ganó 3-0 la final a Central Córdoba de Santiago del Estero, en Mendoza.",
    notes: [{ kind: "formato", text: FORMATO_2019 }],
  }),
  copaArgentina("2019-20", 2020, "arg2020.html", {
    championIds: ["boca"],
    runnerUpIds: ["talleres"],
    headings: [/^Copa Total Argentina$/],
    weekdayYears: true,
    knownTableDiffs: {
      keys: ["defensores-pronunciamiento:played", "defensores-pronunciamiento:lost", "defensores-pronunciamiento:goalsAgainst"],
      explanation: "La tabla de RSSSF no cuenta el River 4-0 Defensores de Pronunciamiento de treintaidosavos (jugado recién el 10 de febrero de 2021, confirmado por Wikipedia).",
    },
    tableAliases: { "39": "talleres-re", "54": "sarmiento-resistencia", "70": "union-sunchales" },
    tableIndex: [0],
    summary: "Boca ganó la Copa Argentina 2019/20: empató 0-0 la final con Talleres en Santiago del Estero y la ganó 5-4 por penales.",
    notes: [
      { kind: "formato", text: FORMATO_2019 },
      { kind: "dato", text: "La pandemia de covid-19 frenó la copa en marzo de 2020, en los treintaidosavos. Se retomó en diciembre de 2020 y la final se jugó el 8 de diciembre de 2021." },
    ],
  }),
  ...[2022, 2023, 2024, 2025, 2026].map((y) =>
    copaArgentina(String(y), y, `arg${y}.html`, {
      runnerUpIds: ({ 2022: ["talleres"], 2023: ["defensa-y-justicia"], 2024: ["velez"], 2025: ["argentinos"] } as Record<number, string[]>)[y],
      championIds: ({ 2022: ["patronato-parana"], 2023: ["estudiantes"], 2024: ["central-cordoba-sde"], 2025: ["independiente-rivadavia"] } as Record<number, string[]>)[y] ?? [],
      ...(y === 2022 && {
        aliases: { ...A_CA, "CA San Martín": "san-martin-tucuman" },
        overrides: {
          "2022-07-06 argentinos defensa-y-justicia": {
            awayGoals: 1,
            note: "RSSSF da 0-2, pero La Nación, Página/12 y Ámbito dan 0-1 (gol de Kevin Gutiérrez), como Wikipedia.",
          },
        },
        knownTableDiffs: {
          keys: ["defensa-y-justicia:goalsFor", "argentinos:goalsAgainst"],
          explanation: "La tabla de RSSSF cuenta el Argentinos–Defensa y Justicia de octavos como 0-2; fue 0-1 (ver el partido).",
        },
      }),
      // Homónimos en la tabla de RSSSF ("Club Atlético Sarmiento", "Independiente", "Talleres", "Gimnasia y Esgrima"),
      // por su puesto: el primero de cada nombre lo resuelve el alias; los demás van acá.
      tableAliases: ({
        2022: { "17": "gimnasia-jujuy", "55": "gimnasia-mendoza" },
        2023: { "58": "sarmiento-resistencia", "62": "independiente-chivilcoy" },
        2024: { "7": "talleres-re", "10": "talleres", "53": "independiente-chivilcoy" },
        2025: { "41": "gimnasia-jujuy", "45": "sarmiento-la-banda" },
        2026: { "30": "gimnasia-jujuy", "38": "gimnasia-mendoza", "57": "sarmiento-la-banda" },
      } as Record<number, Record<string, string>>)[y],
      // Partidos todavía sin rival definido ("TBD").
      skip: (m) => /\bTBD\b/.test(`${m.home} ${m.away}`),
      headings: [y === 2022 ? /^Copa Argentina Axion energy 2022$/ : new RegExp(`^AFA national cup: Copa Argentina ${y}$`)],
      tableIndex: [0],
      ...(y === 2026 && { inProgress: true }),
      summary: ({
        2022: "Patronato, que ese año descendió, ganó su primera Copa Argentina: eliminó a River y a Boca por penales y le ganó 1-0 la final a Talleres en Mendoza.",
        2023: "Estudiantes de La Plata ganó la Copa Argentina: le ganó 3-2 la semifinal a Boca y 1-0 la final a Defensa y Justicia, en Lanús.",
        2024: "Central Córdoba de Santiago del Estero ganó su primer título nacional: le ganó 1-0 la final a Vélez en Santa Fe.",
        2025: "Independiente Rivadavia de Mendoza ganó su primer título nacional: eliminó a River por penales en semifinales y empató 2-2 la final con Argentinos Juniors en Córdoba, que ganó 5-3 por penales.",
        2026: "En juego: cargada hasta los cuartos de final (actualización de RSSSF de septiembre de 2026).",
      } as Record<number, string>)[y],
      notes: [
        { kind: "formato", text: FORMATO_2022 },
        ...(y === 2026 ? [{ kind: "dato" as const, text: "Torneo en curso: se actualiza a medida que RSSSF carga los partidos." }] : []),
      ],
    }),
  ),
];
