// Copas nacionales 1941–1950. Las páginas de RSSSF de estas copas tienen formatos muy distintos entre sí
// (columnas alineadas a la derecha, fechas en la misma línea, córners en líneas sueltas): los partidos se cargan
// a mano, uno por uno, copiados de la página de RSSSF de cada edición. El control de la copa (final contra el
// índice de RSSSF, eliminados que no vuelven a jugar, participantes) corre igual.
import type { Match } from "../../lib/types";
import type { TournamentConfig } from "./config";

const AFA = "Asociación del Fútbol Argentino";

type Row = [date: string, stage: string, home: string, hg: number, ag: number, away: string, extra?: Partial<Match>];
const rows = (slug: string, list: Row[]) =>
  list.map(([date, stage, homeId, homeGoals, awayGoals, awayId, extra], i) => ({
    id: `${slug}-${String(i + 1).padStart(3, "0")}`,
    date,
    stage,
    phase: "cup" as const,
    homeId,
    awayId,
    homeGoals,
    awayGoals,
    ...extra,
  }));

// ───────── Copa Escobar ─────────
const ESCOBAR = {
  kind: "formato",
  text: "La jugaban los siete primeros del campeonato, casi siempre en uno o dos días y en una misma cancha, con partidos de 40 minutos. Los empates se definían por córners (y si seguían iguales, por sorteo). El campeón de liga entraba directo en semifinales.",
} as const;
const corners = (team: string, score: string, extra = "") => ({ advancedId: team, note: `Pasó por córners (${score}).${extra}` });

const escobar = (year: number, rest: Partial<TournamentConfig> & Pick<TournamentConfig, "championIds" | "summary">, list: Row[]): TournamentConfig => {
  const slug = `copa-escobar-${year}`;
  return {
    slug,
    kind: "cup",
    year,
    file: `arg-esc${String(year).slice(2)}.html`,
    competition: "Copa Escobar",
    title: `Copa Escobar ${year}`,
    tournament: "Copa Adrián C. Escobar",
    organizer: AFA,
    skip: () => true,
    extraMatches: rows(slug, list),
    notes: [ESCOBAR],
    ...rest,
  };
};

const CR = "Cancha de River Plate";
const CSL = "Cancha de San Lorenzo (Gasómetro)";

// ───────── Copa de Competencia Británica ─────────
const BRITANICA = {
  kind: "formato",
  text: "Copa de Competencia «Jorge VI», donada por el embajador británico en nombre del rey. La jugaban los equipos de Primera por eliminación directa a un partido, casi siempre en cancha neutral; los semifinalistas de 1944 y 1945 entraron al Campeonato de la República.",
} as const;
const at = (club: string) => `Cancha de ${club}`;
const britanica = (year: number, rest: Partial<TournamentConfig> & Pick<TournamentConfig, "championIds" | "summary">, list: Row[]): TournamentConfig => {
  const slug = `copa-britanica-${year}`;
  return {
    slug,
    kind: "cup",
    year,
    file: `arg-bri${String(year).slice(2)}.html`,
    competition: "Copa de Competencia Británica",
    title: `Copa Británica ${year}`,
    tournament: "Copa de Competencia Británica «Jorge VI»",
    organizer: AFA,
    skip: () => true,
    extraMatches: rows(slug, list),
    notes: [BRITANICA],
    ...rest,
  };
};

// ───────── Copa de la República (Campeonato de la República) ─────────
const REPUBLICA = {
  kind: "formato",
  text: "Primer torneo nacional con clubes de todo el país. Los equipos de las ligas del interior jugaban por zonas (grupos A a D) a eliminación directa y los cuatro ganadores cruzaban en cuartos de final con cuatro equipos de Primera. Los grupos eran cuadros de eliminación, no tablas.",
} as const;
const en = (city: string) => ({ venue: city });
const aet = { note: "Con alargue." };
const republica = (year: number, rest: Partial<TournamentConfig> & Pick<TournamentConfig, "championIds" | "runnerUpIds" | "summary">, list: Row[]): TournamentConfig => {
  const slug = `copa-republica-${year}`;
  return {
    slug,
    kind: "cup",
    year,
    file: `arg-rep${String(year).slice(2)}.html`,
    wiki: `Copa de la República ${year}`,
    competition: "Copa de la República",
    title: `Copa de la República ${year}`,
    tournament: "Campeonato de la República",
    organizer: `${AFA} (las zonas del interior, el Consejo Federal)`,
    skip: () => true,
    knockoutGroups: true,
    extraMatches: rows(slug, list),
    notes: [REPUBLICA],
    ...rest,
  };
};
// Nombres de la lista de participantes de RSSSF.
const REP_ALIASES: Record<string, string> = {
  "Argentino del Norte": "argentino-norte-salta",
  "Central Argentino": "central-argentino-sde",
  Colón: "colon-santa-fe",
  "Estudiantes LP": "estudiantes",
  "Ferro Carril Oeste (BA)": "ferro",
  "Ferro Carril Oeste (Buenos Aires)": "ferro",
  "General Paz Juniors": "general-paz-juniors",
  "Gimnasia y Esgrima LP": "gimnasia",
  "Huracán (BA)": "huracan",
  "Independiente (A)": "independiente",
  "Independiente (J)": "independiente-jujuy",
  Lipton: "lipton-corrientes",
  "Nacional V. S. P.": "nacional-vsp-mendoza",
  Patronato: "patronato-parana",
  "Platense (VL)": "platense",
  "Puerto Comercial": "puerto-comercial",
  Regional: "regional-resistencia",
  "Quilmes (MdP)": "quilmes-mdp",
  "Quilmes (Mar del Plata)": "quilmes-mdp",
  "Rioja Juniors": "rioja-juniors",
  "San Martín (SJ)": "san-martin-sj",
  "San Martín (T)": "san-martin-tucuman",
  "San Martín (Tucumán)": "san-martin-tucuman",
  "Sarmiento (C)": "sarmiento-catamarca",
  "Sarmiento (J)": "sarmiento-junin",
  "Sarmiento (Junín)": "sarmiento-junin",
  "Sportivo Bella Vista": "bella-vista-tucuman",
  "Sportivo Estudiantes": "sportivo-estudiantes-sl",
  Tráfico: "trafico-pergamino",
  "Aprendices Chaqueños": "aprendices-chaquenos",
  "Atlético Concepción": "atletico-concepcion",
  "Atlético Ledesma": "atletico-ledesma",
  "Atlético Uruguay": "atletico-uruguay",
  "Aviador Origone": "aviador-origone",
  "Belgrano (Paraná)": "belgrano-parana",
  "Boca Juniors (Buenos Aires)": "boca",
  "Boca Juniors (Tres Arroyos)": "boca-tres-arroyos",
  "Cazadores de los Andes": "cazadores-andes",
  "Central Goya": "central-goya",
  "Central Norte (Metán)": "central-norte-metan|Central Norte (Metán)",
  "Central Norte Argentino": "central-norte-metan",
  "Central Norte (Salta)": "central-norte-salta",
  "Defensores de Belgrano (B. Ville)": "defensores-bell-ville",
  "Defensores de Cambaceres": "defensores-cambaceres",
  "Deportivo Colón": "deportivo-colon-chivilcoy",
  "Deportivo Unión": "deportivo-union-catamarca",
  "El Socorro": "el-socorro-pergamino",
  "Gimnasia y Esgrima (Santa Fe)": "gimnasia-santa-fe",
  "Godoy Cruz Antonio Tomba": "godoy-cruz",
  Graffigna: "graffigna",
  Güemes: "guemes-sde",
  "Huracán (Buenos Aires)": "huracan",
  "Huracán (Mercedes)": "huracan-mercedes",
  "Independiente (La Rioja)": "independiente-la-rioja",
  "Newell's Old Boys": "newells",
  Ñuñorco: "nunorco",
  Paraná: "parana-zarate",
  "Club Atlético Platense": "platense",
  Provinciano: "provinciano-tafi",
  "Sarmiento (Resistencia)": "sarmiento-resistencia",
  "Sportivo Atenas": "sportivo-atenas",
  "Sportivo Club Victoria": "sportivo-victoria-sl",
  "Sportivo Ferroviarios": "ferroviarios-corrientes",
  "Sportivo General Urquiza": "general-urquiza-mdp",
  "Sportivo Huracán": "sportivo-huracan-bragado",
  "Sportivo Las Palmeras": "las-palmeras-san-pedro",
  "Sportivo Patria": "sportivo-patria",
  "Sportivo Unión": "sportivo-union-posadas",
  "Talleres Central Norte": "talleres-anatuya",
  "Villa Mitre": "villa-mitre",
  "9 de Julio": "nueve-de-julio-rafaela",
  "Atlético de la Juventud": "atletico-juventud-sj",
  "Benjamín Matienzo": "benjamin-matienzo",
  "Central Norte (Sáenz Peña)": "central-norte-spena",
  Comercio: "comercio-ledesma",
  "Estudiantes de La Plata": "estudiantes",
  "Estudiantes (Santiago del Estero)": "estudiantes-sde",
  "Gimnasia y Esgrima (Jujuy)": "gimnasia-jujuy",
  "Gimnasia y Esgrima (Mercedes)": "gimnasia-mercedes",
  "Huracán (San Luis)": "huracan-san-luis",
  Independencia: "independencia-san-pedro",
  "Independiente (Pascanas)": "independiente-pascanas",
  "Independiente Rivadavia": "independiente-rivadavia",
  "Juventud Unida": "juventud-unida-tafi",
  Pettirossi: "pettirossi",
  "Racing (Colón)": "racing-colon",
  "Racing Club": "racing",
  "San Martín (Olavarría)": "san-martin-olavarria",
  "San Pablo": "san-pablo-tucuman",
  "Sarmiento (Pigüé)": "sarmiento-pigue",
  "Sol de Mayo": "sol-de-mayo-formosa",
  Sportivo: "sportivo-25-mayo",
  "Sportivo Comercio": "sportivo-comercio-salta",
  "Sportivo Municipal": "sportivo-municipal-rc",
  "Sportivo Vélez Sarsfield": "sportivo-velez-catamarca",
  "Sportivo Villa Mercedes": "sportivo-villa-mercedes",
  "Talleres (Córdoba)": "talleres",
  Victoria: "victoria-concordia",
};

export const CUP_TOURNAMENTS_40S: TournamentConfig[] = [
  republica(
    1943,
    {
      championIds: ["sanlorenzo"],
      runnerUpIds: ["general-paz-juniors"],
      tournament: "Campeonato de la República · Copa General de División Pedro Pablo Ramírez",
      aliases: REP_ALIASES,
      summary: "San Lorenzo ganó la primera Copa de la República: 8-3 a General Paz Juniors de Córdoba en la final, en la cancha de Chacarita.",
      notes: [
        REPUBLICA,
        { kind: "formato", text: "En 1943 los 16 equipos de Primera jugaron su propio cuadro (dos rondas) para definir los cuatro que entraron en cuartos de final." },
        { kind: "dato", text: "La semifinal San Lorenzo–Huracán se suspendió a los 126 minutos (en el alargue), 2-2, y se jugó de nuevo." },
      ],
    },
    [
      ["1943-10-12", "Primera División · 1.ª ronda", "chacarita", 5, 1, "lanus"],
      ["1943-10-12", "Primera División · 1.ª ronda", "estudiantes", 4, 2, "racing", aet],
      ["1943-10-12", "Primera División · 1.ª ronda", "gimnasia", 5, 1, "ferro"],
      ["1943-10-12", "Primera División · 1.ª ronda", "huracan", 4, 1, "banfield"],
      ["1943-10-12", "Primera División · 1.ª ronda", "independiente", 4, 3, "central", aet],
      ["1943-10-12", "Primera División · 1.ª ronda", "newells", 4, 2, "atlanta", aet],
      ["1943-10-12", "Primera División · 1.ª ronda", "platense", 4, 3, "boca", aet],
      ["1943-10-12", "Primera División · 1.ª ronda", "sanlorenzo", 4, 2, "river"],
      ["1943-11-11", "Primera División · 2.ª ronda", "huracan", 5, 1, "platense"],
      ["1943-11-11", "Primera División · 2.ª ronda", "independiente", 4, 2, "gimnasia"],
      ["1943-11-11", "Primera División · 2.ª ronda", "newells", 5, 0, "chacarita", en("Rosario")],
      ["1943-11-11", "Primera División · 2.ª ronda", "sanlorenzo", 3, 2, "estudiantes"],
      ["1943-11-14", "Grupo A · 1.ª ronda", "independiente-jujuy", 4, 2, "argentino-norte-salta", en("Jujuy")],
      ["1943-11-21", "Grupo A · 2.ª ronda", "central-argentino-sde", 2, 3, "bella-vista-tucuman", { ...en("Santiago del Estero"), ...aet }],
      ["1943-11-21", "Grupo A · 2.ª ronda", "san-martin-tucuman", 5, 0, "independiente-jujuy", en("Tucumán")],
      ["1943-11-28", "Grupo A · 3.ª ronda", "san-martin-tucuman", 7, 2, "bella-vista-tucuman", en("Tucumán")],
      ["1943-11-14", "Grupo B · 1.ª ronda", "sarmiento-catamarca", 6, 0, "rioja-juniors", en("Catamarca")],
      ["1943-11-14", "Grupo B · 1.ª ronda", "sportivo-estudiantes-sl", 0, 6, "nacional-vsp-mendoza", en("San Luis")],
      ["1943-11-21", "Grupo B · 2.ª ronda", "general-paz-juniors", 6, 0, "sarmiento-catamarca", { ...en("Córdoba"), ...aet }],
      ["1943-11-21", "Grupo B · 2.ª ronda", "nacional-vsp-mendoza", 2, 1, "san-martin-sj", en("Mendoza")],
      ["1943-11-28", "Grupo B · 3.ª ronda", "general-paz-juniors", 9, 6, "nacional-vsp-mendoza", { ...en("Córdoba"), ...aet }],
      ["1943-11-14", "Grupo C · 1.ª ronda", "colon-santa-fe", 3, 2, "patronato-parana", en("Santa Fe")],
      ["1943-11-14", "Grupo C · 1.ª ronda", "regional-resistencia", 5, 3, "lipton-corrientes", en("Resistencia")],
      ["1943-11-28", "Grupo C · 2.ª ronda", "colon-santa-fe", 1, 3, "regional-resistencia", en("Santa Fe")],
      ["1943-11-14", "Grupo D · 1.ª ronda", "quilmes-mdp", 1, 2, "puerto-comercial", en("Mar del Plata")],
      ["1943-11-14", "Grupo D · 1.ª ronda", "trafico-pergamino", 1, 4, "sarmiento-junin", en("Pergamino")],
      ["1943-11-28", "Grupo D · 2.ª ronda", "puerto-comercial", 3, 0, "sarmiento-junin", en("Bahía Blanca")],
      ["1943-12-12", "Cuartos de final", "general-paz-juniors", 3, 2, "newells", { venue: at("Boca Juniors") }],
      ["1943-12-12", "Cuartos de final", "sanlorenzo", 4, 1, "puerto-comercial", { venue: at("Chacarita Juniors") }],
      ["1943-12-14", "Cuartos de final", "huracan", 7, 0, "regional-resistencia", { venue: at("San Lorenzo") }],
      ["1943-12-14", "Cuartos de final", "san-martin-tucuman", 2, 0, "independiente", { venue: at("Chacarita Juniors") }],
      ["1943-12-16", "Semifinal", "general-paz-juniors", 5, 4, "san-martin-tucuman", { venue: at("San Lorenzo") }],
      ["1943-12-16", "Semifinal", "sanlorenzo", 2, 2, "huracan", { venue: at("Chacarita Juniors"), note: "Con alargue. Suspendido a los 126 minutos con 2-2; se jugó de nuevo." }],
      ["1943-12-19", "Semifinal (desempate)", "sanlorenzo", 2, 1, "huracan", { venue: at("Chacarita Juniors") }],
      ["1943-12-21", "Final", "sanlorenzo", 8, 3, "general-paz-juniors", { venue: at("Chacarita Juniors") }],
    ],
  ),
  republica(
    1944,
    {
      championIds: ["san-martin-tucuman"],
      runnerUpIds: ["newells"],
      aliases: REP_ALIASES,
      summary: "San Martín de Tucumán ganó la Copa de la República: 3-1 a Newell's Old Boys en la final, en Tucumán. Fue el primer club indirectamente afiliado a la AFA en ganar una copa nacional.",
      notes: [
        REPUBLICA,
        { kind: "formato", text: "Los cuatro equipos de Primera fueron los semifinalistas de la Copa Británica 1944 (Boca, Huracán, Newell's y Platense). Las zonas del interior las organizó el Consejo Federal; desde cuartos de final, la AFA." },
        { kind: "fuentes", text: "Talleres de Córdoba no figura en la lista de participantes de RSSSF, pero sí en los partidos del grupo B." },
        { kind: "fuentes", text: "Semifinal Sarmiento–San Martín: pasó San Martín por córners. RSSSF da 12-7 con los números del lado de Sarmiento; Wikipedia da 12-11 para San Martín." },
      ],
      listedWithoutMatches: { ferro: "no es un participante: es una línea de plantilla que quedó en la página de RSSSF (\"ferro carril oeste (buenos aires) (xx) x:x\")" },
    },
    [
      ["1944-10-29", "Grupo A · 1.ª ronda", "cazadores-andes", 1, 0, "atletico-ledesma", en("Jujuy")],
      ["1944-10-29", "Grupo A · 1.ª ronda", "central-norte-salta", 5, 1, "central-norte-metan", { ...en("Salta"), awayAs: "Central Norte (Metán)" }],
      ["1944-10-29", "Grupo A · 1.ª ronda", "guemes-sde", 3, 2, "talleres-anatuya", en("Santiago del Estero")],
      ["1944-10-29", "Grupo A · 1.ª ronda", "independiente-la-rioja", 4, 2, "deportivo-union-catamarca", en("La Rioja")],
      ["1944-10-29", "Grupo A · 1.ª ronda", "provinciano-tafi", 2, 6, "nunorco", en("Tafí Viejo")],
      ["1944-11-05", "Grupo A · 2.ª ronda", "central-norte-salta", 1, 0, "cazadores-andes", en("Salta")],
      ["1944-11-05", "Grupo A · 2.ª ronda", "atletico-concepcion", 6, 2, "guemes-sde", en("Tucumán")],
      ["1944-11-05", "Grupo A · 2.ª ronda", "nunorco", 3, 2, "independiente-la-rioja", en("Monteros")],
      ["1944-11-12", "Grupo A · 3.ª ronda", "atletico-concepcion", 3, 1, "central-norte-salta", en("Tucumán")],
      ["1944-11-12", "Grupo A · 3.ª ronda", "nunorco", 0, 5, "san-martin-tucuman", en("Monteros")],
      ["1944-11-26", "Grupo A · 4.ª ronda", "san-martin-tucuman", 4, 0, "atletico-concepcion", en("Tucumán")],
      ["1944-10-29", "Grupo B · 1.ª ronda", "graffigna", 0, 1, "godoy-cruz", en("San Juan")],
      ["1944-10-29", "Grupo B · 1.ª ronda", "sportivo-atenas", 5, 3, "defensores-bell-ville", en("Río Cuarto")],
      ["1944-10-29", "Grupo B · 1.ª ronda", "sportivo-victoria-sl", 6, 4, "aviador-origone", en("San Luis")],
      ["1944-11-05", "Grupo B · 2.ª ronda", "sportivo-victoria-sl", 2, 5, "godoy-cruz", en("San Luis")],
      ["1944-11-05", "Grupo B · 2.ª ronda", "talleres", 3, 2, "sportivo-atenas", en("Córdoba")],
      ["1944-11-12", "Grupo B · 3.ª ronda", "godoy-cruz", 2, 3, "talleres", en("Mendoza")],
      ["1944-10-29", "Grupo C · 1.ª ronda", "belgrano-parana", 2, 1, "atletico-uruguay", en("Paraná")],
      ["1944-10-29", "Grupo C · 1.ª ronda", "gimnasia-santa-fe", 4, 2, "nueve-de-julio-rafaela", en("Santa Fe")],
      ["1944-10-29", "Grupo C · 1.ª ronda", "ferroviarios-corrientes", 2, 2, "central-goya", { ...en("Corrientes"), advancedId: "ferroviarios-corrientes", note: "Con alargue. Pasó por córners (18-4)." }],
      ["1944-11-05", "Grupo C · 2.ª ronda", "belgrano-parana", 4, 3, "gimnasia-santa-fe", en("Paraná")],
      ["1944-11-05", "Grupo C · 2.ª ronda", "sarmiento-resistencia", 3, 3, "aprendices-chaquenos", { ...en("Resistencia"), advancedId: "sarmiento-resistencia", note: "Con alargue. Pasó por córners (11-1)." }],
      ["1944-11-12", "Grupo C · 2.ª ronda", "sportivo-patria", 6, 5, "ferroviarios-corrientes", en("Formosa")],
      ["1944-11-14", "Grupo C · 3.ª ronda", "sarmiento-resistencia", 4, 2, "belgrano-parana", en("Resistencia")],
      ["1944-11-19", "Grupo C · 3.ª ronda", "sportivo-union-posadas", 1, 3, "sportivo-patria", en("Posadas")],
      ["1944-11-26", "Grupo C · 4.ª ronda", "sportivo-patria", 1, 3, "sarmiento-resistencia", en("Formosa")],
      ["1944-10-29", "Grupo D · 1.ª ronda", "huracan-mercedes", 2, 3, "deportivo-colon-chivilcoy", en("Mercedes")],
      ["1944-10-29", "Grupo D · 1.ª ronda", "sarmiento-junin", 6, 1, "el-socorro-pergamino", en("Junín")],
      ["1944-10-29", "Grupo D · 1.ª ronda", "las-palmeras-san-pedro", 1, 3, "parana-zarate", en("San Pedro")],
      ["1944-11-05", "Grupo D · 2.ª ronda", "deportivo-colon-chivilcoy", 8, 2, "sportivo-huracan-bragado", en("Chivilcoy")],
      ["1944-11-05", "Grupo D · 2.ª ronda", "parana-zarate", 5, 1, "sarmiento-junin", en("General Uriburu (Zárate)")],
      ["1944-11-05", "Grupo D · 2.ª ronda", "general-urquiza-mdp", 1, 0, "defensores-cambaceres", en("Mar del Plata")],
      ["1944-11-05", "Grupo D · 2.ª ronda", "villa-mitre", 5, 2, "boca-tres-arroyos", en("Bahía Blanca")],
      ["1944-11-12", "Grupo D · 3.ª ronda", "parana-zarate", 3, 3, "deportivo-colon-chivilcoy", { ...en("General Uriburu (Zárate)"), note: "Se jugó un desempate." }],
      ["1944-11-12", "Grupo D · 3.ª ronda", "villa-mitre", 6, 2, "general-urquiza-mdp", en("Bahía Blanca")],
      ["1944-11-19", "Grupo D · 3.ª ronda (desempate)", "deportivo-colon-chivilcoy", 1, 0, "parana-zarate", en("Chivilcoy")],
      ["1944-11-26", "Grupo D · 4.ª ronda", "deportivo-colon-chivilcoy", 0, 3, "villa-mitre", en("Chivilcoy")],
      ["1944-12-03", "Cuartos de final", "talleres", 5, 3, "platense", en("Córdoba")],
      ["1944-12-03", "Cuartos de final", "villa-mitre", 0, 5, "newells", en("Bahía Blanca")],
      ["1944-12-17", "Cuartos de final", "san-martin-tucuman", 2, 2, "boca", { ...en("Tucumán"), advancedId: "san-martin-tucuman", note: "Con alargue. Pasó por córners (11-9)." }],
      ["1944-12-17", "Cuartos de final", "sarmiento-resistencia", 2, 1, "huracan", { ...en("Resistencia"), ...aet }],
      ["1945-02-25", "Semifinal", "sarmiento-resistencia", 1, 1, "san-martin-tucuman", { ...en("Resistencia"), advancedId: "san-martin-tucuman", note: "Con alargue. Pasó San Martín por córners (ver notas de la copa: las fuentes no coinciden en la cantidad)." }],
      ["1945-02-25", "Semifinal", "talleres", 1, 3, "newells", { venue: at("Belgrano (Córdoba)") }],
      ["1945-03-04", "Final", "san-martin-tucuman", 3, 1, "newells", { ...en("Tucumán"), note: "Goles: Juárez 5', Díaz 36', Brandán 48'; R. Micci 54'. Árbitro: J. Cángaro." }],
    ],
  ),
  republica(
    1945,
    {
      championIds: ["estudiantes"],
      runnerUpIds: ["boca"],
      aliases: REP_ALIASES,
      summary: "Estudiantes de La Plata ganó la Copa de la República: 4-4 con Boca en la final y 1-0 en el desempate, jugado nueve meses después.",
      notes: [
        REPUBLICA,
        { kind: "formato", text: "Los cuatro equipos de Primera fueron los semifinalistas de la Copa Británica 1945 (Boca, Estudiantes, Ferro y Racing)." },
        { kind: "dato", text: "Las semifinales y la final se jugaron en marzo de 1946 y el desempate de la final recién el 18 de diciembre de 1946 (fechas confirmadas en Wikipedia)." },
      ],
    },
    [
      ["1945-10-28", "Grupo A · 1.ª ronda", "central-norte-metan", 0, 5, "sportivo-comercio-salta", { venue: "Estadio de la Liga Metanense (Metán)" }],
      ["1945-10-28", "Grupo A · 1.ª ronda", "comercio-ledesma", 2, 3, "gimnasia-jujuy", { venue: at("Atlético Ledesma") }],
      ["1945-10-28", "Grupo A · 1.ª ronda", "nunorco", 6, 0, "juventud-unida-tafi", { venue: at("Ñuñorco (Monteros)") }],
      ["1945-10-28", "Grupo A · 1.ª ronda", "sportivo-velez-catamarca", 3, 1, "rioja-juniors", { venue: "Estadio de la Liga Catamarqueña" }],
      ["1945-10-28", "Grupo A · 1.ª ronda", "talleres-anatuya", 0, 0, "estudiantes-sde", { walkover: true, awardedTo: "estudiantes-sde", note: "No se jugó: los puntos fueron para Estudiantes." }],
      ["1945-11-04", "Grupo A · 2.ª ronda", "estudiantes-sde", 4, 2, "san-martin-tucuman", { venue: at("Atlético Mitre (Santiago del Estero)") }],
      ["1945-11-04", "Grupo A · 2.ª ronda", "gimnasia-jujuy", 3, 2, "sportivo-comercio-salta", { venue: "Estadio de la Liga Jujeña" }],
      ["1945-11-04", "Grupo A · 2.ª ronda", "sportivo-velez-catamarca", 4, 2, "nunorco", { venue: "Estadio de la Liga Catamarqueña" }],
      ["1945-11-11", "Grupo A · 3.ª ronda", "gimnasia-jujuy", 2, 4, "estudiantes-sde", { venue: "Estadio de la Liga Jujeña" }],
      ["1945-11-11", "Grupo A · 3.ª ronda", "san-pablo-tucuman", 5, 0, "sportivo-velez-catamarca", { venue: at("All Boys (Tucumán)") }],
      ["1945-11-18", "Grupo A · 4.ª ronda", "estudiantes-sde", 4, 3, "san-pablo-tucuman", { venue: at("Atlético Mitre (Santiago del Estero)") }],
      ["1945-10-28", "Grupo B · 1.ª ronda", "independiente-rivadavia", 1, 0, "atletico-juventud-sj", { venue: at("Gimnasia y Esgrima (Mendoza)") }],
      ["1945-10-28", "Grupo B · 1.ª ronda", "sportivo-villa-mercedes", 2, 1, "huracan-san-luis", { venue: "Estadio de la Liga Mercedina (Villa Mercedes)" }],
      ["1945-11-04", "Grupo B · 1.ª ronda", "sportivo-municipal-rc", 2, 1, "independiente-pascanas", { venue: "Estadio de la Liga de Río Cuarto" }],
      ["1945-11-04", "Grupo B · 2.ª ronda", "independiente-rivadavia", 3, 1, "sportivo-villa-mercedes", { venue: at("Independiente Rivadavia") }],
      ["1945-11-11", "Grupo B · 2.ª ronda", "sportivo-municipal-rc", 1, 0, "talleres", { venue: "Estadio de la Liga de Río Cuarto" }],
      ["1945-11-18", "Grupo B · 3.ª ronda", "independiente-rivadavia", 5, 1, "sportivo-municipal-rc", { venue: at("Independiente Rivadavia") }],
      ["1945-10-28", "Grupo C · 1.ª ronda", "victoria-concordia", 3, 3, "patronato-parana", { venue: at("Atlético Libertad (Concordia)"), advancedId: "victoria-concordia", note: "Victoria pasó por sorteo." }],
      ["1945-10-28", "Grupo C · 1.ª ronda", "nueve-de-julio-rafaela", 2, 6, "colon-santa-fe", { venue: at("Atlético Rafaela") }],
      ["1945-11-04", "Grupo C · 2.ª ronda", "central-norte-spena", 1, 2, "sarmiento-resistencia", { venue: at("Sportivo (Sáenz Peña)") }],
      ["1945-11-04", "Grupo C · 2.ª ronda", "colon-santa-fe", 3, 1, "victoria-concordia", { venue: at("Gimnasia y Esgrima (Santa Fe)") }],
      ["1945-11-05", "Grupo C · 2.ª ronda", "benjamin-matienzo", 4, 1, "ferroviarios-corrientes", { venue: at("Central Goya") }],
      ["1945-11-18", "Grupo C · 3.ª ronda", "sarmiento-resistencia", 3, 2, "colon-santa-fe", { venue: at("Regional (Resistencia)") }],
      ["1945-11-18", "Grupo C · 3.ª ronda", "sol-de-mayo-formosa", 7, 2, "benjamin-matienzo", { venue: "Estadio de la Liga Formoseña" }],
      ["1945-11-25", "Grupo C · 4.ª ronda", "sarmiento-resistencia", 4, 0, "sol-de-mayo-formosa", { venue: at("Chaco For Ever") }],
      ["1945-11-04", "Grupo D · 1.ª ronda", "san-martin-olavarria", 2, 1, "quilmes-mdp", { venue: at("Estudiantes (Olavarría)") }],
      ["1945-11-04", "Grupo D · 1.ª ronda", "sportivo-25-mayo", 0, 1, "pettirossi", { venue: at("Sportivo (25 de Mayo)") }],
      ["1945-11-04", "Grupo D · 2.ª ronda", "independencia-san-pedro", 3, 1, "racing-colon", { venue: at("Paraná (San Pedro)") }],
      ["1945-11-04", "Grupo D · 2.ª ronda", "gimnasia-mercedes", 0, 7, "sarmiento-junin", { venue: "Estadio de la Liga Mercedina (Mercedes)" }],
      ["1945-11-11", "Grupo D · 2.ª ronda", "boca-tres-arroyos", 6, 2, "sarmiento-pigue", { venue: at("Nacional (Tres Arroyos)") }],
      ["1945-11-11", "Grupo D · 2.ª ronda", "san-martin-olavarria", 3, 1, "pettirossi", { venue: at("Estudiantes (Olavarría)") }],
      ["1945-11-11", "Grupo D · 3.ª ronda", "sarmiento-junin", 9, 2, "independencia-san-pedro", { venue: at("Buenos Aires al Pacífico (Junín)") }],
      ["1945-11-18", "Grupo D · 3.ª ronda", "boca-tres-arroyos", 4, 5, "san-martin-olavarria", { venue: at("Nacional (Tres Arroyos)") }],
      ["1945-11-25", "Grupo D · 4.ª ronda", "san-martin-olavarria", 1, 3, "sarmiento-junin", { venue: at("Racing (Olavarría)") }],
      ["1945-12-09", "Cuartos de final", "estudiantes-sde", 3, 1, "ferro", { venue: at("Atlético Mitre (Santiago del Estero)") }],
      ["1945-12-09", "Cuartos de final", "independiente-rivadavia", 1, 2, "racing", { venue: at("Gimnasia y Esgrima (Mendoza)") }],
      ["1945-12-09", "Cuartos de final", "sarmiento-resistencia", 0, 1, "estudiantes", { venue: at("Sarmiento (Resistencia)") }],
      ["1945-12-16", "Cuartos de final", "sarmiento-junin", 2, 3, "boca", { venue: at("Buenos Aires al Pacífico (Junín)") }],
      ["1946-03-17", "Semifinal", "boca", 2, 1, "racing", { venue: at("Ferro Carril Oeste"), note: "Wikipedia fecha las semifinales el 16 de marzo." }],
      ["1946-03-17", "Semifinal", "estudiantes-sde", 1, 3, "estudiantes", { venue: at("Atlético Mitre (Santiago del Estero)"), note: "Wikipedia fecha las semifinales el 16 de marzo." }],
      ["1946-03-24", "Final", "boca", 4, 4, "estudiantes", { venue: at("San Lorenzo"), note: "Se jugó un desempate." }],
      ["1946-12-18", "Final (desempate)", "boca", 0, 1, "estudiantes", { venue: at("San Lorenzo"), note: "Gol: Pellegrina 29'. Árbitro: L. Amoroso. Público: 40.000." }],
    ],
  ),
  escobar(
    1941,
    { championIds: ["river"], runnerUpIds: ["huracan"], summary: "River Plate, campeón de liga, ganó la Copa Escobar: 1-0 a Huracán en la final." },
    [
      ["1941-11-01", "Cuartos de final", "huracan", 1, 0, "independiente", { venue: CR }],
      ["1941-11-01", "Cuartos de final", "sanlorenzo", 4, 0, "racing", { venue: CR }],
      ["1941-11-01", "Cuartos de final", "newells", 1, 0, "boca", { venue: CR }],
      ["1941-11-02", "Semifinal", "river", 2, 1, "sanlorenzo"],
      ["1941-11-02", "Semifinal", "huracan", 2, 1, "newells", { venue: CR }],
      ["1941-11-02", "Final", "river", 1, 0, "huracan"],
    ],
  ),
  escobar(
    1942,
    { championIds: ["huracan"], runnerUpIds: ["river"], summary: "Huracán ganó la Copa Escobar: 2-0 a River Plate en la final." },
    [
      ["1942-11-26", "Cuartos de final", "boca", 3, 0, "banfield", { venue: "Cancha de San Lorenzo" }],
      ["1942-11-26", "Cuartos de final", "sanlorenzo", 2, 0, "estudiantes", { venue: "Cancha de San Lorenzo" }],
      ["1942-11-26", "Cuartos de final", "huracan", 0, 0, "newells", { venue: "Cancha de San Lorenzo", ...corners("huracan", "4-2") }],
      ["1942-12-01", "Semifinal", "boca", 0, 0, "river", { venue: CR, ...corners("river", "3-2") }],
      ["1942-12-01", "Semifinal", "sanlorenzo", 0, 1, "huracan", { venue: CR, note: "Con alargue." }],
      ["1942-12-01", "Final", "river", 0, 2, "huracan", { venue: CR }],
    ],
  ),
  escobar(
    1943,
    { championIds: ["huracan"], runnerUpIds: ["platense"], summary: "Huracán bicampeón de la Copa Escobar: 0-0 con Platense en la final y 4-1 en córners." },
    [
      ["1943-12-08", "Cuartos de final", "huracan", 1, 0, "river", { venue: "Cancha de River Plate (Monumental)" }],
      ["1943-12-08", "Cuartos de final", "platense", 1, 0, "estudiantes", { venue: "Cancha de River Plate (Monumental)" }],
      ["1943-12-08", "Cuartos de final", "independiente", 1, 1, "sanlorenzo", { venue: "Cancha de River Plate (Monumental)", ...corners("independiente", "4-2") }],
      ["1943-12-11", "Semifinal", "huracan", 0, 0, "independiente", { venue: CSL, advancedId: "huracan", note: "Empataron también en córners (3-3): Huracán pasó por sorteo." }],
      ["1943-12-11", "Semifinal", "platense", 1, 1, "boca", { venue: CSL, ...corners("platense", "7-3") }],
      ["1943-12-11", "Final", "huracan", 0, 0, "platense", { venue: CSL, ...corners("huracan", "4-1", " Huracán campeón.") }],
    ],
  ),
  escobar(
    1944,
    { championIds: ["estudiantes"], runnerUpIds: ["sanlorenzo"], summary: "Estudiantes de La Plata ganó la Copa Escobar: 1-0 a San Lorenzo en la final." },
    [
      ["1944-11-30", "Cuartos de final", "huracan", 2, 1, "racing", { venue: CSL }],
      ["1944-11-30", "Cuartos de final", "sanlorenzo", 2, 0, "independiente", { venue: CSL }],
      ["1944-11-30", "Cuartos de final", "estudiantes", 0, 0, "river", { venue: CSL, ...corners("estudiantes", "4-3") }],
      ["1944-12-02", "Semifinal", "estudiantes", 2, 1, "huracan", { venue: CSL }],
      ["1944-12-02", "Semifinal", "sanlorenzo", 2, 0, "boca", { venue: CSL }],
      ["1944-12-02", "Final", "estudiantes", 1, 0, "sanlorenzo", { venue: CSL }],
    ],
  ),
  escobar(
    1946,
    {
      championIds: [],
      abandoned: true,
      summary: "La Copa Escobar 1946 se empezó a jugar en marzo de 1947 y quedó suspendida después de los cuartos de final: no tuvo campeón.",
      notes: [ESCOBAR, { kind: "dato", text: "Solo se jugaron los cuartos de final (29 de marzo de 1947, en la cancha de San Lorenzo); San Lorenzo, libre, no llegó a jugar. La copa se abandonó." }],
      listedWithoutMatches: { sanlorenzo: "libre en cuartos de final; la copa se abandonó antes de las semifinales" },
    },
    [
      ["1947-03-29", "Cuartos de final", "independiente", 1, 2, "river", { venue: "Cancha de San Lorenzo" }],
      ["1947-03-29", "Cuartos de final", "boca", 0, 1, "racing", { venue: "Cancha de San Lorenzo" }],
      ["1947-03-29", "Cuartos de final", "estudiantes", 2, 2, "central", { venue: "Cancha de San Lorenzo", ...corners("estudiantes", "2-0") }],
    ],
  ),
  escobar(
    1949,
    { championIds: ["newells"], runnerUpIds: ["racing"], summary: "Newell's Old Boys ganó la Copa Escobar: 2-2 con Racing en la final y 4-2 en córners." },
    [
      ["1949-12-09", "Cuartos de final", "newells", 2, 1, "sanlorenzo", { venue: "Cancha de Huracán", note: "Público: 10.000." }],
      ["1949-12-09", "Cuartos de final", "river", 0, 0, "estudiantes", { venue: "Cancha de Huracán", ...corners("river", "8-1") }],
      ["1949-12-09", "Cuartos de final", "velez", 1, 0, "platense", { venue: "Cancha de Huracán" }],
      ["1949-12-10", "Semifinal", "newells", 1, 0, "velez", { venue: "Cancha de Independiente", note: "Público: 40.000." }],
      ["1949-12-10", "Semifinal", "racing", 3, 1, "river", { venue: "Cancha de Independiente" }],
      ["1949-12-10", "Final", "newells", 2, 2, "racing", { venue: "Cancha de Independiente", ...corners("newells", "4-2", " Con alargue.") }],
    ],
  ),
  // ───────── Copa de Competencia Británica (Copa Jorge VI) ─────────
  britanica(
    1944,
    { championIds: ["huracan"], runnerUpIds: ["boca"], summary: "Huracán ganó la primera Copa Británica: 4-2 a Boca Juniors en la final, en el Gasómetro." },
    [
      ["1944-04-09", "Octavos de final", "banfield", 2, 1, "lanus"],
      ["1944-04-09", "Octavos de final", "boca", 3, 2, "racing"],
      ["1944-04-09", "Octavos de final", "chacarita", 1, 0, "atlanta"],
      ["1944-04-09", "Octavos de final", "ferro", 2, 1, "estudiantes"],
      ["1944-04-09", "Octavos de final", "huracan", 2, 1, "velez"],
      ["1944-04-09", "Octavos de final", "newells", 3, 2, "river"],
      ["1944-04-09", "Octavos de final", "platense", 4, 3, "central"],
      ["1944-04-09", "Octavos de final", "sanlorenzo", 4, 1, "independiente"],
      ["1944-05-25", "Cuartos de final", "boca", 4, 2, "banfield"],
      ["1944-05-25", "Cuartos de final", "huracan", 4, 3, "sanlorenzo"],
      ["1944-05-25", "Cuartos de final", "newells", 4, 1, "ferro"],
      ["1944-05-25", "Cuartos de final", "platense", 3, 1, "chacarita"],
      ["1944-06-29", "Semifinal", "boca", 1, 0, "platense", { venue: "Cancha de Chacarita Juniors" }],
      ["1944-06-29", "Semifinal", "huracan", 4, 1, "newells", { venue: CSL }],
      ["1944-12-09", "Final", "huracan", 4, 2, "boca", { venue: CSL }],
    ],
  ),
  britanica(
    1945,
    { championIds: ["racing"], runnerUpIds: ["boca"], summary: "Racing Club ganó la Copa Británica: 4-1 a Boca Juniors en la final, en la cancha de San Lorenzo." },
    [
      ["1945-04-08", "Octavos de final", "boca", 6, 2, "atlanta", { venue: at("Ferro Carril Oeste") }],
      ["1945-04-08", "Octavos de final", "estudiantes", 3, 3, "gimnasia", { venue: at("Racing Club"), note: "Con alargue. Se jugó un desempate." }],
      ["1945-04-08", "Octavos de final", "ferro", 3, 1, "newells", { venue: at("Atlanta") }],
      ["1945-04-08", "Octavos de final", "independiente", 3, 2, "sanlorenzo", { venue: at("River Plate") }],
      ["1945-04-08", "Octavos de final", "racing", 5, 3, "huracan", { venue: at("San Lorenzo") }],
      ["1945-04-08", "Octavos de final", "river", 3, 1, "platense", { venue: at("Boca Juniors") }],
      ["1945-04-08", "Octavos de final", "central", 3, 2, "chacarita", { venue: at("Newell's Old Boys") }],
      ["1945-04-08", "Octavos de final", "velez", 3, 2, "lanus", { venue: at("Platense") }],
      ["1945-05-01", "Octavos de final (desempate)", "gimnasia", 1, 2, "estudiantes"],
      ["1945-06-20", "Cuartos de final", "boca", 1, 0, "independiente", { venue: at("San Lorenzo"), note: "Con alargue." }],
      ["1945-06-20", "Cuartos de final", "estudiantes", 2, 0, "velez", { venue: at("Racing Club") }],
      ["1945-06-20", "Cuartos de final", "ferro", 2, 1, "central", { venue: at("Platense"), note: "Con alargue." }],
      ["1945-06-20", "Cuartos de final", "racing", 3, 2, "river", { venue: at("Boca Juniors") }],
      ["1945-08-31", "Semifinal", "boca", 7, 0, "ferro", { venue: at("Racing Club") }],
      ["1945-08-31", "Semifinal", "racing", 4, 0, "estudiantes", { venue: at("San Lorenzo") }],
      ["1945-10-12", "Final", "racing", 4, 1, "boca", { venue: at("San Lorenzo") }],
    ],
  ),
  britanica(
    1946,
    { championIds: ["boca"], runnerUpIds: ["sanlorenzo"], summary: "Boca Juniors ganó la Copa Británica: 3-1 a San Lorenzo en la final, en la cancha de River Plate." },
    [
      ["1946-04-14", "Octavos de final", "boca", 3, 2, "velez", { venue: at("Ferro Carril Oeste") }],
      ["1946-04-14", "Octavos de final", "chacarita", 4, 2, "lanus", { venue: at("Independiente") }],
      ["1946-04-14", "Octavos de final", "estudiantes", 3, 1, "tigre", { venue: at("Platense") }],
      ["1946-04-14", "Octavos de final", "huracan", 2, 1, "atlanta", { venue: at("Boca Juniors") }],
      ["1946-04-14", "Octavos de final", "independiente", 2, 1, "platense", { venue: at("Atlanta") }],
      ["1946-04-14", "Octavos de final", "river", 4, 0, "racing", { venue: at("San Lorenzo") }],
      ["1946-04-14", "Octavos de final", "central", 4, 2, "newells", { venue: "Rosario" }],
      ["1946-04-14", "Octavos de final", "sanlorenzo", 5, 1, "ferro", { venue: at("Vélez Sarsfield") }],
      ["1946-06-20", "Cuartos de final", "boca", 4, 1, "central", { venue: at("San Lorenzo") }],
      ["1946-06-20", "Cuartos de final", "estudiantes", 1, 0, "independiente", { venue: at("Boca Juniors") }],
      ["1946-06-20", "Cuartos de final", "river", 8, 4, "chacarita", { venue: at("Platense") }],
      ["1946-06-20", "Cuartos de final", "sanlorenzo", 2, 0, "huracan", { venue: at("Ferro Carril Oeste") }],
      ["1946-08-15", "Semifinal", "boca", 2, 0, "river", { venue: at("San Lorenzo") }],
      ["1946-08-15", "Semifinal", "sanlorenzo", 1, 0, "estudiantes", { venue: at("Boca Juniors"), note: "Con alargue." }],
      ["1946-12-14", "Final", "boca", 3, 1, "sanlorenzo", { venue: at("River Plate") }],
    ],
  ),
  britanica(
    1948,
    {
      championIds: [],
      abandoned: true,
      summary: "La cuarta Copa Británica empezó el 4 de abril de 1948 pero solo se jugaron los octavos de final: no tuvo campeón.",
      notes: [BRITANICA, { kind: "dato", text: "Solo se jugaron los octavos de final. La copa quedó sin terminar y sin campeón." }],
    },
    [
      ["1948-04-04", "Octavos de final", "boca", 2, 1, "lanus", { venue: at("Independiente") }],
      ["1948-04-04", "Octavos de final", "estudiantes", 3, 1, "river", { venue: at("Boca Juniors") }],
      ["1948-04-04", "Octavos de final", "gimnasia", 3, 2, "platense", { venue: at("Banfield") }],
      ["1948-04-04", "Octavos de final", "huracan", 2, 0, "banfield", { venue: at("San Lorenzo") }],
      ["1948-04-04", "Octavos de final", "independiente", 5, 4, "chacarita", { venue: at("Huracán"), note: "Con alargue." }],
      ["1948-04-04", "Octavos de final", "central", 3, 2, "newells", { venue: at("Newell's Old Boys") }],
      ["1948-04-04", "Octavos de final", "sanlorenzo", 5, 2, "racing", { venue: at("River Plate") }],
      ["1948-04-04", "Octavos de final", "tigre", 5, 2, "velez", { venue: at("Chacarita Juniors"), note: "Con alargue." }],
    ],
  ),
];
