// Copas nacionales desde 2012 que se definen en uno o dos partidos: Supercopa Argentina, Copa Campeonato,
// Copa del Bicentenario, Trofeo de Campeones y Supercopa Internacional. Se cargan a mano desde la página de RSSSF
// de cada año (arg20XX.html), cruzadas con la lista de copas oficiales de Wikipedia.
import type { Match } from "../../lib/types";
import type { TournamentConfig } from "./config";

const AFA = "Asociación del Fútbol Argentino";
const LPF = "Liga Profesional de Fútbol (AFA)";

type Row = [date: string, stage: string, home: string, hg: number, ag: number, away: string, extra?: Partial<Match>];
const rows = (slug: string, list: Row[]) =>
  list.map(([date, stage, homeId, homeGoals, awayGoals, awayId, extra], i) => ({
    id: `${slug}-${String(i + 1).padStart(3, "0")}`,
    date,
    stage,
    phase: "cup" as const,
    homeId,
    awayId,
    homeGoals,
    awayGoals,
    ...extra,
  }));
const en = (venue: string, extra?: Partial<Match>) => ({ venue, ...extra });

const copa = (
  key: string,
  year: number,
  name: string,
  file: string,
  organizer: string,
  list: Row[],
  championIds: string[],
  runnerUpIds: string[] | undefined,
  summary: string,
  formato: string,
  more: Partial<TournamentConfig> = {},
): TournamentConfig => {
  const slug = `${key}-${year}`;
  return {
    slug,
    kind: "cup",
    year,
    file,
    competition: name,
    title: `${name} ${year}`,
    tournament: `${name} ${year}`,
    organizer,
    championIds,
    runnerUpIds,
    skip: () => true,
    extraMatches: rows(slug, list),
    summary,
    notes: [{ kind: "formato", text: formato }],
    ...more,
  };
};

const SUPERCOPA = "Partido único en cancha neutral entre el campeón de Primera y el campeón de la Copa Argentina.";
const TROFEO = "Partido único en cancha neutral entre los campeones de los dos torneos de Primera del año.";
const INTERNACIONAL = "Partido único entre el ganador del Trofeo de Campeones y el mejor de la tabla anual (o el siguiente, si era el mismo club).";

export const CUP_TOURNAMENTS_MODERN: TournamentConfig[] = [
  // ───────── Supercopa Argentina ─────────
  copa("supercopa-argentina", 2012, "Supercopa Argentina", "arg2012.html", AFA,
    [["2012-11-07", "Final", "boca", 0, 0, "arsenal", en("Estadio Bicentenario (Catamarca)", { advancedId: "arsenal", note: "Arsenal ganó 4-3 por penales." })]],
    ["arsenal"], ["boca"],
    "Arsenal le ganó por penales (0-0, 4-3) a Boca, campeón del Apertura y de la Copa Argentina, en la primera Supercopa Argentina.",
    "Partido único en cancha neutral entre los campeones del Apertura 2011 y la Copa Argentina 2011/12 (Boca) y del Clausura 2012 (Arsenal)."),
  copa("supercopa-argentina", 2013, "Supercopa Argentina", "arg2013.html", AFA,
    [["2014-01-31", "Final", "velez", 1, 0, "arsenal", en("Estadio Juan Gilberto Funes (San Luis)", { note: "Goles: Canteros 59'." })]],
    ["velez"], ["arsenal"],
    "Vélez, campeón de Primera 2012/13, le ganó 1-0 a Arsenal, campeón de la Copa Argentina, en San Luis (enero de 2014).",
    SUPERCOPA),
  copa("supercopa-argentina", 2014, "Supercopa Argentina", "arg2014.html", AFA,
    [["2015-04-25", "Final", "river", 0, 1, "huracan", en("Estadio San Juan del Bicentenario (San Juan)", { note: "Goles: Puch 21'." })]],
    ["huracan"], ["river"],
    "Huracán, campeón de la Copa Argentina, le ganó 1-0 a River, ganador de la Copa Campeonato, en San Juan (abril de 2015).",
    "Partido único en cancha neutral entre el ganador de la Copa Campeonato 2013/14 (River) y el campeón de la Copa Argentina 2013/14 (Huracán)."),
  copa("supercopa-argentina", 2015, "Supercopa Argentina", "arg2015a.html", AFA,
    [["2016-02-10", "Final", "boca", 0, 4, "sanlorenzo", en("Mario Alberto Kempes (Córdoba)")]],
    ["sanlorenzo"], ["boca"],
    "San Lorenzo le ganó 4-0 a Boca en Córdoba (febrero de 2016). Boca había ganado el campeonato y la Copa Argentina, y jugó San Lorenzo como subcampeón.",
    "Partido único en cancha neutral entre el campeón de Primera 2015 y el de la Copa Argentina 2014/15; como Boca ganó los dos, jugó el subcampeón de la liga."),
  copa("supercopa-argentina", 2016, "Supercopa Argentina", "arg2016.html", AFA,
    [["2017-02-04", "Final", "lanus", 3, 0, "river", en("Estadio Único Ciudad de La Plata (La Plata)", { note: "Goles: Acosta 70', Pasquini 80', Sand 88' (de penal)." })]],
    ["lanus"], ["river"],
    "Lanús, campeón de Primera 2016, le ganó 3-0 a River, campeón de la Copa Argentina, en La Plata (febrero de 2017).",
    SUPERCOPA),
  copa("supercopa-argentina", 2017, "Supercopa Argentina", "arg2017.html", AFA,
    [["2018-03-14", "Final", "boca", 0, 2, "river", en("Malvinas Argentinas (Mendoza)", { note: "Goles: Martínez 18' (de penal), Scocco 70'." })]],
    ["river"], ["boca"],
    "River, campeón de la Copa Argentina, le ganó 2-0 a Boca, campeón de Primera 2016/17, en Mendoza (marzo de 2018): el único Superclásico que definió esta copa.",
    SUPERCOPA),
  copa("supercopa-argentina", 2018, "Supercopa Argentina", "arg2018.html", AFA,
    [["2019-05-02", "Final", "boca", 0, 0, "central", en("Malvinas Argentinas (Mendoza)", { advancedId: "boca", note: "Boca ganó 6-5 por penales." })]],
    ["boca"], ["central"],
    "Boca, campeón de Primera 2017/18, le ganó por penales (0-0, 6-5) a Rosario Central, campeón de la Copa Argentina, en Mendoza (mayo de 2019).",
    SUPERCOPA),
  copa("supercopa-argentina", 2019, "Supercopa Argentina", "arg2019.html", AFA,
    [["2021-03-04", "Final", "racing", 0, 5, "river", en("Único Madre de Ciudades (Santiago del Estero)")]],
    ["river"], ["racing"],
    "River, campeón de la Copa Argentina, le ganó 5-0 a Racing, campeón de Primera 2018/19, en Santiago del Estero (marzo de 2021, postergada por la pandemia).",
    SUPERCOPA),
  copa("supercopa-argentina", 2022, "Supercopa Argentina", "arg2022.html", AFA,
    [["2023-03-01", "Final", "boca", 3, 0, "patronato-parana", en("Único Madre de Ciudades (Santiago del Estero)")]],
    ["boca"], ["patronato-parana"],
    "Boca, campeón de Primera 2022, le ganó 3-0 a Patronato, campeón de la Copa Argentina (ya descendido), en Santiago del Estero (marzo de 2023).",
    SUPERCOPA),
  copa("supercopa-argentina", 2023, "Supercopa Argentina", "arg2023.html", AFA,
    [["2024-03-13", "Final", "river", 2, 1, "estudiantes", en("Mario Alberto Kempes (Córdoba)")]],
    ["river"], ["estudiantes"],
    "River, campeón de Primera 2023, le ganó 2-1 a Estudiantes, campeón de la Copa Argentina, en Córdoba (marzo de 2024).",
    SUPERCOPA),
  copa("supercopa-argentina", 2024, "Supercopa Argentina", "arg2024.html", AFA,
    [["2025-09-06", "Final", "velez", 2, 0, "central-cordoba-sde", en("Gigante de Arroyito (Rosario)")]],
    ["velez"], ["central-cordoba-sde"],
    "Vélez, campeón de Primera 2024, le ganó 2-0 a Central Córdoba de Santiago del Estero, campeón de la Copa Argentina, en Rosario (septiembre de 2025).",
    SUPERCOPA),

  // ───────── Copa Campeonato y Copa del Bicentenario ─────────
  copa("copa-campeonato", 2014, "Copa Campeonato", "arg2014.html", AFA,
    [["2014-05-24", "Final", "sanlorenzo", 0, 1, "river", en("Estadio Juan Gilberto Funes (San Luis)", { note: "Goles: Pezzella 72'." })]],
    ["river"], ["sanlorenzo"],
    "River, ganador del Final 2014, le ganó 1-0 a San Lorenzo, ganador del Inicial 2013, en San Luis.",
    "Copa de Campeonato de Primera División 2013/14: partido único en cancha neutral entre los ganadores del Inicial (San Lorenzo) y del Final (River)."),
  copa("copa-bicentenario", 2016, "Copa del Bicentenario", "arg2017.html", AFA,
    [["2016-08-14", "Final", "racing", 0, 1, "lanus", en("Presidente Perón (Avellaneda)", { note: "Goles: Brian Montenegro 90+1'. La cancha se sorteó entre los dos clubes." })]],
    ["lanus"], ["racing"],
    "Lanús, campeón 2016, le ganó 1-0 a Racing, campeón 2014, en el Cilindro, con un gol en el descuento.",
    "Copa por los 200 años de la Independencia: partido único entre los campeones de 2014 (Racing) y 2016 (Lanús)."),

  // ───────── Trofeo de Campeones ─────────
  copa("trofeo-campeones", 2019, "Trofeo de Campeones", "arg2019.html", "Superliga Argentina de Fútbol",
    [["2019-12-14", "Final", "racing", 2, 0, "tigre", en("José María Minella (Mar del Plata)")]],
    ["racing"], ["tigre"],
    "Racing, campeón de la Superliga 2018/19, le ganó 2-0 a Tigre, campeón de la Copa de la Superliga 2019, en Mar del Plata.",
    "Trofeo de Campeones de la Superliga: partido único en cancha neutral entre el campeón de la Superliga y el de la Copa de la Superliga."),
  copa("trofeo-campeones", 2020, "Trofeo de Campeones", "arg2020.html", LPF,
    [["2023-02-22", "Semifinal", "banfield", 2, 3, "river", en("Mario Alberto Kempes (Córdoba)")]],
    [], undefined,
    "Se jugó recién en 2023 y quedó sin terminar: River le ganó 3-2 a Banfield en la semifinal, pero la final con Boca nunca se jugó.",
    "Boca ganó los dos torneos de la temporada 2020 (Superliga 2019/20 y Copa Diego Maradona), así que los subcampeones (River y Banfield) jugaron una semifinal por el lugar en la final con Boca.",
    { abandoned: true }),
  copa("trofeo-campeones", 2021, "Trofeo de Campeones", "arg2021.html", LPF,
    [["2021-12-18", "Final", "river", 4, 0, "colon-santa-fe", en("Único Madre de Ciudades (Santiago del Estero)")]],
    ["river"], ["colon-santa-fe"],
    "River, campeón de la Liga Profesional 2021, le ganó 4-0 a Colón, campeón de la Copa de la Liga 2021, en Santiago del Estero.",
    TROFEO),
  copa("trofeo-campeones", 2022, "Trofeo de Campeones", "arg2022.html", LPF,
    [
      ["2022-11-02", "Semifinal", "tigre", 2, 3, "racing", en("Tomás Adolfo Ducó (Parque Patricios)", { note: "Con alargue." })],
      ["2022-11-06", "Final", "boca", 1, 2, "racing", en("Único del Parque La Pedrera (Villa Mercedes)", { note: "Con alargue." })],
    ],
    ["racing"], ["boca"],
    "Racing le ganó la final a Boca (2-1 con alargue) en San Luis. Boca había ganado los dos torneos del año; Racing llegó ganándole la semifinal a Tigre.",
    "Boca ganó los dos torneos de 2022 (Copa de la Liga y Liga Profesional): los subcampeones (Racing y Tigre) jugaron una semifinal por el lugar en la final con Boca."),
  copa("trofeo-campeones", 2023, "Trofeo de Campeones", "arg2023.html", LPF,
    [["2023-12-22", "Final", "central", 0, 2, "river", en("Único Madre de Ciudades (Santiago del Estero)")]],
    ["river"], ["central"],
    "River, campeón de la Liga Profesional 2023, le ganó 2-0 a Rosario Central, campeón de la Copa de la Liga 2023, en Santiago del Estero.",
    TROFEO),
  copa("trofeo-campeones", 2024, "Trofeo de Campeones", "arg2024.html", LPF,
    [["2024-12-21", "Final", "velez", 0, 3, "estudiantes", en("Único Madre de Ciudades (Santiago del Estero)")]],
    ["estudiantes"], ["velez"],
    "Estudiantes, campeón de la Copa de la Liga 2024, le ganó 3-0 a Vélez, campeón de la Liga Profesional 2024, en Santiago del Estero.",
    TROFEO),
  copa("trofeo-campeones", 2025, "Trofeo de Campeones", "arg2025.html", LPF,
    [["2025-12-20", "Final", "estudiantes", 2, 1, "platense", en("Estadio Único (San Nicolás)")]],
    ["estudiantes"], ["platense"],
    "Estudiantes, campeón del Clausura 2025, le ganó 2-1 a Platense, campeón del Apertura, en San Nicolás.",
    TROFEO),

  // ───────── Supercopa Internacional ─────────
  copa("supercopa-internacional", 2022, "Supercopa Internacional", "arg2022.html", LPF,
    [["2023-01-20", "Final", "boca", 1, 2, "racing", en("Estadio Hazza bin Zayed (Al Ain, Emiratos Árabes Unidos)")]],
    ["racing"], ["boca"],
    "Racing le ganó 2-1 a Boca en Al Ain, Emiratos Árabes Unidos (enero de 2023).",
    INTERNACIONAL),
  copa("supercopa-internacional", 2023, "Supercopa Internacional", "arg2023.html", LPF,
    [["2025-03-05", "Final", "river", 0, 0, "talleres", en("Estadio Ueno La Nueva Olla (Asunción, Paraguay)", { advancedId: "talleres", note: "Con alargue. Talleres ganó 3-2 por penales." })]],
    ["talleres"], ["river"],
    "Talleres le ganó por penales (0-0, 3-2) a River en Asunción, Paraguay (marzo de 2025).",
    "Partido único entre el ganador del Trofeo de Campeones 2023 (River) y el mejor de la tabla anual; como era el mismo club, jugó el segundo (Talleres)."),
  copa("supercopa-internacional", 2024, "Supercopa Internacional", "arg2024.html", LPF,
    [["2025-07-08", "Final", "estudiantes", 0, 2, "velez", en("Libertadores de América - Ricardo Enrique Bochini (Avellaneda)")]],
    ["velez"], ["estudiantes"],
    "Vélez, primero de la tabla anual 2024, le ganó 2-0 a Estudiantes, ganador del Trofeo de Campeones, en Avellaneda (julio de 2025).",
    INTERNACIONAL),
];
